import sys

from setuptools_scm.version import ScmVersion, guess_next_version
from setuptools_scm import Configuration, _get_version
from setuptools_scm._version_cls import _version_as_tuple
from argparse import ArgumentParser


class Versionner:
    def __init__(self, consider_dirty=True, dev_version=None):
        self.consider_dirty = consider_dirty
        self.dev_version = dev_version

    def get_version(self, version: ScmVersion):
        dev = (
            self.dev_version
            if self.dev_version is not None
            else (version.distance if version.distance else 0)
            + int(version.dirty and self.consider_dirty)
        )
        if dev:
            return version.format_next_version(
                guess_next_version, "{guessed}" + f".dev{dev}"
            )
        return version.format_with("{tag}")


def main():
    parser = ArgumentParser("ArmoniK Python version generator")
    parser.add_argument("-n", "--no-dirty", action="store_true")
    parser.add_argument("-w", "--write-to", required=False, type=str)
    parser.add_argument("-d", "--dev", type=int)
    args = parser.parse_args()
    config = Configuration(root="../..", local_scheme="no-local-version")
    versionner = Versionner(not args.no_dirty, dev_version=args.dev)
    config.version_scheme = versionner.get_version
    version = _get_version(config)
    print(version)
    if args.write_to:
        try:
            with open(args.write_to, "w") as f:
                f.writelines(
                    [
                        "# generated by genversion.py, based on setuptools_scm\n",
                        f'__version__ = "{version}"\n',
                        f"__version_tuple__ = {_version_as_tuple(version)}\n",
                    ]
                )
        except Exception as e:
            print(f"Couldn't write to file {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
