import sys
from argparse import ArgumentParser

from setuptools_scm.version import ScmVersion, guess_next_version
from setuptools_scm import get_version
from packaging.version import Version as PkgVersion


def version_as_tuple(version_str: str) -> tuple:
    v = PkgVersion(version_str)
    return v.release + ((f"dev{v.dev}",) if v.dev is not None else ())


def main():
    parser = ArgumentParser("ArmoniK Python version generator")
    parser.add_argument("-n", "--no-dirty", action="store_true")
    parser.add_argument("-w", "--write-to", required=False, type=str)
    parser.add_argument("-d", "--dev", type=int)
    args = parser.parse_args()

    consider_dirty = not args.no_dirty
    dev_version = args.dev

    def version_scheme(version: ScmVersion) -> str:
        dev = (
            dev_version
            if dev_version is not None
            else (version.distance if version.distance else 0)
            + int(version.dirty and consider_dirty)
        )
        if dev:
            return version.format_next_version(guess_next_version, "{guessed}" + f".dev{dev}")
        return version.format_with("{tag}")

    version = get_version(
        root="../..",
        version_scheme=version_scheme,
        local_scheme="no-local-version",
    )
    print(version)
    if args.write_to:
        try:
            with open(args.write_to, "w") as f:
                f.writelines(
                    [
                        "# generated by genversion.py, based on setuptools_scm\n",
                        f'__version__ = "{version}"\n',
                        f"__version_tuple__ = {version_as_tuple(version)}\n",
                    ]
                )
        except Exception as e:
            print(f"Couldn't write to file {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
