# A path to the cache directory.
cache-dir = ".ruff_cache"

# The style in which violation messages should be formatted.
output-format = "grouped"

# Enable fix behavior by-default when running `ruff`
fix = false

# Enable application of unsafe fixes.
unsafe-fixes = false

# Enumerate all fixed violations.
show-fixes = true

# Disable preview features.
preview = false

# The minimum Python version targetted is Python 3.10.
target-version = "py38"

# Allow imports relative to the "src/armonik" and "test" directories.
src = ["src/armonik", "test"]

# Allow lines to be as long as 110.
line-length = 100

# Use 4-long indents
indent-width = 4

[lint]
# A list of file patterns to exclude from formatting and linting.
exclude = ["*.pyi"]

# By default all rules are considered fixable.
fixable = ["ALL"]

[format]
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Use `\n` line endings for all files
line-ending = "lf"

# Enable auto-formatting of code examples in docstrings.
docstring-code-format = true

# Allow lines to be as long as 100 for code snippets in
# docstrings.
docstring-code-line-length = 100
