// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/schema/shapes.json). Do not edit.

package ak.borrow;

/** Protos/V1/objects.proto */
public final class TaskOptions {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public java.util.TreeMap<ak.Utf8View, ak.Utf8View> options = new java.util.TreeMap<ak.Utf8View, ak.Utf8View>();
  public Duration max_duration = null;
  public int max_retries = 0;
  public int priority = 0;
  public ak.Utf8View partition_id = ak.Utf8View.EMPTY;
  public ak.Utf8View application_name = ak.Utf8View.EMPTY;
  public ak.Utf8View application_version = ak.Utf8View.EMPTY;
  public ak.Utf8View application_namespace = ak.Utf8View.EMPTY;
  public ak.Utf8View application_service = ak.Utf8View.EMPTY;
  public ak.Utf8View engine_type = ak.Utf8View.EMPTY;
}
