// This file is part of the ArmoniK project
//
// Copyright (C) ANEO, 2021-2026. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License")
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.Json;

namespace ArmoniK.Api.TransportOptionsGenerator
{
  /// <summary>
  ///   Turns the JSON schema of the armonik-transport option vocabulary into a C# options class.
  /// </summary>
  public static class Generator
  {
    /// <summary>
    ///   Namespace of the generated class.
    /// </summary>
    public const string Namespace = "ArmoniK.Api.Client.Native";

    /// <summary>
    ///   Name of the generated class.
    /// </summary>
    public const string ClassName = "TransportOptions";

    private const string Eol = "\n";

    // The licence lines pad "//" with a space, as every other source file in the repository does.
    // They live in string literals rather than in a block below, where an editor trimming trailing
    // whitespace would silently change the generated file. The year is spelled out rather than read
    // from the clock: the same schema has to give the same bytes.
    private static readonly string[] LicenceHeader =
    {
      "// This file is part of the ArmoniK project",
      "// ",
      "// Copyright (C) ANEO, 2021-2026. All rights reserved.",
      "// ",
      "// Licensed under the Apache License, Version 2.0 (the \"License\")",
      "// you may not use this file except in compliance with the License.",
      "// You may obtain a copy of the License at",
      "// ",
      "//     http://www.apache.org/licenses/LICENSE-2.0",
      "// ",
      "// Unless required by applicable law or agreed to in writing, software",
      "// distributed under the License is distributed on an \"AS IS\" BASIS,",
      "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
      "// See the License for the specific language governing permissions and",
      "// limitations under the License.",
    };

    // The banner comes before the licence: a tool that reads only the first line then knows the file
    // is generated and leaves it alone, and reformatting it would break the check that regenerates
    // it.
    private const string Banner = @"// <auto-generated>
//   Generated by packages/csharp/tools/ArmoniK.Api.TransportOptionsGenerator from the JSON schema
//   of the armonik-transport option vocabulary. Edits are lost on the next run.
// </auto-generated>
";

    private const string Rules = @"// The class is the union of the options the schema names: those at its root and those in every
// allOf/anyOf branch, deduplicated by name, the first description winning.
//
// No validation is generated. The anyOf groups are tautological - one branch requires nothing, so
// every document satisfies the group - and they document the accepted shapes rather than constrain
// them. The transport is the single validator, and it refuses by option name.
//
// Every option is text by contract, so every property is a string defaulting to the empty string.
//
// ToTransportJson leaves an empty option out: the schema requires none of them and a missing key
// reads as the empty string, so an omitted option says what an empty one would, and the document
// carries only what was set. It writes its own JSON, so that hosting this file costs no
// serialisation dependency.
";

    private const string JsonWriter = @"    /// <summary>
    ///   Appends one option to <paramref name=""builder"" />, unless it carries nothing.
    /// </summary>
    private static void AppendOption(StringBuilder builder,
                                     string        name,
                                     string        value)
    {
      if (string.IsNullOrEmpty(value))
      {
        return;
      }

      // The opening brace stands alone in the builder until the first option lands.
      if (builder.Length > 1)
      {
        builder.Append(',');
      }

      AppendString(builder,
                   name);
      builder.Append(':');
      AppendString(builder,
                   value);
    }

    /// <summary>
    ///   Appends <paramref name=""value"" /> as a JSON string literal.
    /// </summary>
    private static void AppendString(StringBuilder builder,
                                     string        value)
    {
      builder.Append('""');

      foreach (var c in value)
      {
        switch (c)
        {
          case '""':
            builder.Append(""\\\"""");
            break;
          case '\\':
            builder.Append(""\\\\"");
            break;
          case '\b':
            builder.Append(""\\b"");
            break;
          case '\f':
            builder.Append(""\\f"");
            break;
          case '\n':
            builder.Append(""\\n"");
            break;
          case '\r':
            builder.Append(""\\r"");
            break;
          case '\t':
            builder.Append(""\\t"");
            break;
          default:
            // JSON asks for an escape below U+0020, and nowhere else.
            if (c < ' ')
            {
              builder.Append(""\\u"");
              builder.Append(((int)c).ToString(""x4"",
                                               CultureInfo.InvariantCulture));
            }
            else
            {
              builder.Append(c);
            }

            break;
        }
      }

      builder.Append('""');
    }
";

    /// <summary>
    ///   Reads the option vocabulary out of <paramref name="schemaJson" /> and writes the class that
    ///   carries it.
    /// </summary>
    /// <param name="schemaJson">The JSON schema, as printed by the armonik-transport example.</param>
    /// <returns>The whole content of the generated file, newline terminated.</returns>
    /// <exception cref="InvalidOperationException">The schema names an option this generator cannot spell.</exception>
    public static string Generate(string schemaJson)
    {
      using var schema = JsonDocument.Parse(schemaJson);
      return Emit(ReadOptions(schema.RootElement));
    }

    /// <summary>
    ///   Collects the options, deduplicated by name, the first occurrence winning.
    /// </summary>
    /// <remarks>
    ///   The vocabulary is flat, so every <c>properties</c> object the schema holds - at the root, in
    ///   an <c>allOf</c> entry, in one of its <c>anyOf</c> branches - names options of that same one
    ///   vocabulary. A name really does come back with a different description: <c>ProxyAddress</c>
    ///   documents a credential-free URL in one branch and a URL carrying its credentials in the
    ///   other, and the first describes the option rather than a shape.
    /// </remarks>
    private static List<Option> ReadOptions(JsonElement root)
    {
      var options = new List<Option>();
      var seen = new HashSet<string>(StringComparer.Ordinal);

      foreach (var property in PropertyBags(root)
                 .SelectMany(bag => bag.EnumerateObject()))
      {
        if (!IsOptionName(property.Name))
        {
          throw new InvalidOperationException($"Option '{property.Name}' is not a PascalCase name");
        }

        // Every value is text by contract. An option typed otherwise is a change of contract, and
        // belongs in a decision rather than in a conversion invented here.
        if (!IsText(property.Value))
        {
          throw new InvalidOperationException($"Option '{property.Name}' is not typed as a string");
        }

        if (seen.Add(property.Name))
        {
          options.Add(new Option(property.Name,
                                 Description(property)));
        }
      }

      if (options.Count == 0)
      {
        throw new InvalidOperationException("The schema names no option at all");
      }

      return options;
    }

    /// <summary>
    ///   Every <c>properties</c> object the schema holds, in the order it holds them.
    /// </summary>
    /// <remarks>
    ///   A schema object that names no option is skipped rather than refused: an <c>allOf</c> entry
    ///   usually does nothing but group the branches under it.
    /// </remarks>
    private static IEnumerable<JsonElement> PropertyBags(JsonElement root)
    {
      if (TryProperties(root,
                        out var rootBag))
      {
        yield return rootBag;
      }

      if (!root.TryGetProperty("allOf",
                               out var allOf))
      {
        yield break;
      }

      foreach (var entry in allOf.EnumerateArray())
      {
        if (TryProperties(entry,
                          out var entryBag))
        {
          yield return entryBag;
        }

        if (!entry.TryGetProperty("anyOf",
                                  out var anyOf))
        {
          continue;
        }

        foreach (var branch in anyOf.EnumerateArray())
        {
          if (TryProperties(branch,
                            out var branchBag))
          {
            yield return branchBag;
          }
        }
      }
    }

    private static bool TryProperties(JsonElement element,
                                      out JsonElement properties)
      => element.TryGetProperty("properties",
                                out properties) && properties.ValueKind == JsonValueKind.Object;

    private static bool IsText(JsonElement option)
      => option.TryGetProperty("type",
                               out var type) && type.ValueKind == JsonValueKind.String && type.GetString() == "string";

    // An option with nothing to say about itself is documented by its own name, which is at least
    // the name a deployment sets.
    private static string Description(JsonProperty option)
      => option.Value.TryGetProperty("description",
                                     out var description)
           ? description.GetString() ?? option.Name
           : option.Name;

    private static string Emit(List<Option> options)
    {
      var builder = new StringBuilder();

      Block(builder,
            Banner);
      Line(builder,
           "");

      foreach (var line in LicenceHeader)
      {
        Line(builder,
             line);
      }

      Line(builder,
           "");
      Block(builder,
            Rules);
      Line(builder,
           "");
      Line(builder,
           "using System.Globalization;");
      Line(builder,
           "using System.Text;");
      Line(builder,
           "");
      Line(builder,
           $"namespace {Namespace}");
      Line(builder,
           "{");
      Line(builder,
           "  /// <summary>");
      Line(builder,
           "  ///   The options of the native transport, one flat vocabulary whose every value is text.");
      Line(builder,
           "  /// </summary>");
      Line(builder,
           "  /// <remarks>");
      Line(builder,
           "  ///   An instance may carry a real <see cref=\"ProxyPassword\" />, which is a secret: neither it");
      Line(builder,
           "  ///   nor the instance holding it is ever to be logged or dumped.");
      Line(builder,
           "  /// </remarks>");
      Line(builder,
           $"  public class {ClassName}");
      Line(builder,
           "  {");

      foreach (var option in options)
      {
        EmitDocumentation(builder,
                          option.Description);
        Line(builder,
             $"    public string {option.Name} {{ get; set; }} = \"\";");
        Line(builder,
             "");
      }

      Line(builder,
           "    /// <summary>");
      Line(builder,
           "    ///   Writes the options that are set as a JSON document of the transport vocabulary.");
      Line(builder,
           "    /// </summary>");
      Line(builder,
           "    /// <returns>A JSON object carrying every option that is set, and none of the others.</returns>");
      Line(builder,
           "    public string ToTransportJson()");
      Line(builder,
           "    {");
      Line(builder,
           "      var builder = new StringBuilder();");
      Line(builder,
           "      builder.Append('{');");
      Line(builder,
           "");

      foreach (var name in options.Select(option => option.Name))
      {
        Line(builder,
             "      AppendOption(builder,");
        Line(builder,
             $"                   \"{name}\",");
        Line(builder,
             $"                   {name});");
      }

      Line(builder,
           "");
      Line(builder,
           "      builder.Append('}');");
      Line(builder,
           "      return builder.ToString();");
      Line(builder,
           "    }");
      Line(builder,
           "");
      Block(builder,
            JsonWriter);
      Line(builder,
           "  }");
      Line(builder,
           "}");

      return builder.ToString();
    }

    private static void EmitDocumentation(StringBuilder builder,
                                          string        description)
    {
      Line(builder,
           "    /// <summary>");

      foreach (var line in Normalise(description)
                 .Split('\n'))
      {
        var text = XmlEscape(line.Trim());
        Line(builder,
             text.Length == 0
               ? "    ///"
               : $"    ///   {text}");
      }

      Line(builder,
           "    /// </summary>");
    }

    private static void Line(StringBuilder builder,
                             string        text)
      => builder.Append(text)
                .Append(Eol);

    private static void Block(StringBuilder builder,
                              string        text)
      => builder.Append(Normalise(text));

    // A verbatim literal carries the line endings of the file it is written in, and the generated
    // file has one line ending on every platform.
    private static string Normalise(string text)
      => text.Replace("\r\n",
                      "\n");

    private static string XmlEscape(string text)
      => text.Replace("&",
                      "&amp;")
             .Replace("<",
                      "&lt;")
             .Replace(">",
                      "&gt;");

    // The vocabulary is PascalCase, and the leading capital is what makes the name safe to declare:
    // every C# keyword is lower case, so no option can collide with one.
    private static bool IsOptionName(string name)
      => name.Length > 0 && char.IsUpper(name[0]) && name.All(c => char.IsLetterOrDigit(c) || c == '_');

    private readonly record struct Option(string Name,
                                          string Description);
  }
}
