// @generated by ffi/poc/java/gen/java_corpus.py (corpus glue). Do not edit.

package ak.corpus;

import ak.Dec;
import ak.Enc;

/** Root name -> each arm's decode and encode, so the corpus harness carries no
 *  reflection. Arm R for every message; the binding for the C ABI's roots. */
public final class Dispatch {
  private Dispatch() {}

  public static final String[] ALL = {"Timestamp", "Duration", "ResultRaw", "TaskOptions", "TaskOutput", "TaskDetailed", "TaskSummary", "Probe", "Empty", "UploadResultData", "MetricsBatch", "Pair", "ListResultsResponse", "ListTasksDetailedResponse", "ListTaskSummaryResponse", "ListProbeResponse", "ListMetricsResponse", "UploadResultDataMessage", "DualResponse", "ChunkLeaf", "ChunkInner", "ChunkElement", "ChunkedResponse", "ChunkedResponseWide", "LeafElement", "LeafResponse", "Surrogate", "SurrogateInner", "Nest", "WireZoo"};
  public static final String[] ABI = {"Timestamp", "Duration", "ResultRaw", "TaskOptions", "TaskOutput", "TaskDetailed", "TaskSummary", "Probe", "Empty", "UploadResultData", "MetricsBatch", "Pair", "ListResultsResponse", "ListTasksDetailedResponse", "ListTaskSummaryResponse", "ListProbeResponse", "ListMetricsResponse", "UploadResultDataMessage", "DualResponse", "ChunkLeaf", "ChunkInner", "ChunkElement", "ChunkedResponse", "ChunkedResponseWide", "LeafElement", "LeafResponse", "Surrogate", "SurrogateInner", "WireZoo"};

  /** The no-unknown build (WP5 step 10) has no retain codec. */
  public static Object decRRetain(String root, byte[] b) {
    throw new UnsupportedOperationException("no-unknown build: no retain mode");
  }

  public static byte[] encRRetain(String root, Object o) {
    throw new UnsupportedOperationException("no-unknown build: no retain mode");
  }

  public static Object decR(String root, byte[] b) {
    Dec d = new Dec().reset(b, 0, b.length);
    switch (root) {
      case "Timestamp": return Codec.decTimestamp(d);
      case "Duration": return Codec.decDuration(d);
      case "ResultRaw": return Codec.decResultRaw(d);
      case "TaskOptions": return Codec.decTaskOptions(d);
      case "TaskOutput": return Codec.decTaskOutput(d);
      case "TaskDetailed": return Codec.decTaskDetailed(d);
      case "TaskSummary": return Codec.decTaskSummary(d);
      case "Probe": return Codec.decProbe(d);
      case "Empty": return Codec.decEmpty(d);
      case "UploadResultData": return Codec.decUploadResultData(d);
      case "MetricsBatch": return Codec.decMetricsBatch(d);
      case "Pair": return Codec.decPair(d);
      case "ListResultsResponse": return Codec.decListResultsResponse(d);
      case "ListTasksDetailedResponse": return Codec.decListTasksDetailedResponse(d);
      case "ListTaskSummaryResponse": return Codec.decListTaskSummaryResponse(d);
      case "ListProbeResponse": return Codec.decListProbeResponse(d);
      case "ListMetricsResponse": return Codec.decListMetricsResponse(d);
      case "UploadResultDataMessage": return Codec.decUploadResultDataMessage(d);
      case "DualResponse": return Codec.decDualResponse(d);
      case "ChunkLeaf": return Codec.decChunkLeaf(d);
      case "ChunkInner": return Codec.decChunkInner(d);
      case "ChunkElement": return Codec.decChunkElement(d);
      case "ChunkedResponse": return Codec.decChunkedResponse(d);
      case "ChunkedResponseWide": return Codec.decChunkedResponseWide(d);
      case "LeafElement": return Codec.decLeafElement(d);
      case "LeafResponse": return Codec.decLeafResponse(d);
      case "Surrogate": return Codec.decSurrogate(d);
      case "SurrogateInner": return Codec.decSurrogateInner(d);
      case "Nest": return Codec.decNest(d);
      case "WireZoo": return Codec.decWireZoo(d);
      default: throw new IllegalArgumentException(root);
    }
  }

  public static byte[] encR(String root, Object o) {
    Enc e = new Enc(Codec.SITES);
    e.reset();
    switch (root) {
      case "Timestamp": Codec.encTimestamp(e, (Timestamp) o); break;
      case "Duration": Codec.encDuration(e, (Duration) o); break;
      case "ResultRaw": Codec.encResultRaw(e, (ResultRaw) o); break;
      case "TaskOptions": Codec.encTaskOptions(e, (TaskOptions) o); break;
      case "TaskOutput": Codec.encTaskOutput(e, (TaskOutput) o); break;
      case "TaskDetailed": Codec.encTaskDetailed(e, (TaskDetailed) o); break;
      case "TaskSummary": Codec.encTaskSummary(e, (TaskSummary) o); break;
      case "Probe": Codec.encProbe(e, (Probe) o); break;
      case "Empty": Codec.encEmpty(e, (Empty) o); break;
      case "UploadResultData": Codec.encUploadResultData(e, (UploadResultData) o); break;
      case "MetricsBatch": Codec.encMetricsBatch(e, (MetricsBatch) o); break;
      case "Pair": Codec.encPair(e, (Pair) o); break;
      case "ListResultsResponse": Codec.encListResultsResponse(e, (ListResultsResponse) o); break;
      case "ListTasksDetailedResponse": Codec.encListTasksDetailedResponse(e, (ListTasksDetailedResponse) o); break;
      case "ListTaskSummaryResponse": Codec.encListTaskSummaryResponse(e, (ListTaskSummaryResponse) o); break;
      case "ListProbeResponse": Codec.encListProbeResponse(e, (ListProbeResponse) o); break;
      case "ListMetricsResponse": Codec.encListMetricsResponse(e, (ListMetricsResponse) o); break;
      case "UploadResultDataMessage": Codec.encUploadResultDataMessage(e, (UploadResultDataMessage) o); break;
      case "DualResponse": Codec.encDualResponse(e, (DualResponse) o); break;
      case "ChunkLeaf": Codec.encChunkLeaf(e, (ChunkLeaf) o); break;
      case "ChunkInner": Codec.encChunkInner(e, (ChunkInner) o); break;
      case "ChunkElement": Codec.encChunkElement(e, (ChunkElement) o); break;
      case "ChunkedResponse": Codec.encChunkedResponse(e, (ChunkedResponse) o); break;
      case "ChunkedResponseWide": Codec.encChunkedResponseWide(e, (ChunkedResponseWide) o); break;
      case "LeafElement": Codec.encLeafElement(e, (LeafElement) o); break;
      case "LeafResponse": Codec.encLeafResponse(e, (LeafResponse) o); break;
      case "Surrogate": Codec.encSurrogate(e, (Surrogate) o); break;
      case "SurrogateInner": Codec.encSurrogateInner(e, (SurrogateInner) o); break;
      case "Nest": Codec.encNest(e, (Nest) o); break;
      case "WireZoo": Codec.encWireZoo(e, (WireZoo) o); break;
      default: throw new IllegalArgumentException(root);
    }
    return e.toBytes();
  }

  public static Object decFfi(Binding b, String root, byte[] w) {
    switch (root) {
      case "Timestamp": return b.decodeTimestamp(w, 0, w.length);
      case "Duration": return b.decodeDuration(w, 0, w.length);
      case "ResultRaw": return b.decodeResultRaw(w, 0, w.length);
      case "TaskOptions": return b.decodeTaskOptions(w, 0, w.length);
      case "TaskOutput": return b.decodeTaskOutput(w, 0, w.length);
      case "TaskDetailed": return b.decodeTaskDetailed(w, 0, w.length);
      case "TaskSummary": return b.decodeTaskSummary(w, 0, w.length);
      case "Probe": return b.decodeProbe(w, 0, w.length);
      case "Empty": return b.decodeEmpty(w, 0, w.length);
      case "UploadResultData": return b.decodeUploadResultData(w, 0, w.length);
      case "MetricsBatch": return b.decodeMetricsBatch(w, 0, w.length);
      case "Pair": return b.decodePair(w, 0, w.length);
      case "ListResultsResponse": return b.decodeListResultsResponse(w, 0, w.length);
      case "ListTasksDetailedResponse": return b.decodeListTasksDetailedResponse(w, 0, w.length);
      case "ListTaskSummaryResponse": return b.decodeListTaskSummaryResponse(w, 0, w.length);
      case "ListProbeResponse": return b.decodeListProbeResponse(w, 0, w.length);
      case "ListMetricsResponse": return b.decodeListMetricsResponse(w, 0, w.length);
      case "UploadResultDataMessage": return b.decodeUploadResultDataMessage(w, 0, w.length);
      case "DualResponse": return b.decodeDualResponse(w, 0, w.length);
      case "ChunkLeaf": return b.decodeChunkLeaf(w, 0, w.length);
      case "ChunkInner": return b.decodeChunkInner(w, 0, w.length);
      case "ChunkElement": return b.decodeChunkElement(w, 0, w.length);
      case "ChunkedResponse": return b.decodeChunkedResponse(w, 0, w.length);
      case "ChunkedResponseWide": return b.decodeChunkedResponseWide(w, 0, w.length);
      case "LeafElement": return b.decodeLeafElement(w, 0, w.length);
      case "LeafResponse": return b.decodeLeafResponse(w, 0, w.length);
      case "Surrogate": return b.decodeSurrogate(w, 0, w.length);
      case "SurrogateInner": return b.decodeSurrogateInner(w, 0, w.length);
      case "WireZoo": return b.decodeWireZoo(w, 0, w.length);
      default: throw new IllegalArgumentException(root);
    }
  }

  public static Object parseFfi(Binding b, String root, byte[] w) {
    switch (root) {
      case "Timestamp": return b.parseTimestamp(w, 0, w.length);
      case "Duration": return b.parseDuration(w, 0, w.length);
      case "ResultRaw": return b.parseResultRaw(w, 0, w.length);
      case "TaskOptions": return b.parseTaskOptions(w, 0, w.length);
      case "TaskOutput": return b.parseTaskOutput(w, 0, w.length);
      case "TaskDetailed": return b.parseTaskDetailed(w, 0, w.length);
      case "TaskSummary": return b.parseTaskSummary(w, 0, w.length);
      case "Probe": return b.parseProbe(w, 0, w.length);
      case "Empty": return b.parseEmpty(w, 0, w.length);
      case "UploadResultData": return b.parseUploadResultData(w, 0, w.length);
      case "MetricsBatch": return b.parseMetricsBatch(w, 0, w.length);
      case "Pair": return b.parsePair(w, 0, w.length);
      case "ListResultsResponse": return b.parseListResultsResponse(w, 0, w.length);
      case "ListTasksDetailedResponse": return b.parseListTasksDetailedResponse(w, 0, w.length);
      case "ListTaskSummaryResponse": return b.parseListTaskSummaryResponse(w, 0, w.length);
      case "ListProbeResponse": return b.parseListProbeResponse(w, 0, w.length);
      case "ListMetricsResponse": return b.parseListMetricsResponse(w, 0, w.length);
      case "UploadResultDataMessage": return b.parseUploadResultDataMessage(w, 0, w.length);
      case "DualResponse": return b.parseDualResponse(w, 0, w.length);
      case "ChunkLeaf": return b.parseChunkLeaf(w, 0, w.length);
      case "ChunkInner": return b.parseChunkInner(w, 0, w.length);
      case "ChunkElement": return b.parseChunkElement(w, 0, w.length);
      case "ChunkedResponse": return b.parseChunkedResponse(w, 0, w.length);
      case "ChunkedResponseWide": return b.parseChunkedResponseWide(w, 0, w.length);
      case "LeafElement": return b.parseLeafElement(w, 0, w.length);
      case "LeafResponse": return b.parseLeafResponse(w, 0, w.length);
      case "Surrogate": return b.parseSurrogate(w, 0, w.length);
      case "SurrogateInner": return b.parseSurrogateInner(w, 0, w.length);
      case "WireZoo": return b.parseWireZoo(w, 0, w.length);
      default: throw new IllegalArgumentException(root);
    }
  }

  public static byte[] encFfi(Binding b, String root, Object o) {
    switch (root) {
      case "Timestamp": b.encodeTimestamp((Timestamp) o); break;
      case "Duration": b.encodeDuration((Duration) o); break;
      case "ResultRaw": b.encodeResultRaw((ResultRaw) o); break;
      case "TaskOptions": b.encodeTaskOptions((TaskOptions) o); break;
      case "TaskOutput": b.encodeTaskOutput((TaskOutput) o); break;
      case "TaskDetailed": b.encodeTaskDetailed((TaskDetailed) o); break;
      case "TaskSummary": b.encodeTaskSummary((TaskSummary) o); break;
      case "Probe": b.encodeProbe((Probe) o); break;
      case "Empty": b.encodeEmpty((Empty) o); break;
      case "UploadResultData": b.encodeUploadResultData((UploadResultData) o); break;
      case "MetricsBatch": b.encodeMetricsBatch((MetricsBatch) o); break;
      case "Pair": b.encodePair((Pair) o); break;
      case "ListResultsResponse": b.encodeListResultsResponse((ListResultsResponse) o); break;
      case "ListTasksDetailedResponse": b.encodeListTasksDetailedResponse((ListTasksDetailedResponse) o); break;
      case "ListTaskSummaryResponse": b.encodeListTaskSummaryResponse((ListTaskSummaryResponse) o); break;
      case "ListProbeResponse": b.encodeListProbeResponse((ListProbeResponse) o); break;
      case "ListMetricsResponse": b.encodeListMetricsResponse((ListMetricsResponse) o); break;
      case "UploadResultDataMessage": b.encodeUploadResultDataMessage((UploadResultDataMessage) o); break;
      case "DualResponse": b.encodeDualResponse((DualResponse) o); break;
      case "ChunkLeaf": b.encodeChunkLeaf((ChunkLeaf) o); break;
      case "ChunkInner": b.encodeChunkInner((ChunkInner) o); break;
      case "ChunkElement": b.encodeChunkElement((ChunkElement) o); break;
      case "ChunkedResponse": b.encodeChunkedResponse((ChunkedResponse) o); break;
      case "ChunkedResponseWide": b.encodeChunkedResponseWide((ChunkedResponseWide) o); break;
      case "LeafElement": b.encodeLeafElement((LeafElement) o); break;
      case "LeafResponse": b.encodeLeafResponse((LeafResponse) o); break;
      case "Surrogate": b.encodeSurrogate((Surrogate) o); break;
      case "SurrogateInner": b.encodeSurrogateInner((SurrogateInner) o); break;
      case "WireZoo": b.encodeWireZoo((WireZoo) o); break;
      default: throw new IllegalArgumentException(root);
    }
    return b.take();
  }

  /** Decision 11's retain mode on this binding; the no-unknown build refuses it. */
  public static void setRetain(Binding b, boolean on) {
    if (on) throw new UnsupportedOperationException("no-unknown build: no retain mode");
  }

  /** {buffers reclaimed after failed decodes, left after successful ones}. */
  public static long[] unkCounters(Binding b) {
    return new long[] {0L, 0L};
  }
}
