// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

/** invented for the corpus */
public final class Surrogate {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public String text = "";
  public SurrogateInner nested = null;
  public java.util.TreeMap<String, String> attrs = new java.util.TreeMap<String, String>();
  public java.util.List<String> texts = new java.util.ArrayList<String>();
  public byte[] raw = EMPTY_BYTES;
}
