# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS and Python version
build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_install:
      - curl -OfsSL https://dot.net/v1/dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh
    pre_build:
      # Install protobuf compiler manually
      - curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.0/protoc-21.0-linux-x86_64.zip
      - unzip protoc-21.0-linux-x86_64.zip -d $HOME/protoc
      
      # If the above fails, try downloading again from a correct source
      - curl -LO https://github.com/pseudomuto/protoc-gen-doc/releases/download/v1.5.1/protoc-gen-doc_1.5.1_linux_amd64.tar.gz
      - mkdir -p $HOME/protoc-gen-doc
      - tar -xvzf protoc-gen-doc_1.5.1_linux_amd64.tar.gz -C $HOME/protoc-gen-doc 
      - export PATH="$HOME/protoc/bin:$PATH" && export PATH="$HOME/protoc-gen-doc:$PATH" && protoc --version && protoc -I Protos/V1 --doc_out=.docs/content/api --doc_opt=markdown,tmp.md Protos/V1/*.proto  # Generate docs
      # Process the generated markdown with sed to apply custom formatting
      - sed -E '
          s/# Protocol Documentation/# V1/;
          /## Table of Contents/,/^[^#]*## /{
            /## agent_common.proto/!d
          };
          s/name="([^"]*)"/id="\1"/g
        ' .docs/content/api/tmp.md > .docs/content/api/v1.md ;
      # Set up .NET environment
      - DOTNET_ROOT="$HOME/.dotnet" PATH="$PATH":"$DOTNET_ROOT":"$DOTNET_ROOT/scripts" env
      - DOTNET_ROOT="$HOME/.dotnet" PATH="$PATH":"$DOTNET_ROOT":"$DOTNET_ROOT/scripts" scripts/generate-csharp-doc.sh

# Move anchors out of the titles
# Build documentation in the ".docs/" directory with Sphinx
sphinx:
  configuration: .docs/conf.py

# Optionally, but recommended,
# declare the Python requirements required to build your documentation
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
    - requirements: .docs/requirements.txt