[package]
name = "armonik-client-test"
version = "3.10.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
armonik = { path = "../armonik" }
futures = "0.3"
futures-core = "0.3"
futures-util = "0.3"
tokio = { version = "1.0", features = [
  "rt-multi-thread",
  "macros",
  "sync",
  "time",
] }
tokio-stream = { version = "0.1", features = ["sync", "net"] }
tokio-util = "0.7"
async-stream = "0.3"
async-trait = "0.1"
tower-http = { version = "0.6", features = ["trace"] }
