// @generated by ffi/poc/codec/gen/cs_types.py (driven by ffi/poc/csharp/gen/generate.py)
// from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json. Do not edit: `gen/generate.py --check` fails if this file is not
// what the generator writes today.
//
// Structural equality over the facade, for the decode half of the oracle.

using System;
using System.Collections.Generic;
using Armonik.Ffi.Facade;

namespace Armonik.Ffi.Corpus;

public static class Eq
{
    public static bool Bytes(byte[] a, byte[] b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return (a == null ? 0 : a.Length) == (b == null ? 0 : b.Length);
        if (a.Length != b.Length) return false;
        for (int i = 0; i < a.Length; i++) if (a[i] != b[i]) return false;
        return true;
    }

    public static bool Map(OrderedMap<string, string> a, OrderedMap<string, string> b)
    {
        if (a.Count != b.Count) return false;
        foreach (var kv in a) { if (!b.TryGetValue(kv.Key, out var v) || v != kv.Value) return false; }
        return true;
    }

    public static bool List<T>(List<T> a, List<T> b, Func<T, T, bool> same)
    {
        if (a.Count != b.Count) return false;
        for (int i = 0; i < a.Count; i++) if (!same(a[i], b[i])) return false;
        return true;
    }

    public static bool SameTimestamp(Timestamp a, Timestamp b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Seconds == b.Seconds)) return false;
        if (!(a.Nanos == b.Nanos)) return false;
        return true;
    }

    public static bool SameDuration(Duration a, Duration b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Seconds == b.Seconds)) return false;
        if (!(a.Nanos == b.Nanos)) return false;
        return true;
    }

    public static bool SameResultRaw(ResultRaw a, ResultRaw b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.SessionId == b.SessionId)) return false;
        if (!(a.Name == b.Name)) return false;
        if (!(a.OwnerTaskId == b.OwnerTaskId)) return false;
        if (!(a.Status == b.Status)) return false;
        if (!(SameTimestamp(a.CreatedAt, b.CreatedAt))) return false;
        if (!(SameTimestamp(a.CompletedAt, b.CompletedAt))) return false;
        if (!(a.ResultId == b.ResultId)) return false;
        if (!(a.Size == b.Size)) return false;
        if (!(a.CreatedBy == b.CreatedBy)) return false;
        if (!(Eq.Bytes(a.OpaqueId, b.OpaqueId))) return false;
        if (!(a.ManualDeletion == b.ManualDeletion)) return false;
        return true;
    }

    public static bool SameTaskOptions(TaskOptions a, TaskOptions b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.Map(a.Options, b.Options)) return false;
        if (!(SameDuration(a.MaxDuration, b.MaxDuration))) return false;
        if (!(a.MaxRetries == b.MaxRetries)) return false;
        if (!(a.Priority == b.Priority)) return false;
        if (!(a.PartitionId == b.PartitionId)) return false;
        if (!(a.ApplicationName == b.ApplicationName)) return false;
        if (!(a.ApplicationVersion == b.ApplicationVersion)) return false;
        if (!(a.ApplicationNamespace == b.ApplicationNamespace)) return false;
        if (!(a.ApplicationService == b.ApplicationService)) return false;
        if (!(a.EngineType == b.EngineType)) return false;
        return true;
    }

    public static bool SameTaskOutput(TaskOutput a, TaskOutput b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Success == b.Success)) return false;
        if (!(a.Error == b.Error)) return false;
        return true;
    }

    public static bool SameTaskDetailed(TaskDetailed a, TaskDetailed b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Id == b.Id)) return false;
        if (!(a.SessionId == b.SessionId)) return false;
        if (!(a.OwnerPodId == b.OwnerPodId)) return false;
        if (!Eq.List(a.ParentTaskIds, b.ParentTaskIds, (x, y) => x == y)) return false;
        if (!Eq.List(a.DataDependencies, b.DataDependencies, (x, y) => x == y)) return false;
        if (!Eq.List(a.ExpectedOutputIds, b.ExpectedOutputIds, (x, y) => x == y)) return false;
        if (!Eq.List(a.RetryOfIds, b.RetryOfIds, (x, y) => x == y)) return false;
        if (!(a.Status == b.Status)) return false;
        if (!(a.StatusMessage == b.StatusMessage)) return false;
        if (!(SameTaskOptions(a.Options, b.Options))) return false;
        if (!(SameTimestamp(a.CreatedAt, b.CreatedAt))) return false;
        if (!(SameTimestamp(a.SubmittedAt, b.SubmittedAt))) return false;
        if (!(SameTimestamp(a.StartedAt, b.StartedAt))) return false;
        if (!(SameTimestamp(a.EndedAt, b.EndedAt))) return false;
        if (!(SameTimestamp(a.PodTtl, b.PodTtl))) return false;
        if (!(SameTaskOutput(a.Output, b.Output))) return false;
        if (!(a.PodHostname == b.PodHostname)) return false;
        if (!(SameTimestamp(a.ReceivedAt, b.ReceivedAt))) return false;
        if (!(SameTimestamp(a.AcquiredAt, b.AcquiredAt))) return false;
        if (!(SameDuration(a.CreationToEndDuration, b.CreationToEndDuration))) return false;
        if (!(SameDuration(a.ProcessingToEndDuration, b.ProcessingToEndDuration))) return false;
        if (!(a.InitialTaskId == b.InitialTaskId)) return false;
        if (!(SameDuration(a.ReceivedToEndDuration, b.ReceivedToEndDuration))) return false;
        if (!(SameTimestamp(a.ProcessedAt, b.ProcessedAt))) return false;
        if (!(SameTimestamp(a.FetchedAt, b.FetchedAt))) return false;
        if (!(a.PayloadId == b.PayloadId)) return false;
        if (!(a.CreatedBy == b.CreatedBy)) return false;
        return true;
    }

    public static bool SameTaskSummary(TaskSummary a, TaskSummary b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Id == b.Id)) return false;
        if (!(a.SessionId == b.SessionId)) return false;
        if (!(SameTaskOptions(a.Options, b.Options))) return false;
        if (!(a.Status == b.Status)) return false;
        if (!(SameTimestamp(a.CreatedAt, b.CreatedAt))) return false;
        if (!(a.Error == b.Error)) return false;
        if (!(a.StatusMessage == b.StatusMessage)) return false;
        if (!(a.CountDataDependencies == b.CountDataDependencies)) return false;
        return true;
    }

    public static bool SameProbe(Probe a, Probe b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Id == b.Id)) return false;
        if (!(a.OptCount == b.OptCount)) return false;
        if (!(a.OptLabel == b.OptLabel)) return false;
        if (!(a.OptFlag == b.OptFlag)) return false;
        if (a.BodyCase != b.BodyCase) return false;
        switch (a.BodyCase)
        {
            case ProbeBodyCase.AsInt: if (!(a.AsInt == b.AsInt)) return false; break;
            case ProbeBodyCase.AsText: if (!(a.AsText == b.AsText)) return false; break;
            case ProbeBodyCase.AsBlob: if (!(Eq.Bytes(a.AsBlob, b.AsBlob))) return false; break;
            case ProbeBodyCase.AsStamp: if (!(SameTimestamp(a.AsStamp, b.AsStamp))) return false; break;
            case ProbeBodyCase.AsNothing: if (!(SameEmpty(a.AsNothing, b.AsNothing))) return false; break;
            default: break;
        }
        return true;
    }

    public static bool SameEmpty(Empty a, Empty b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        return true;
    }

    public static bool SameUploadResultData(UploadResultData a, UploadResultData b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.SessionId == b.SessionId)) return false;
        if (!(a.ResultId == b.ResultId)) return false;
        if (!(Eq.Bytes(a.DataChunk, b.DataChunk))) return false;
        return true;
    }

    public static bool SameMetricsBatch(MetricsBatch a, MetricsBatch b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Id == b.Id)) return false;
        if (!Eq.List(a.Ticks, b.Ticks, (x, y) => x == y)) return false;
        if (!Eq.List(a.Values, b.Values, (x, y) => BitConverter.DoubleToInt64Bits(x) == BitConverter.DoubleToInt64Bits(y))) return false;
        if (!Eq.List(a.Codes, b.Codes, (x, y) => x == y)) return false;
        if (!Eq.List(a.Flags, b.Flags, (x, y) => x == y)) return false;
        if (!Eq.List(a.Statuses, b.Statuses, (x, y) => x == y)) return false;
        return true;
    }

    public static bool SamePair(Pair a, Pair b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Key == b.Key)) return false;
        if (!(a.Value == b.Value)) return false;
        return true;
    }

    public static bool SameListResultsResponse(ListResultsResponse a, ListResultsResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Results, b.Results, (x, y) => SameResultRaw(x, y))) return false;
        if (!(a.Page == b.Page)) return false;
        if (!(a.Total == b.Total)) return false;
        return true;
    }

    public static bool SameListTasksDetailedResponse(ListTasksDetailedResponse a, ListTasksDetailedResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Tasks, b.Tasks, (x, y) => SameTaskDetailed(x, y))) return false;
        if (!(a.Page == b.Page)) return false;
        if (!(a.Total == b.Total)) return false;
        return true;
    }

    public static bool SameListTaskSummaryResponse(ListTaskSummaryResponse a, ListTaskSummaryResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Tasks, b.Tasks, (x, y) => SameTaskSummary(x, y))) return false;
        return true;
    }

    public static bool SameListProbeResponse(ListProbeResponse a, ListProbeResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Probes, b.Probes, (x, y) => SameProbe(x, y))) return false;
        return true;
    }

    public static bool SameListMetricsResponse(ListMetricsResponse a, ListMetricsResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Batches, b.Batches, (x, y) => SameMetricsBatch(x, y))) return false;
        return true;
    }

    public static bool SameUploadResultDataMessage(UploadResultDataMessage a, UploadResultDataMessage b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(SameUploadResultData(a.Upload, b.Upload))) return false;
        return true;
    }

    public static bool SameDualResponse(DualResponse a, DualResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Left, b.Left, (x, y) => SamePair(x, y))) return false;
        if (!Eq.List(a.Right, b.Right, (x, y) => SamePair(x, y))) return false;
        return true;
    }

    public static bool SameChunkLeaf(ChunkLeaf a, ChunkLeaf b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.K == b.K)) return false;
        if (!(a.V == b.V)) return false;
        return true;
    }

    public static bool SameChunkInner(ChunkInner a, ChunkInner b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Marks, b.Marks, (x, y) => x == y)) return false;
        if (!Eq.List(a.Leaves, b.Leaves, (x, y) => SameChunkLeaf(x, y))) return false;
        return true;
    }

    public static bool SameChunkElement(ChunkElement a, ChunkElement b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Labels, b.Labels, (x, y) => x == y)) return false;
        if (!Eq.Map(a.Attrs, b.Attrs)) return false;
        if (!(a.Id == b.Id)) return false;
        if (!(SameChunkInner(a.Inner, b.Inner))) return false;
        return true;
    }

    public static bool SameChunkedResponse(ChunkedResponse a, ChunkedResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Items, b.Items, (x, y) => SameChunkElement(x, y))) return false;
        if (!(a.Page == b.Page)) return false;
        return true;
    }

    public static bool SameChunkedResponseWide(ChunkedResponseWide a, ChunkedResponseWide b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Items, b.Items, (x, y) => SameChunkElement(x, y))) return false;
        return true;
    }

    public static bool SameLeafElement(LeafElement a, LeafElement b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Id == b.Id)) return false;
        if (!(a.N == b.N)) return false;
        if (!(SameTimestamp(a.Stamp, b.Stamp))) return false;
        return true;
    }

    public static bool SameLeafResponse(LeafResponse a, LeafResponse b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!Eq.List(a.Items, b.Items, (x, y) => SameLeafElement(x, y))) return false;
        return true;
    }

    public static bool SameSurrogate(Surrogate a, Surrogate b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Text == b.Text)) return false;
        if (!(SameSurrogateInner(a.Nested, b.Nested))) return false;
        if (!Eq.Map(a.Attrs, b.Attrs)) return false;
        if (!Eq.List(a.Texts, b.Texts, (x, y) => x == y)) return false;
        if (!(Eq.Bytes(a.Raw, b.Raw))) return false;
        return true;
    }

    public static bool SameSurrogateInner(SurrogateInner a, SurrogateInner b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.Text == b.Text)) return false;
        return true;
    }

    public static bool SameNest(Nest a, Nest b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(SameNest(a.Child, b.Child))) return false;
        if (!(a.Leaf == b.Leaf)) return false;
        return true;
    }

    public static bool SameWireZoo(WireZoo a, WireZoo b)
    {
        if (ReferenceEquals(a, b)) return true;
        if (a == null || b == null) return false;
        if (!(a.VInt32 == b.VInt32)) return false;
        if (!(a.VInt64 == b.VInt64)) return false;
        if (!(a.VBool == b.VBool)) return false;
        if (!(BitConverter.DoubleToInt64Bits(a.VDouble) == BitConverter.DoubleToInt64Bits(b.VDouble))) return false;
        if (!(a.VFixed32 == b.VFixed32)) return false;
        if (!(a.VString == b.VString)) return false;
        if (!(Eq.Bytes(a.VBytes, b.VBytes))) return false;
        if (!(a.VEnum == b.VEnum)) return false;
        if (!(SameTimestamp(a.VMsg, b.VMsg))) return false;
        if (!(a.VBigTag == b.VBigTag)) return false;
        return true;
    }
}
