// The JSON spellings `ffi/corpus/CONTRACT.md` section 3 fixes, and nothing else.
//
// No shape knowledge lives here: which fields appear, and in which form, is generated by
// `gen/cpp_project.py` over the same IR every other backend reads (R1). This file is the
// three primitives that generated code calls -- escape a string, hex a byte string, print
// a double the way the contract says -- so a value rule cannot be written twice.
#ifndef AK_PROJJSON_H
#define AK_PROJJSON_H

#include <cstdio>
#include <string>

namespace ak {
namespace proj {

inline void str(const std::string &s, std::string *out) {
  out->push_back('"');
  for (std::size_t i = 0; i < s.size(); ++i) {
    unsigned char c = (unsigned char)s[i];
    switch (c) {
      case '"': out->append("\\\""); break;
      case '\\': out->append("\\\\"); break;
      case '\b': out->append("\\b"); break;
      case '\f': out->append("\\f"); break;
      case '\n': out->append("\\n"); break;
      case '\r': out->append("\\r"); break;
      case '\t': out->append("\\t"); break;
      default:
        if (c < 0x20) {
          char b[8];
          std::snprintf(b, sizeof(b), "\\u%04x", c);
          out->append(b);
        } else {
          // Everything else goes through as raw UTF-8 bytes. Every string that reaches
          // here has already been validated by the decode policy, so this cannot emit
          // invalid JSON, and the driver parses with a UTF-8 reader.
          out->push_back((char)c);
        }
    }
  }
  out->push_back('"');
}

// CONTRACT.md section 3: a `bytes` value is a LOWERCASE hex string.
inline void hex(const std::string &s, std::string *out) {
  static const char *d = "0123456789abcdef";
  out->push_back('"');
  for (std::size_t i = 0; i < s.size(); ++i) {
    unsigned char c = (unsigned char)s[i];
    out->push_back(d[c >> 4]);
    out->push_back(d[c & 15]);
  }
  out->push_back('"');
}

// Every integer and every ENUM is a decimal STRING. An enum value the descriptor does not
// declare has no name to use, and "999" is the point of several vectors.
inline void i64(long long v, std::string *out) {
  char b[32];
  std::snprintf(b, sizeof(b), "%lld", v);
  out->push_back('"');
  out->append(b);
  out->push_back('"');
}

// A double is a string, %.17g.
inline void f64(double v, std::string *out) {
  char b[64];
  std::snprintf(b, sizeof(b), "%.17g", v);
  out->push_back('"');
  out->append(b);
  out->push_back('"');
}

inline void boolean(bool v, std::string *out) { out->append(v ? "true" : "false"); }

// A comma before every entry but the first, tracked by the caller.
inline void sep(bool *first, std::string *out) {
  if (*first) { *first = false; } else { out->push_back(','); }
}

inline void key(const char *name, bool *first, std::string *out) {
  sep(first, out);
  str(std::string(name), out);
  out->push_back(':');
}

}  // namespace proj
}  // namespace ak
#endif  // AK_PROJJSON_H
