// @generated by ffi/poc/codec/gen/cs_types.py (driven by ffi/poc/csharp/gen/generate.py)
// from ffi/schema/shapes.json. Do not edit: `gen/generate.py --check` fails if this file is not
// what the generator writes today.
//
// The facade types of this message set.

using System;
using System.Collections.Generic;

namespace Armonik.Ffi.Facade;

/// 127 is real and it is why this enum is here: a two-byte varint, and a value a host
/// built against a shorter enum must round-trip losslessly.
/// Open enum: a wire value this build was not generated against is representable as
/// `(ResultStatus)v` and round-trips. A C# enum is open by construction.
public enum ResultStatus
{
    Unspecified = 0,
    Created = 1,
    Completed = 2,
    Aborted = 3,
    Deleted = 4,
    Notfound = 127,
}

/// Open enum: a wire value this build was not generated against is representable as
/// `(TaskStatus)v` and round-trips. A C# enum is open by construction.
public enum TaskStatus
{
    Unspecified = 0,
    Creating = 1,
    Submitted = 2,
    Dispatched = 3,
    Completed = 4,
    Error = 5,
    Timeout = 6,
    Cancelling = 7,
    Cancelled = 8,
    Processing = 9,
    Processed = 10,
    Retried = 11,
    Pending = 12,
    Paused = 13,
}

/// google.protobuf.Timestamp, copied rather than imported
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class Timestamp
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public long Seconds;
    public int Nanos;
}

/// google.protobuf.Duration, copied rather than imported
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class Duration
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public long Seconds;
    public int Nanos;
}

/// Protos/V1/results_common.proto, tags preserved including the gap at 7
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class ResultRaw
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string SessionId = "";
    public string Name = "";
    public string OwnerTaskId = "";
    public ResultStatus Status;
    public Timestamp CreatedAt;
    public Timestamp CompletedAt;
    public string ResultId = "";
    public long Size;
    public string CreatedBy = "";
    public byte[] OpaqueId = EmptyBytes;
    public bool ManualDeletion;
}

/// Protos/V1/objects.proto
/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class TaskOptions
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public OrderedMap<string, string> Options = new OrderedMap<string, string>();
    public Duration MaxDuration;
    public int MaxRetries;
    public int Priority;
    public string PartitionId = "";
    public string ApplicationName = "";
    public string ApplicationVersion = "";
    public string ApplicationNamespace = "";
    public string ApplicationService = "";
    public string EngineType = "";
}

/// Protos/V1/tasks_common.proto, TaskDetailed.Output, hoisted out of its parent
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class TaskOutput
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public bool Success;
    public string Error = "";
}

/// Protos/V1/tasks_common.proto, tags preserved
/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class TaskDetailed
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public string SessionId = "";
    public string OwnerPodId = "";
    public List<string> ParentTaskIds = new List<string>();
    public List<string> DataDependencies = new List<string>();
    public List<string> ExpectedOutputIds = new List<string>();
    public List<string> RetryOfIds = new List<string>();
    public TaskStatus Status;
    public string StatusMessage = "";
    public TaskOptions Options;
    public Timestamp CreatedAt;
    public Timestamp SubmittedAt;
    public Timestamp StartedAt;
    public Timestamp EndedAt;
    public Timestamp PodTtl;
    public TaskOutput Output;
    public string PodHostname = "";
    public Timestamp ReceivedAt;
    public Timestamp AcquiredAt;
    public Duration CreationToEndDuration;
    public Duration ProcessingToEndDuration;
    public string InitialTaskId = "";
    public Duration ReceivedToEndDuration;
    public Timestamp ProcessedAt;
    public Timestamp FetchedAt;
    public string PayloadId = "";
    public string CreatedBy = "";
}

/// Protos/V1/tasks_common.proto, reduced to the fields the adapter site needs
/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class TaskSummary
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public string SessionId = "";
    public TaskOptions Options;
    public TaskStatus Status;
    public Timestamp CreatedAt;
    public string Error = "";
    public string StatusMessage = "";
    public long CountDataDependencies;
}

/// Which member of `Probe.body` is set, by TAG (the ABI's `body_case` carries the same
/// number). `None` is no member.
public enum ProbeBodyCase
{
    None = 0,
    AsInt = 10,
    AsText = 11,
    AsBlob = 12,
    AsStamp = 13,
    AsNothing = 14,
}

/// invented; both shapes are real, the schema has 19 oneofs in 413 fields
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class Probe
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public int? OptCount;
    public string OptLabel;
    public bool? OptFlag;

    public ProbeBodyCase BodyCase;
    public long AsInt;
    public string AsText;
    public byte[] AsBlob;
    public Timestamp AsStamp;
    public Empty AsNothing;
}

/// Protos/V1/objects.proto
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class Empty
{
    internal static readonly byte[] EmptyBytes = new byte[0];
}

/// adapted from UploadResultDataRequest: flattened out of its oneof stream so that one
/// message carries the bulk field
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class UploadResultData
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string SessionId = "";
    public string ResultId = "";
    public byte[] DataChunk = EmptyBytes;
}

/// invented. The four scalar packed fields are a CONTROL: the real schema has 3 packed
/// repeated fields and all of them are enums. `statuses` is the real shape, relocated:
/// every packed field in Protos/V1 sits on a filter or request message
/// (submitter_common.proto `repeated task_status.TaskStatus statuses`,
/// results_common.proto `repeated result_status.ResultStatus fetch_statuses`), and this
/// payload set carries responses only. So M6's scalar rows are a control and its enum
/// row is not.
/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class MetricsBatch
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public List<long> Ticks = new List<long>();
    public List<double> Values = new List<double>();
    public List<int> Codes = new List<int>();
    public List<bool> Flags = new List<bool>();
    public List<TaskStatus> Statuses = new List<TaskStatus>();
}

/// invented, the element of M7
/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class Pair
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Key = "";
    public int Value;
}

/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class ListResultsResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<ResultRaw> Results = new List<ResultRaw>();
    public int Page;
    public int Total;
}

/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class ListTasksDetailedResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<TaskDetailed> Tasks = new List<TaskDetailed>();
    public int Page;
    public int Total;
}

/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class ListTaskSummaryResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<TaskSummary> Tasks = new List<TaskSummary>();
}

/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class ListProbeResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<Probe> Probes = new List<Probe>();
}

/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class ListMetricsResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<MetricsBatch> Batches = new List<MetricsBatch>();
}

/// Batching predicate (ABI v1 6/7.2): a LEAF.
public sealed class UploadResultDataMessage
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public UploadResultData Upload;
}

/// invented. CONTROL: legal wire that no group buffer keyed by type can decode
/// Batching predicate (ABI v1 6/7.2): NOT a leaf.
public sealed class DualResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<Pair> Left = new List<Pair>();
    public List<Pair> Right = new List<Pair>();
}
