/* @generated by ffi/poc/codec/gen/c_abi.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit. */


/* The C ABI of ffi/design/ABI-v1.md, version 1. Fixed part (sections 3, 4, 5, 7.1,
 * 9, 10) from plan.FIXED; per-message part (section 6's groups and vtables, section
 * 7's fixes) from the plan's layout. C99/C++11 clean. */
#ifndef AK_ABI_H
#define AK_ABI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- section 5: errors (plan.FIXED.codes) ------------------------------------- */
#define AK_OK                    0      /* success */
#define AK_ALREADY_INITIALIZED   1      /* success: ak_init called again with the same options */
#define AK_ERR_HOST              (-1)   /* the host reported through ak_fail */
#define AK_ERR_MALFORMED         (-2)   /* invalid wire */
#define AK_ERR_TRUNCATED         (-3)   /* the input ended inside a value */
#define AK_ERR_DEPTH             (-4)   /* the decode recursion limit */
#define AK_ERR_LIMIT             (-5)   /* a size limit */
#define AK_ERR_TRANSCODE         (-6)   /* the transcoder refused its input */
#define AK_ERR_CAPACITY          (-7)   /* a transcoder wrote past the capacity given */
#define AK_ERR_INVALID_STATE     (-8)   /* e.g. two concurrent recv on one call */
#define AK_ERR_PANIC             (-9)   /* a caught Rust panic */
#define AK_ERR_UNINITIALIZED     (-10)  /* ak_init was not called */
#define AK_ERR_ABI               (-11)  /* version or group-layout mismatch */
#define AK_DETAIL_NONE           0u
#define AK_DETAIL_ABI_MISMATCH   1u
#define AK_DETAIL_OPTS_DIFFER    2u
#define AK_DETAIL_NULL_ARG       3u

#define AK_ABI_VERSION 1u

/* ---- section 3: lifecycle flags (plan.lifecycle.flag_values) ------------------- */
#define AK_INIT_OWN_LOGGING    1u
#define AK_INIT_NO_PANIC_HOOK  2u
#define AK_INIT_NO_CRYPTO      4u

/* ---- section 4: common vocabulary (plan.FIXED) --------------------------------- */
typedef struct ak_enc_ctx ak_enc_ctx;
typedef struct ak_dec_ctx ak_dec_ctx;
typedef struct ak_uspan ak_uspan;
/* ABI v1 section 4: the transcoder's growth callback; may move the buffer. */
typedef int32_t (*ak_grow_fn)(void *sink, int32_t want, uint8_t * *dst, int32_t *cap);
/* ABI v1 section 4: source code units -> UTF-8 into dst; returns bytes written or an error. */
typedef int32_t (*ak_transcode_fn)(const void *src, size_t len, uint8_t *dst, int32_t cap, ak_grow_fn grow, void *sink);
/* ABI v1 section 3: the host's log sink. */
typedef void (*ak_log_fn)(void *ctx, uint32_t level, const uint8_t *msg, size_t msg_len);
/* ABI v1 section 6: a host-driven loop over one repeated/packed/map field. */
typedef int32_t (*ak_loop_f)(ak_enc_ctx *ctx, const void *obj, int64_t token);
/* Decision 11 candidate: captured unknown-field runs, delivered by token. */
typedef void (*ak_unk_f)(ak_dec_ctx *ctx, void *obj, const struct ak_uspan *spans, int32_t n);
/* ABI v1 section 4, encode: a blob as DATA in the group. `len` counts SOURCE code units; `tc == NULL` means the field is ABSENT. */
struct ak_str {
  const void *data;
  size_t len;
  ak_transcode_fn tc;
};
typedef struct ak_str ak_str;
/* ABI v1 section 4, decode: an OFFSET into the buffer the host handed in. */
struct ak_span {
  uint32_t off;
  uint32_t len;
  uint32_t coder;
};
typedef struct ak_span ak_span;
/* Decision 11's unknown-field bag: two words, raw tag-and-value runs. */
struct ak_blob {
  const void *data;
  size_t len;
};
typedef struct ak_blob ak_blob;
/* One captured unknown run: which object (a token) and where in the input. */
struct ak_uspan {
  int64_t token;
  uint32_t off;
  uint32_t len;
};
typedef struct ak_uspan ak_uspan;
/* ak_init's out-parameter (ABI v1 section 3/5): a code and a detail. */
struct ak_err {
  int32_t code;
  uint32_t detail;
};
typedef struct ak_err ak_err;
/* ak_init's options (ABI v1 section 3). */
struct ak_init_opts {
  uint32_t abi_version;
  uint32_t flags;
  ak_log_fn log;
  void *log_ctx;
};
typedef struct ak_init_opts ak_init_opts;
/* README R5: boundary-call counts, counted in the CORE (zero unless the core is a counting build). */
struct AkCounters {
  uint64_t forward;
  uint64_t reverse;
  uint64_t transcode;
  uint64_t prefix_moves;
  uint64_t prefix_bytes;
  uint64_t grows;
};
typedef struct AkCounters AkCounters;
/* ABI v1 section 7.1: one pull record header, 24 bytes; the payload follows, padded to 8. */
struct ak_bdr_rec {
  uint32_t op;
  uint32_t slot;
  int64_t token;
  uint32_t n;
  uint32_t bytes;
};
typedef struct ak_bdr_rec ak_bdr_rec;
#define AK_STR_DIRECT ((const void *)(uintptr_t)1)  /* ABI v1 section 8: ak_str.data meaning 'a direct argument of the call'. */
#define AK_TOKEN_ROOT ((int64_t)-1)  /* a token naming the root object itself */
#define AK_BDR_APPLY 1u  /* pull record: the root group (last record) */
#define AK_BDR_ADD 2u  /* pull record: a batched run */
#define AK_BDR_NEW 3u  /* pull record: a non-leaf element begins (minted token) */
#define AK_BDR_APPLY_ELEM 4u  /* pull record: a non-leaf element's group */
#define AK_BDR_MIN_CHUNK 32792u  /* the smallest drain chunk that holds any record */

/* ---- section 3: the lifecycle (plan.lifecycle, R-G7) ----------------------------
 * Every binding rendered from this plan calls `ak_init` before its first codec or RPC
 * call and treats AK_OK and AK_ALREADY_INITIALIZED as success. A core built with `init-guard`
 * refuses every entry point with AK_ERR_UNINITIALIZED until it has. The prototype
 * is among the fixed entry points below. */

/* Encode group for `TaskOptionsOptionsEntry`. */
struct ak_efix_TaskOptionsOptionsEntry {
  struct ak_str key;
  struct ak_str value;
  uint32_t presence;
};

/* Decode group for `TaskOptionsOptionsEntry`. */
struct ak_dfix_TaskOptionsOptionsEntry {
  struct ak_span key;
  struct ak_span value;
  uint32_t presence;
};

/* Encode group for `TaskOptionsOptionsEntry`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskOptionsOptionsEntry {
  struct ak_str key;
  struct ak_str value;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ChunkElementAttrsEntry`. */
struct ak_efix_ChunkElementAttrsEntry {
  struct ak_str key;
  struct ak_str value;
  uint32_t presence;
};

/* Decode group for `ChunkElementAttrsEntry`. */
struct ak_dfix_ChunkElementAttrsEntry {
  struct ak_span key;
  struct ak_span value;
  uint32_t presence;
};

/* Encode group for `ChunkElementAttrsEntry`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ChunkElementAttrsEntry {
  struct ak_str key;
  struct ak_str value;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `SurrogateAttrsEntry`. */
struct ak_efix_SurrogateAttrsEntry {
  struct ak_str key;
  struct ak_str value;
  uint32_t presence;
};

/* Decode group for `SurrogateAttrsEntry`. */
struct ak_dfix_SurrogateAttrsEntry {
  struct ak_span key;
  struct ak_span value;
  uint32_t presence;
};

/* Encode group for `SurrogateAttrsEntry`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_SurrogateAttrsEntry {
  struct ak_str key;
  struct ak_str value;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Timestamp`. */
struct ak_efix_Timestamp {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Decode group for `Timestamp`. */
struct ak_dfix_Timestamp {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Encode group for `Timestamp`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Timestamp {
  int64_t seconds;
  int32_t nanos;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Duration`. */
struct ak_efix_Duration {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Decode group for `Duration`. */
struct ak_dfix_Duration {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Encode group for `Duration`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Duration {
  int64_t seconds;
  int32_t nanos;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ResultRaw`. */
struct ak_efix_ResultRaw {
  struct ak_str session_id;
  struct ak_str name;
  struct ak_str owner_task_id;
  int32_t status;
  struct ak_efix_Timestamp created_at;
  struct ak_efix_Timestamp completed_at;
  struct ak_str result_id;
  int64_t size;
  struct ak_str created_by;
  struct ak_str opaque_id;
  uint8_t manual_deletion;
  uint32_t presence;
};
#define AK_EFIX_RESULTRAW_PRESENT_CREATED_AT (1u << 0)
#define AK_EFIX_RESULTRAW_PRESENT_COMPLETED_AT (1u << 1)

/* Decode group for `ResultRaw`. */
struct ak_dfix_ResultRaw {
  struct ak_span session_id;
  struct ak_span name;
  struct ak_span owner_task_id;
  int32_t status;
  struct ak_dfix_Timestamp created_at;
  struct ak_dfix_Timestamp completed_at;
  struct ak_span result_id;
  int64_t size;
  struct ak_span created_by;
  struct ak_span opaque_id;
  uint8_t manual_deletion;
  uint32_t presence;
};
#define AK_DFIX_RESULTRAW_PRESENT_CREATED_AT (1u << 0)
#define AK_DFIX_RESULTRAW_PRESENT_COMPLETED_AT (1u << 1)

/* Encode group for `ResultRaw`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ResultRaw {
  struct ak_str session_id;
  struct ak_str name;
  struct ak_str owner_task_id;
  int32_t status;
  struct ak_ufix_Timestamp created_at;
  struct ak_ufix_Timestamp completed_at;
  struct ak_str result_id;
  int64_t size;
  struct ak_str created_by;
  struct ak_str opaque_id;
  uint8_t manual_deletion;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_RESULTRAW_PRESENT_CREATED_AT (1u << 0)
#define AK_UFIX_RESULTRAW_PRESENT_COMPLETED_AT (1u << 1)

/* Encode group for `TaskOptions`. */
struct ak_efix_TaskOptions {
  struct ak_efix_Duration max_duration;
  int32_t max_retries;
  int32_t priority;
  struct ak_str partition_id;
  struct ak_str application_name;
  struct ak_str application_version;
  struct ak_str application_namespace;
  struct ak_str application_service;
  struct ak_str engine_type;
  uint32_t presence;
};
#define AK_EFIX_TASKOPTIONS_PRESENT_MAX_DURATION (1u << 0)

/* Decode group for `TaskOptions`. */
struct ak_dfix_TaskOptions {
  struct ak_dfix_Duration max_duration;
  int32_t max_retries;
  int32_t priority;
  struct ak_span partition_id;
  struct ak_span application_name;
  struct ak_span application_version;
  struct ak_span application_namespace;
  struct ak_span application_service;
  struct ak_span engine_type;
  uint32_t presence;
};
#define AK_DFIX_TASKOPTIONS_PRESENT_MAX_DURATION (1u << 0)

/* Encode group for `TaskOptions`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskOptions {
  struct ak_ufix_Duration max_duration;
  int32_t max_retries;
  int32_t priority;
  struct ak_str partition_id;
  struct ak_str application_name;
  struct ak_str application_version;
  struct ak_str application_namespace;
  struct ak_str application_service;
  struct ak_str engine_type;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_TASKOPTIONS_PRESENT_MAX_DURATION (1u << 0)

/* Encode group for `TaskOutput`. */
struct ak_efix_TaskOutput {
  uint8_t success;
  struct ak_str error;
  uint32_t presence;
};

/* Decode group for `TaskOutput`. */
struct ak_dfix_TaskOutput {
  uint8_t success;
  struct ak_span error;
  uint32_t presence;
};

/* Encode group for `TaskOutput`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskOutput {
  uint8_t success;
  struct ak_str error;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `TaskDetailed`. */
struct ak_efix_TaskDetailed {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_str owner_pod_id;
  int32_t status;
  struct ak_str status_message;
  struct ak_efix_TaskOptions options;
  struct ak_efix_Timestamp created_at;
  struct ak_efix_Timestamp submitted_at;
  struct ak_efix_Timestamp started_at;
  struct ak_efix_Timestamp ended_at;
  struct ak_efix_Timestamp pod_ttl;
  struct ak_efix_TaskOutput output;
  struct ak_str pod_hostname;
  struct ak_efix_Timestamp received_at;
  struct ak_efix_Timestamp acquired_at;
  struct ak_efix_Duration creation_to_end_duration;
  struct ak_efix_Duration processing_to_end_duration;
  struct ak_str initial_task_id;
  struct ak_efix_Duration received_to_end_duration;
  struct ak_efix_Timestamp processed_at;
  struct ak_efix_Timestamp fetched_at;
  struct ak_str payload_id;
  struct ak_str created_by;
  uint32_t presence;
};
#define AK_EFIX_TASKDETAILED_PRESENT_OPTIONS (1u << 0)
#define AK_EFIX_TASKDETAILED_PRESENT_CREATED_AT (1u << 1)
#define AK_EFIX_TASKDETAILED_PRESENT_SUBMITTED_AT (1u << 2)
#define AK_EFIX_TASKDETAILED_PRESENT_STARTED_AT (1u << 3)
#define AK_EFIX_TASKDETAILED_PRESENT_ENDED_AT (1u << 4)
#define AK_EFIX_TASKDETAILED_PRESENT_POD_TTL (1u << 5)
#define AK_EFIX_TASKDETAILED_PRESENT_OUTPUT (1u << 6)
#define AK_EFIX_TASKDETAILED_PRESENT_RECEIVED_AT (1u << 7)
#define AK_EFIX_TASKDETAILED_PRESENT_ACQUIRED_AT (1u << 8)
#define AK_EFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION (1u << 9)
#define AK_EFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION (1u << 10)
#define AK_EFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION (1u << 11)
#define AK_EFIX_TASKDETAILED_PRESENT_PROCESSED_AT (1u << 12)
#define AK_EFIX_TASKDETAILED_PRESENT_FETCHED_AT (1u << 13)

/* Decode group for `TaskDetailed`. */
struct ak_dfix_TaskDetailed {
  struct ak_span id;
  struct ak_span session_id;
  struct ak_span owner_pod_id;
  int32_t status;
  struct ak_span status_message;
  struct ak_dfix_TaskOptions options;
  struct ak_dfix_Timestamp created_at;
  struct ak_dfix_Timestamp submitted_at;
  struct ak_dfix_Timestamp started_at;
  struct ak_dfix_Timestamp ended_at;
  struct ak_dfix_Timestamp pod_ttl;
  struct ak_dfix_TaskOutput output;
  struct ak_span pod_hostname;
  struct ak_dfix_Timestamp received_at;
  struct ak_dfix_Timestamp acquired_at;
  struct ak_dfix_Duration creation_to_end_duration;
  struct ak_dfix_Duration processing_to_end_duration;
  struct ak_span initial_task_id;
  struct ak_dfix_Duration received_to_end_duration;
  struct ak_dfix_Timestamp processed_at;
  struct ak_dfix_Timestamp fetched_at;
  struct ak_span payload_id;
  struct ak_span created_by;
  uint32_t presence;
};
#define AK_DFIX_TASKDETAILED_PRESENT_OPTIONS (1u << 0)
#define AK_DFIX_TASKDETAILED_PRESENT_CREATED_AT (1u << 1)
#define AK_DFIX_TASKDETAILED_PRESENT_SUBMITTED_AT (1u << 2)
#define AK_DFIX_TASKDETAILED_PRESENT_STARTED_AT (1u << 3)
#define AK_DFIX_TASKDETAILED_PRESENT_ENDED_AT (1u << 4)
#define AK_DFIX_TASKDETAILED_PRESENT_POD_TTL (1u << 5)
#define AK_DFIX_TASKDETAILED_PRESENT_OUTPUT (1u << 6)
#define AK_DFIX_TASKDETAILED_PRESENT_RECEIVED_AT (1u << 7)
#define AK_DFIX_TASKDETAILED_PRESENT_ACQUIRED_AT (1u << 8)
#define AK_DFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION (1u << 9)
#define AK_DFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION (1u << 10)
#define AK_DFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION (1u << 11)
#define AK_DFIX_TASKDETAILED_PRESENT_PROCESSED_AT (1u << 12)
#define AK_DFIX_TASKDETAILED_PRESENT_FETCHED_AT (1u << 13)

/* Encode group for `TaskDetailed`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskDetailed {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_str owner_pod_id;
  int32_t status;
  struct ak_str status_message;
  struct ak_ufix_TaskOptions options;
  struct ak_ufix_Timestamp created_at;
  struct ak_ufix_Timestamp submitted_at;
  struct ak_ufix_Timestamp started_at;
  struct ak_ufix_Timestamp ended_at;
  struct ak_ufix_Timestamp pod_ttl;
  struct ak_ufix_TaskOutput output;
  struct ak_str pod_hostname;
  struct ak_ufix_Timestamp received_at;
  struct ak_ufix_Timestamp acquired_at;
  struct ak_ufix_Duration creation_to_end_duration;
  struct ak_ufix_Duration processing_to_end_duration;
  struct ak_str initial_task_id;
  struct ak_ufix_Duration received_to_end_duration;
  struct ak_ufix_Timestamp processed_at;
  struct ak_ufix_Timestamp fetched_at;
  struct ak_str payload_id;
  struct ak_str created_by;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_TASKDETAILED_PRESENT_OPTIONS (1u << 0)
#define AK_UFIX_TASKDETAILED_PRESENT_CREATED_AT (1u << 1)
#define AK_UFIX_TASKDETAILED_PRESENT_SUBMITTED_AT (1u << 2)
#define AK_UFIX_TASKDETAILED_PRESENT_STARTED_AT (1u << 3)
#define AK_UFIX_TASKDETAILED_PRESENT_ENDED_AT (1u << 4)
#define AK_UFIX_TASKDETAILED_PRESENT_POD_TTL (1u << 5)
#define AK_UFIX_TASKDETAILED_PRESENT_OUTPUT (1u << 6)
#define AK_UFIX_TASKDETAILED_PRESENT_RECEIVED_AT (1u << 7)
#define AK_UFIX_TASKDETAILED_PRESENT_ACQUIRED_AT (1u << 8)
#define AK_UFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION (1u << 9)
#define AK_UFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION (1u << 10)
#define AK_UFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION (1u << 11)
#define AK_UFIX_TASKDETAILED_PRESENT_PROCESSED_AT (1u << 12)
#define AK_UFIX_TASKDETAILED_PRESENT_FETCHED_AT (1u << 13)

/* Encode group for `TaskSummary`. */
struct ak_efix_TaskSummary {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_efix_TaskOptions options;
  int32_t status;
  struct ak_efix_Timestamp created_at;
  struct ak_str error;
  struct ak_str status_message;
  int64_t count_data_dependencies;
  uint32_t presence;
};
#define AK_EFIX_TASKSUMMARY_PRESENT_OPTIONS (1u << 0)
#define AK_EFIX_TASKSUMMARY_PRESENT_CREATED_AT (1u << 1)

/* Decode group for `TaskSummary`. */
struct ak_dfix_TaskSummary {
  struct ak_span id;
  struct ak_span session_id;
  struct ak_dfix_TaskOptions options;
  int32_t status;
  struct ak_dfix_Timestamp created_at;
  struct ak_span error;
  struct ak_span status_message;
  int64_t count_data_dependencies;
  uint32_t presence;
};
#define AK_DFIX_TASKSUMMARY_PRESENT_OPTIONS (1u << 0)
#define AK_DFIX_TASKSUMMARY_PRESENT_CREATED_AT (1u << 1)

/* Encode group for `TaskSummary`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskSummary {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_ufix_TaskOptions options;
  int32_t status;
  struct ak_ufix_Timestamp created_at;
  struct ak_str error;
  struct ak_str status_message;
  int64_t count_data_dependencies;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_TASKSUMMARY_PRESENT_OPTIONS (1u << 0)
#define AK_UFIX_TASKSUMMARY_PRESENT_CREATED_AT (1u << 1)

/* Encode group for `Empty`. */
struct ak_efix_Empty {
  uint32_t presence;
};

/* Decode group for `Empty`. */
struct ak_dfix_Empty {
  uint32_t presence;
};

/* Encode group for `Empty`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Empty {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Probe`. */
struct ak_efix_Probe {
  struct ak_str id;
  int32_t opt_count;
  struct ak_str opt_label;
  uint8_t opt_flag;
  uint32_t body_case;
  int64_t body_as_int;
  struct ak_str body_as_text;
  struct ak_str body_as_blob;
  struct ak_efix_Timestamp body_as_stamp;
  struct ak_efix_Empty body_as_nothing;
  uint32_t presence;
};
#define AK_EFIX_PROBE_PRESENT_OPT_COUNT (1u << 0)
#define AK_EFIX_PROBE_PRESENT_OPT_LABEL (1u << 1)
#define AK_EFIX_PROBE_PRESENT_OPT_FLAG (1u << 2)

/* Decode group for `Probe`. */
struct ak_dfix_Probe {
  struct ak_span id;
  int32_t opt_count;
  struct ak_span opt_label;
  uint8_t opt_flag;
  uint32_t body_case;
  int64_t body_as_int;
  struct ak_span body_as_text;
  struct ak_span body_as_blob;
  struct ak_dfix_Timestamp body_as_stamp;
  struct ak_dfix_Empty body_as_nothing;
  uint32_t presence;
};
#define AK_DFIX_PROBE_PRESENT_OPT_COUNT (1u << 0)
#define AK_DFIX_PROBE_PRESENT_OPT_LABEL (1u << 1)
#define AK_DFIX_PROBE_PRESENT_OPT_FLAG (1u << 2)

/* Encode group for `Probe`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Probe {
  struct ak_str id;
  int32_t opt_count;
  struct ak_str opt_label;
  uint8_t opt_flag;
  uint32_t body_case;
  int64_t body_as_int;
  struct ak_str body_as_text;
  struct ak_str body_as_blob;
  struct ak_ufix_Timestamp body_as_stamp;
  struct ak_ufix_Empty body_as_nothing;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_PROBE_PRESENT_OPT_COUNT (1u << 0)
#define AK_UFIX_PROBE_PRESENT_OPT_LABEL (1u << 1)
#define AK_UFIX_PROBE_PRESENT_OPT_FLAG (1u << 2)

/* Encode group for `UploadResultData`. */
struct ak_efix_UploadResultData {
  struct ak_str session_id;
  struct ak_str result_id;
  struct ak_str data_chunk;
  uint32_t presence;
};

/* Decode group for `UploadResultData`. */
struct ak_dfix_UploadResultData {
  struct ak_span session_id;
  struct ak_span result_id;
  struct ak_span data_chunk;
  uint32_t presence;
};

/* Encode group for `UploadResultData`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_UploadResultData {
  struct ak_str session_id;
  struct ak_str result_id;
  struct ak_str data_chunk;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `MetricsBatch`. */
struct ak_efix_MetricsBatch {
  struct ak_str id;
  uint32_t presence;
};

/* Decode group for `MetricsBatch`. */
struct ak_dfix_MetricsBatch {
  struct ak_span id;
  uint32_t presence;
};

/* Encode group for `MetricsBatch`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_MetricsBatch {
  struct ak_str id;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Pair`. */
struct ak_efix_Pair {
  struct ak_str key;
  int32_t value;
  uint32_t presence;
};

/* Decode group for `Pair`. */
struct ak_dfix_Pair {
  struct ak_span key;
  int32_t value;
  uint32_t presence;
};

/* Encode group for `Pair`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Pair {
  struct ak_str key;
  int32_t value;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListResultsResponse`. */
struct ak_efix_ListResultsResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Decode group for `ListResultsResponse`. */
struct ak_dfix_ListResultsResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Encode group for `ListResultsResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListResultsResponse {
  int32_t page;
  int32_t total;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListTasksDetailedResponse`. */
struct ak_efix_ListTasksDetailedResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Decode group for `ListTasksDetailedResponse`. */
struct ak_dfix_ListTasksDetailedResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Encode group for `ListTasksDetailedResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListTasksDetailedResponse {
  int32_t page;
  int32_t total;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListTaskSummaryResponse`. */
struct ak_efix_ListTaskSummaryResponse {
  uint32_t presence;
};

/* Decode group for `ListTaskSummaryResponse`. */
struct ak_dfix_ListTaskSummaryResponse {
  uint32_t presence;
};

/* Encode group for `ListTaskSummaryResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListTaskSummaryResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListProbeResponse`. */
struct ak_efix_ListProbeResponse {
  uint32_t presence;
};

/* Decode group for `ListProbeResponse`. */
struct ak_dfix_ListProbeResponse {
  uint32_t presence;
};

/* Encode group for `ListProbeResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListProbeResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListMetricsResponse`. */
struct ak_efix_ListMetricsResponse {
  uint32_t presence;
};

/* Decode group for `ListMetricsResponse`. */
struct ak_dfix_ListMetricsResponse {
  uint32_t presence;
};

/* Encode group for `ListMetricsResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListMetricsResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `UploadResultDataMessage`. */
struct ak_efix_UploadResultDataMessage {
  struct ak_efix_UploadResultData upload;
  uint32_t presence;
};
#define AK_EFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD (1u << 0)

/* Decode group for `UploadResultDataMessage`. */
struct ak_dfix_UploadResultDataMessage {
  struct ak_dfix_UploadResultData upload;
  uint32_t presence;
};
#define AK_DFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD (1u << 0)

/* Encode group for `UploadResultDataMessage`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_UploadResultDataMessage {
  struct ak_ufix_UploadResultData upload;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD (1u << 0)

/* Encode group for `DualResponse`. */
struct ak_efix_DualResponse {
  uint32_t presence;
};

/* Decode group for `DualResponse`. */
struct ak_dfix_DualResponse {
  uint32_t presence;
};

/* Encode group for `DualResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_DualResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ChunkLeaf`. */
struct ak_efix_ChunkLeaf {
  struct ak_str k;
  int32_t v;
  uint32_t presence;
};

/* Decode group for `ChunkLeaf`. */
struct ak_dfix_ChunkLeaf {
  struct ak_span k;
  int32_t v;
  uint32_t presence;
};

/* Encode group for `ChunkLeaf`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ChunkLeaf {
  struct ak_str k;
  int32_t v;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ChunkInner`. */
struct ak_efix_ChunkInner {
  uint32_t presence;
};

/* Decode group for `ChunkInner`. */
struct ak_dfix_ChunkInner {
  uint32_t presence;
};

/* Encode group for `ChunkInner`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ChunkInner {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ChunkElement`. */
struct ak_efix_ChunkElement {
  struct ak_str id;
  struct ak_efix_ChunkInner inner;
  uint32_t presence;
};
#define AK_EFIX_CHUNKELEMENT_PRESENT_INNER (1u << 0)

/* Decode group for `ChunkElement`. */
struct ak_dfix_ChunkElement {
  struct ak_span id;
  struct ak_dfix_ChunkInner inner;
  uint32_t presence;
};
#define AK_DFIX_CHUNKELEMENT_PRESENT_INNER (1u << 0)

/* Encode group for `ChunkElement`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ChunkElement {
  struct ak_str id;
  struct ak_ufix_ChunkInner inner;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_CHUNKELEMENT_PRESENT_INNER (1u << 0)

/* Encode group for `ChunkedResponse`. */
struct ak_efix_ChunkedResponse {
  int32_t page;
  uint32_t presence;
};

/* Decode group for `ChunkedResponse`. */
struct ak_dfix_ChunkedResponse {
  int32_t page;
  uint32_t presence;
};

/* Encode group for `ChunkedResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ChunkedResponse {
  int32_t page;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ChunkedResponseWide`. */
struct ak_efix_ChunkedResponseWide {
  uint32_t presence;
};

/* Decode group for `ChunkedResponseWide`. */
struct ak_dfix_ChunkedResponseWide {
  uint32_t presence;
};

/* Encode group for `ChunkedResponseWide`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ChunkedResponseWide {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `LeafElement`. */
struct ak_efix_LeafElement {
  struct ak_str id;
  int64_t n;
  struct ak_efix_Timestamp stamp;
  uint32_t presence;
};
#define AK_EFIX_LEAFELEMENT_PRESENT_STAMP (1u << 0)

/* Decode group for `LeafElement`. */
struct ak_dfix_LeafElement {
  struct ak_span id;
  int64_t n;
  struct ak_dfix_Timestamp stamp;
  uint32_t presence;
};
#define AK_DFIX_LEAFELEMENT_PRESENT_STAMP (1u << 0)

/* Encode group for `LeafElement`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_LeafElement {
  struct ak_str id;
  int64_t n;
  struct ak_ufix_Timestamp stamp;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_LEAFELEMENT_PRESENT_STAMP (1u << 0)

/* Encode group for `LeafResponse`. */
struct ak_efix_LeafResponse {
  uint32_t presence;
};

/* Decode group for `LeafResponse`. */
struct ak_dfix_LeafResponse {
  uint32_t presence;
};

/* Encode group for `LeafResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_LeafResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `SurrogateInner`. */
struct ak_efix_SurrogateInner {
  struct ak_str text;
  uint32_t presence;
};

/* Decode group for `SurrogateInner`. */
struct ak_dfix_SurrogateInner {
  struct ak_span text;
  uint32_t presence;
};

/* Encode group for `SurrogateInner`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_SurrogateInner {
  struct ak_str text;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Surrogate`. */
struct ak_efix_Surrogate {
  struct ak_str text;
  struct ak_efix_SurrogateInner nested;
  struct ak_str raw;
  uint32_t presence;
};
#define AK_EFIX_SURROGATE_PRESENT_NESTED (1u << 0)

/* Decode group for `Surrogate`. */
struct ak_dfix_Surrogate {
  struct ak_span text;
  struct ak_dfix_SurrogateInner nested;
  struct ak_span raw;
  uint32_t presence;
};
#define AK_DFIX_SURROGATE_PRESENT_NESTED (1u << 0)

/* Encode group for `Surrogate`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Surrogate {
  struct ak_str text;
  struct ak_ufix_SurrogateInner nested;
  struct ak_str raw;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_SURROGATE_PRESENT_NESTED (1u << 0)

/* Encode group for `WireZoo`. */
struct ak_efix_WireZoo {
  int32_t v_int32;
  int64_t v_int64;
  uint8_t v_bool;
  double v_double;
  uint32_t v_fixed32;
  struct ak_str v_string;
  struct ak_str v_bytes;
  int32_t v_enum;
  struct ak_efix_Timestamp v_msg;
  int32_t v_big_tag;
  uint32_t presence;
};
#define AK_EFIX_WIREZOO_PRESENT_V_MSG (1u << 0)

/* Decode group for `WireZoo`. */
struct ak_dfix_WireZoo {
  int32_t v_int32;
  int64_t v_int64;
  uint8_t v_bool;
  double v_double;
  uint32_t v_fixed32;
  struct ak_span v_string;
  struct ak_span v_bytes;
  int32_t v_enum;
  struct ak_dfix_Timestamp v_msg;
  int32_t v_big_tag;
  uint32_t presence;
};
#define AK_DFIX_WIREZOO_PRESENT_V_MSG (1u << 0)

/* Encode group for `WireZoo`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_WireZoo {
  int32_t v_int32;
  int64_t v_int64;
  uint8_t v_bool;
  double v_double;
  uint32_t v_fixed32;
  struct ak_str v_string;
  struct ak_str v_bytes;
  int32_t v_enum;
  struct ak_ufix_Timestamp v_msg;
  int32_t v_big_tag;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_WIREZOO_PRESENT_V_MSG (1u << 0)

/* Encode vtable for `Timestamp`. */
struct ak_evt_Timestamp {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `Timestamp` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Timestamp {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Timestamp *);
  ak_unk_f unknown;
};

/* Encode vtable for `Duration`. */
struct ak_evt_Duration {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `Duration` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Duration {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Duration *);
  ak_unk_f unknown;
};

/* Encode vtable for `ResultRaw`. */
struct ak_evt_ResultRaw {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `ResultRaw` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ResultRaw {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ResultRaw *);
  ak_unk_f unknown;
};

/* Encode vtable for `TaskOptions`. */
struct ak_evt_TaskOptions {
  ak_loop_f loop_options;
};

/* Decode vtable for `TaskOptions` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskOptions {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskOptions *);
  ak_unk_f unknown;
  ak_unk_f unk_options;
  void (*add_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `TaskOutput`. */
struct ak_evt_TaskOutput {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `TaskOutput` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskOutput {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskOutput *);
  ak_unk_f unknown;
};

/* Encode vtable for `TaskDetailed`. */
struct ak_evt_TaskDetailed {
  ak_loop_f loop_parent_task_ids;
  ak_loop_f loop_data_dependencies;
  ak_loop_f loop_expected_output_ids;
  ak_loop_f loop_retry_of_ids;
  ak_loop_f loop_options_options;
};

/* Decode vtable for `TaskDetailed` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskDetailed {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskDetailed *);
  ak_unk_f unknown;
  void (*add_parent_task_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_data_dependencies)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_expected_output_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_retry_of_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  ak_unk_f unk_options_options;
  void (*add_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `TaskSummary`. */
struct ak_evt_TaskSummary {
  ak_loop_f loop_options_options;
};

/* Decode vtable for `TaskSummary` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskSummary {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskSummary *);
  ak_unk_f unknown;
  ak_unk_f unk_options_options;
  void (*add_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `Probe`. */
struct ak_evt_Probe {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `Probe` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Probe {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Probe *);
  ak_unk_f unknown;
};

/* Encode vtable for `Empty`. */
struct ak_evt_Empty {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `Empty` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Empty {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Empty *);
  ak_unk_f unknown;
};

/* Encode vtable for `UploadResultData`. */
struct ak_evt_UploadResultData {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `UploadResultData` (the push family, ABI v1 section 7.1). */
struct ak_dvt_UploadResultData {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_UploadResultData *);
  ak_unk_f unknown;
};

/* Encode vtable for `MetricsBatch`. */
struct ak_evt_MetricsBatch {
  ak_loop_f loop_ticks;
  ak_loop_f loop_values;
  ak_loop_f loop_codes;
  ak_loop_f loop_flags;
  ak_loop_f loop_statuses;
};

/* Decode vtable for `MetricsBatch` (the push family, ABI v1 section 7.1). */
struct ak_dvt_MetricsBatch {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_MetricsBatch *);
  ak_unk_f unknown;
  void (*add_ticks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  void (*add_values)(ak_dec_ctx *, void *, int64_t, const double *, int32_t);
  void (*add_codes)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
  void (*add_flags)(ak_dec_ctx *, void *, int64_t, const uint8_t *, int32_t);
  void (*add_statuses)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
};

/* Encode vtable for `Pair`. */
struct ak_evt_Pair {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `Pair` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Pair {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Pair *);
  ak_unk_f unknown;
};

/* Encode vtable for `ListResultsResponse`. */
struct ak_evt_ListResultsResponse {
  ak_loop_f loop_results;
};

/* Decode vtable for `ListResultsResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListResultsResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListResultsResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_results;
  void (*add_results)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ResultRaw *, int32_t);
};

/* Encode vtable for `ListTasksDetailedResponse`. */
struct ak_evt_ListTasksDetailedResponse {
  ak_loop_f loop_tasks;
  const struct ak_evt_TaskDetailed *elem_tasks;
};

/* Decode vtable for `ListTasksDetailedResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListTasksDetailedResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListTasksDetailedResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_tasks;
  int64_t (*new_tasks)(ak_dec_ctx *, void *);
  void (*apply_tasks)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskDetailed *);
  void (*add_tasks_parent_task_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_data_dependencies)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_expected_output_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_retry_of_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `ListTaskSummaryResponse`. */
struct ak_evt_ListTaskSummaryResponse {
  ak_loop_f loop_tasks;
  const struct ak_evt_TaskSummary *elem_tasks;
};

/* Decode vtable for `ListTaskSummaryResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListTaskSummaryResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListTaskSummaryResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_tasks;
  int64_t (*new_tasks)(ak_dec_ctx *, void *);
  void (*apply_tasks)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskSummary *);
  void (*add_tasks_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `ListProbeResponse`. */
struct ak_evt_ListProbeResponse {
  ak_loop_f loop_probes;
};

/* Decode vtable for `ListProbeResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListProbeResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListProbeResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_probes;
  void (*add_probes)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_Probe *, int32_t);
};

/* Encode vtable for `ListMetricsResponse`. */
struct ak_evt_ListMetricsResponse {
  ak_loop_f loop_batches;
  const struct ak_evt_MetricsBatch *elem_batches;
};

/* Decode vtable for `ListMetricsResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListMetricsResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListMetricsResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_batches;
  int64_t (*new_batches)(ak_dec_ctx *, void *);
  void (*apply_batches)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_MetricsBatch *);
  void (*add_batches_ticks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  void (*add_batches_values)(ak_dec_ctx *, void *, int64_t, const double *, int32_t);
  void (*add_batches_codes)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
  void (*add_batches_flags)(ak_dec_ctx *, void *, int64_t, const uint8_t *, int32_t);
  void (*add_batches_statuses)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
};

/* Encode vtable for `UploadResultDataMessage`. */
struct ak_evt_UploadResultDataMessage {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `UploadResultDataMessage` (the push family, ABI v1 section 7.1). */
struct ak_dvt_UploadResultDataMessage {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_UploadResultDataMessage *);
  ak_unk_f unknown;
};

/* Encode vtable for `DualResponse`. */
struct ak_evt_DualResponse {
  ak_loop_f loop_left;
  ak_loop_f loop_right;
};

/* Decode vtable for `DualResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_DualResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_DualResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_left;
  void (*add_left)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_Pair *, int32_t);
  ak_unk_f unk_right;
  void (*add_right)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_Pair *, int32_t);
};

/* Encode vtable for `ChunkLeaf`. */
struct ak_evt_ChunkLeaf {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `ChunkLeaf` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ChunkLeaf {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ChunkLeaf *);
  ak_unk_f unknown;
};

/* Encode vtable for `ChunkInner`. */
struct ak_evt_ChunkInner {
  ak_loop_f loop_marks;
  ak_loop_f loop_leaves;
};

/* Decode vtable for `ChunkInner` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ChunkInner {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ChunkInner *);
  ak_unk_f unknown;
  void (*add_marks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  ak_unk_f unk_leaves;
  void (*add_leaves)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkLeaf *, int32_t);
};

/* Encode vtable for `ChunkElement`. */
struct ak_evt_ChunkElement {
  ak_loop_f loop_labels;
  ak_loop_f loop_attrs;
  ak_loop_f loop_inner_marks;
  ak_loop_f loop_inner_leaves;
};

/* Decode vtable for `ChunkElement` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ChunkElement {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ChunkElement *);
  ak_unk_f unknown;
  void (*add_labels)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  ak_unk_f unk_attrs;
  void (*add_attrs)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkElementAttrsEntry *, int32_t);
  void (*add_inner_marks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  ak_unk_f unk_inner_leaves;
  void (*add_inner_leaves)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkLeaf *, int32_t);
};

/* Encode vtable for `ChunkedResponse`. */
struct ak_evt_ChunkedResponse {
  ak_loop_f loop_items;
  const struct ak_evt_ChunkElement *elem_items;
};

/* Decode vtable for `ChunkedResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ChunkedResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ChunkedResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_items;
  int64_t (*new_items)(ak_dec_ctx *, void *);
  void (*apply_items)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkElement *);
  void (*add_items_labels)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_items_attrs)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkElementAttrsEntry *, int32_t);
  void (*add_items_inner_marks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  void (*add_items_inner_leaves)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkLeaf *, int32_t);
};

/* Encode vtable for `ChunkedResponseWide`. */
struct ak_evt_ChunkedResponseWide {
  ak_loop_f loop_items;
  const struct ak_evt_ChunkElement *elem_items;
};

/* Decode vtable for `ChunkedResponseWide` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ChunkedResponseWide {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ChunkedResponseWide *);
  ak_unk_f unknown;
  ak_unk_f unk_items;
  int64_t (*new_items)(ak_dec_ctx *, void *);
  void (*apply_items)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkElement *);
  void (*add_items_labels)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_items_attrs)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkElementAttrsEntry *, int32_t);
  void (*add_items_inner_marks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  void (*add_items_inner_leaves)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ChunkLeaf *, int32_t);
};

/* Encode vtable for `LeafElement`. */
struct ak_evt_LeafElement {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `LeafElement` (the push family, ABI v1 section 7.1). */
struct ak_dvt_LeafElement {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_LeafElement *);
  ak_unk_f unknown;
};

/* Encode vtable for `LeafResponse`. */
struct ak_evt_LeafResponse {
  ak_loop_f loop_items;
};

/* Decode vtable for `LeafResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_LeafResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_LeafResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_items;
  void (*add_items)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_LeafElement *, int32_t);
};

/* Encode vtable for `Surrogate`. */
struct ak_evt_Surrogate {
  ak_loop_f loop_attrs;
  ak_loop_f loop_texts;
};

/* Decode vtable for `Surrogate` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Surrogate {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Surrogate *);
  ak_unk_f unknown;
  ak_unk_f unk_attrs;
  void (*add_attrs)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_SurrogateAttrsEntry *, int32_t);
  void (*add_texts)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
};

/* Encode vtable for `SurrogateInner`. */
struct ak_evt_SurrogateInner {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `SurrogateInner` (the push family, ABI v1 section 7.1). */
struct ak_dvt_SurrogateInner {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_SurrogateInner *);
  ak_unk_f unknown;
};

/* Encode vtable for `WireZoo`. */
struct ak_evt_WireZoo {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `WireZoo` (the push family, ABI v1 section 7.1). */
struct ak_dvt_WireZoo {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_WireZoo *);
  ak_unk_f unknown;
};

/* Encode vtable for `TaskOptionsOptionsEntry`. */
struct ak_evt_TaskOptionsOptionsEntry {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `TaskOptionsOptionsEntry` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskOptionsOptionsEntry {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskOptionsOptionsEntry *);
  ak_unk_f unknown;
};

/* Encode vtable for `ChunkElementAttrsEntry`. */
struct ak_evt_ChunkElementAttrsEntry {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `ChunkElementAttrsEntry` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ChunkElementAttrsEntry {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ChunkElementAttrsEntry *);
  ak_unk_f unknown;
};

/* Encode vtable for `SurrogateAttrsEntry`. */
struct ak_evt_SurrogateAttrsEntry {
  const void *_reserved;  /* an empty struct has no defined size in C */
};

/* Decode vtable for `SurrogateAttrsEntry` (the push family, ABI v1 section 7.1). */
struct ak_dvt_SurrogateAttrsEntry {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_SurrogateAttrsEntry *);
  ak_unk_f unknown;
};

/* ABI v1 section 6: what the host calls are PLAIN EXPORTS, not a table. */
intptr_t ak_encode_Timestamp(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Timestamp *vt, const struct ak_efix_Timestamp *fix);
intptr_t ak_uencode_Timestamp(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Timestamp *vt, const struct ak_ufix_Timestamp *fix);
int32_t ak_decode_Timestamp(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_Timestamp *vt);
int32_t ak_parse_Timestamp(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_Duration(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Duration *vt, const struct ak_efix_Duration *fix);
intptr_t ak_uencode_Duration(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Duration *vt, const struct ak_ufix_Duration *fix);
int32_t ak_decode_Duration(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_Duration *vt);
int32_t ak_parse_Duration(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ResultRaw(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ResultRaw *vt, const struct ak_efix_ResultRaw *fix);
intptr_t ak_uencode_ResultRaw(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ResultRaw *vt, const struct ak_ufix_ResultRaw *fix);
int32_t ak_decode_ResultRaw(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ResultRaw *vt);
int32_t ak_parse_ResultRaw(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_TaskOptions(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskOptions *vt, const struct ak_efix_TaskOptions *fix);
intptr_t ak_uencode_TaskOptions(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskOptions *vt, const struct ak_ufix_TaskOptions *fix);
int32_t ak_decode_TaskOptions(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_TaskOptions *vt);
int32_t ak_parse_TaskOptions(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_TaskOutput(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskOutput *vt, const struct ak_efix_TaskOutput *fix);
intptr_t ak_uencode_TaskOutput(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskOutput *vt, const struct ak_ufix_TaskOutput *fix);
int32_t ak_decode_TaskOutput(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_TaskOutput *vt);
int32_t ak_parse_TaskOutput(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_TaskDetailed(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskDetailed *vt, const struct ak_efix_TaskDetailed *fix);
intptr_t ak_uencode_TaskDetailed(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskDetailed *vt, const struct ak_ufix_TaskDetailed *fix);
int32_t ak_decode_TaskDetailed(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_TaskDetailed *vt);
int32_t ak_parse_TaskDetailed(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_TaskSummary(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskSummary *vt, const struct ak_efix_TaskSummary *fix);
intptr_t ak_uencode_TaskSummary(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_TaskSummary *vt, const struct ak_ufix_TaskSummary *fix);
int32_t ak_decode_TaskSummary(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_TaskSummary *vt);
int32_t ak_parse_TaskSummary(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_Probe(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Probe *vt, const struct ak_efix_Probe *fix);
intptr_t ak_uencode_Probe(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Probe *vt, const struct ak_ufix_Probe *fix);
int32_t ak_decode_Probe(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_Probe *vt);
int32_t ak_parse_Probe(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_Empty(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Empty *vt, const struct ak_efix_Empty *fix);
intptr_t ak_uencode_Empty(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Empty *vt, const struct ak_ufix_Empty *fix);
int32_t ak_decode_Empty(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_Empty *vt);
int32_t ak_parse_Empty(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_UploadResultData(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_UploadResultData *vt, const struct ak_efix_UploadResultData *fix, const uint8_t *direct, size_t direct_len);
intptr_t ak_uencode_UploadResultData(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_UploadResultData *vt, const struct ak_ufix_UploadResultData *fix, const uint8_t *direct, size_t direct_len);
int32_t ak_decode_UploadResultData(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_UploadResultData *vt);
int32_t ak_parse_UploadResultData(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_MetricsBatch(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_MetricsBatch *vt, const struct ak_efix_MetricsBatch *fix);
intptr_t ak_uencode_MetricsBatch(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_MetricsBatch *vt, const struct ak_ufix_MetricsBatch *fix);
int32_t ak_decode_MetricsBatch(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_MetricsBatch *vt);
int32_t ak_parse_MetricsBatch(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_Pair(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Pair *vt, const struct ak_efix_Pair *fix);
intptr_t ak_uencode_Pair(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Pair *vt, const struct ak_ufix_Pair *fix);
int32_t ak_decode_Pair(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_Pair *vt);
int32_t ak_parse_Pair(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ListResultsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListResultsResponse *vt, const struct ak_efix_ListResultsResponse *fix);
intptr_t ak_uencode_ListResultsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListResultsResponse *vt, const struct ak_ufix_ListResultsResponse *fix);
int32_t ak_decode_ListResultsResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListResultsResponse *vt);
int32_t ak_parse_ListResultsResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ListTasksDetailedResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTasksDetailedResponse *vt, const struct ak_efix_ListTasksDetailedResponse *fix);
intptr_t ak_uencode_ListTasksDetailedResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTasksDetailedResponse *vt, const struct ak_ufix_ListTasksDetailedResponse *fix);
int32_t ak_decode_ListTasksDetailedResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListTasksDetailedResponse *vt);
int32_t ak_parse_ListTasksDetailedResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ListTaskSummaryResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTaskSummaryResponse *vt, const struct ak_efix_ListTaskSummaryResponse *fix);
intptr_t ak_uencode_ListTaskSummaryResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTaskSummaryResponse *vt, const struct ak_ufix_ListTaskSummaryResponse *fix);
int32_t ak_decode_ListTaskSummaryResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListTaskSummaryResponse *vt);
int32_t ak_parse_ListTaskSummaryResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ListProbeResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListProbeResponse *vt, const struct ak_efix_ListProbeResponse *fix);
intptr_t ak_uencode_ListProbeResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListProbeResponse *vt, const struct ak_ufix_ListProbeResponse *fix);
int32_t ak_decode_ListProbeResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListProbeResponse *vt);
int32_t ak_parse_ListProbeResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ListMetricsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListMetricsResponse *vt, const struct ak_efix_ListMetricsResponse *fix);
intptr_t ak_uencode_ListMetricsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListMetricsResponse *vt, const struct ak_ufix_ListMetricsResponse *fix);
int32_t ak_decode_ListMetricsResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListMetricsResponse *vt);
int32_t ak_parse_ListMetricsResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_UploadResultDataMessage(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_UploadResultDataMessage *vt, const struct ak_efix_UploadResultDataMessage *fix, const uint8_t *direct, size_t direct_len);
intptr_t ak_uencode_UploadResultDataMessage(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_UploadResultDataMessage *vt, const struct ak_ufix_UploadResultDataMessage *fix, const uint8_t *direct, size_t direct_len);
int32_t ak_decode_UploadResultDataMessage(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_UploadResultDataMessage *vt);
int32_t ak_parse_UploadResultDataMessage(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_DualResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_DualResponse *vt, const struct ak_efix_DualResponse *fix);
intptr_t ak_uencode_DualResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_DualResponse *vt, const struct ak_ufix_DualResponse *fix);
int32_t ak_decode_DualResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_DualResponse *vt);
int32_t ak_parse_DualResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ChunkLeaf(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkLeaf *vt, const struct ak_efix_ChunkLeaf *fix);
intptr_t ak_uencode_ChunkLeaf(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkLeaf *vt, const struct ak_ufix_ChunkLeaf *fix);
int32_t ak_decode_ChunkLeaf(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ChunkLeaf *vt);
int32_t ak_parse_ChunkLeaf(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ChunkInner(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkInner *vt, const struct ak_efix_ChunkInner *fix);
intptr_t ak_uencode_ChunkInner(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkInner *vt, const struct ak_ufix_ChunkInner *fix);
int32_t ak_decode_ChunkInner(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ChunkInner *vt);
int32_t ak_parse_ChunkInner(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ChunkElement(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkElement *vt, const struct ak_efix_ChunkElement *fix);
intptr_t ak_uencode_ChunkElement(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkElement *vt, const struct ak_ufix_ChunkElement *fix);
int32_t ak_decode_ChunkElement(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ChunkElement *vt);
int32_t ak_parse_ChunkElement(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ChunkedResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkedResponse *vt, const struct ak_efix_ChunkedResponse *fix);
intptr_t ak_uencode_ChunkedResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkedResponse *vt, const struct ak_ufix_ChunkedResponse *fix);
int32_t ak_decode_ChunkedResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ChunkedResponse *vt);
int32_t ak_parse_ChunkedResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_ChunkedResponseWide(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkedResponseWide *vt, const struct ak_efix_ChunkedResponseWide *fix);
intptr_t ak_uencode_ChunkedResponseWide(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ChunkedResponseWide *vt, const struct ak_ufix_ChunkedResponseWide *fix);
int32_t ak_decode_ChunkedResponseWide(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ChunkedResponseWide *vt);
int32_t ak_parse_ChunkedResponseWide(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_LeafElement(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_LeafElement *vt, const struct ak_efix_LeafElement *fix);
intptr_t ak_uencode_LeafElement(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_LeafElement *vt, const struct ak_ufix_LeafElement *fix);
int32_t ak_decode_LeafElement(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_LeafElement *vt);
int32_t ak_parse_LeafElement(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_LeafResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_LeafResponse *vt, const struct ak_efix_LeafResponse *fix);
intptr_t ak_uencode_LeafResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_LeafResponse *vt, const struct ak_ufix_LeafResponse *fix);
int32_t ak_decode_LeafResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_LeafResponse *vt);
int32_t ak_parse_LeafResponse(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_Surrogate(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Surrogate *vt, const struct ak_efix_Surrogate *fix);
intptr_t ak_uencode_Surrogate(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_Surrogate *vt, const struct ak_ufix_Surrogate *fix);
int32_t ak_decode_Surrogate(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_Surrogate *vt);
int32_t ak_parse_Surrogate(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_SurrogateInner(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_SurrogateInner *vt, const struct ak_efix_SurrogateInner *fix);
intptr_t ak_uencode_SurrogateInner(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_SurrogateInner *vt, const struct ak_ufix_SurrogateInner *fix);
int32_t ak_decode_SurrogateInner(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_SurrogateInner *vt);
int32_t ak_parse_SurrogateInner(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
intptr_t ak_encode_WireZoo(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_WireZoo *vt, const struct ak_efix_WireZoo *fix);
intptr_t ak_uencode_WireZoo(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_WireZoo *vt, const struct ak_ufix_WireZoo *fix);
int32_t ak_decode_WireZoo(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_WireZoo *vt);
int32_t ak_parse_WireZoo(ak_dec_ctx *ctx, const uint8_t *buf, size_t len);
int32_t ak_elemu_ChunkElement(ak_enc_ctx *ctx, const struct ak_efix_ChunkElement *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_ChunkElement(ak_enc_ctx *ctx, const struct ak_ufix_ChunkElement *elems, int32_t n, int64_t tok0);
int32_t ak_elem_ChunkElementAttrsEntry(ak_enc_ctx *ctx, const struct ak_efix_ChunkElementAttrsEntry *elems, int32_t n);
int32_t ak_uelem_ChunkElementAttrsEntry(ak_enc_ctx *ctx, const struct ak_ufix_ChunkElementAttrsEntry *elems, int32_t n);
int32_t ak_elem_ChunkLeaf(ak_enc_ctx *ctx, const struct ak_efix_ChunkLeaf *elems, int32_t n);
int32_t ak_uelem_ChunkLeaf(ak_enc_ctx *ctx, const struct ak_ufix_ChunkLeaf *elems, int32_t n);
int32_t ak_elem_LeafElement(ak_enc_ctx *ctx, const struct ak_efix_LeafElement *elems, int32_t n);
int32_t ak_uelem_LeafElement(ak_enc_ctx *ctx, const struct ak_ufix_LeafElement *elems, int32_t n);
int32_t ak_elemu_MetricsBatch(ak_enc_ctx *ctx, const struct ak_efix_MetricsBatch *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_MetricsBatch(ak_enc_ctx *ctx, const struct ak_ufix_MetricsBatch *elems, int32_t n, int64_t tok0);
int32_t ak_elem_Pair(ak_enc_ctx *ctx, const struct ak_efix_Pair *elems, int32_t n);
int32_t ak_uelem_Pair(ak_enc_ctx *ctx, const struct ak_ufix_Pair *elems, int32_t n);
int32_t ak_elem_Probe(ak_enc_ctx *ctx, const struct ak_efix_Probe *elems, int32_t n);
int32_t ak_uelem_Probe(ak_enc_ctx *ctx, const struct ak_ufix_Probe *elems, int32_t n);
int32_t ak_elem_ResultRaw(ak_enc_ctx *ctx, const struct ak_efix_ResultRaw *elems, int32_t n);
int32_t ak_uelem_ResultRaw(ak_enc_ctx *ctx, const struct ak_ufix_ResultRaw *elems, int32_t n);
int32_t ak_elem_SurrogateAttrsEntry(ak_enc_ctx *ctx, const struct ak_efix_SurrogateAttrsEntry *elems, int32_t n);
int32_t ak_uelem_SurrogateAttrsEntry(ak_enc_ctx *ctx, const struct ak_ufix_SurrogateAttrsEntry *elems, int32_t n);
int32_t ak_elemu_TaskDetailed(ak_enc_ctx *ctx, const struct ak_efix_TaskDetailed *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_TaskDetailed(ak_enc_ctx *ctx, const struct ak_ufix_TaskDetailed *elems, int32_t n, int64_t tok0);
int32_t ak_elem_TaskOptionsOptionsEntry(ak_enc_ctx *ctx, const struct ak_efix_TaskOptionsOptionsEntry *elems, int32_t n);
int32_t ak_uelem_TaskOptionsOptionsEntry(ak_enc_ctx *ctx, const struct ak_ufix_TaskOptionsOptionsEntry *elems, int32_t n);
int32_t ak_elemu_TaskSummary(ak_enc_ctx *ctx, const struct ak_efix_TaskSummary *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_TaskSummary(ak_enc_ctx *ctx, const struct ak_ufix_TaskSummary *elems, int32_t n, int64_t tok0);
int32_t ak_blob_run(ak_enc_ctx *ctx, const struct ak_str *elems, int32_t n);
int32_t ak_run_i32(ak_enc_ctx *ctx, const int32_t *p, size_t n);
int32_t ak_run_i64(ak_enc_ctx *ctx, const int64_t *p, size_t n);
int32_t ak_run_f64(ak_enc_ctx *ctx, const double *p, size_t n);
int32_t ak_run_u8(ak_enc_ctx *ctx, const uint8_t *p, size_t n);

/* ---- the fixed entry points (plan.FIXED.functions) ----------------------------- */
/* lifecycle */
/* Once per process, before anything else (plan.lifecycle). */
int32_t ak_init(const struct ak_init_opts *opts, struct ak_err *err);
/* 1 once ak_init has returned successfully. */
int32_t ak_initialized(void);
/* A NUL-terminated build id. */
const char *ak_build_id(void);
/* Test hook: one line through the installed log bridge. */
int32_t ak_log_test(uint32_t level, const uint8_t *msg, size_t len);
/* Test hook: a panic inside the core. */
void ak_panic_test(void);
/* context */
uint32_t ak_abi_version(void);
ak_enc_ctx *ak_enc_ctx_new(void);
void ak_enc_ctx_free(ak_enc_ctx *ctx);
/* Clears the buffer and the sticky slot. */
void ak_enc_reset(ak_enc_ctx *ctx);
/* Borrow what the context has encoded, valid until the next reset; returns the status. */
int32_t ak_enc_take(ak_enc_ctx *ctx, const uint8_t * *ptr, size_t *len);
ak_dec_ctx *ak_dec_ctx_new(void);
void ak_dec_ctx_free(ak_dec_ctx *ctx);
/* error */
/* Sticky, first error wins; takes either context (ABI v1 section 5). */
void ak_fail(void *ctx, int32_t code, const uint8_t *msg, uint32_t msg_len);
int32_t ak_enc_err(const ak_enc_ctx *ctx);
int32_t ak_dec_err(const ak_dec_ctx *ctx);
void ak_dec_err_reset(ak_dec_ctx *ctx);
/* transcode */
/* UTF-8, validate and refuse. */
ak_transcode_fn ak_tc_utf8(void);
/* UTF-8, no validation. */
ak_transcode_fn ak_tc_utf8_trusted(void);
/* UTF-8, SIMD validator. */
ak_transcode_fn ak_tc_utf8_simd(void);
/* bytes: a copy. */
ak_transcode_fn ak_tc_bytes(void);
/* UTF-16 code units -> UTF-8. */
ak_transcode_fn ak_tc_utf16(void);
/* Latin-1 bytes -> UTF-8. */
ak_transcode_fn ak_tc_latin1(void);
/* counters */
void ak_enc_counters(const ak_enc_ctx *ctx, struct AkCounters *out);
/* Counting build: the HOST reports a reverse crossing the core cannot see. */
void ak_enc_count_reverse(ak_enc_ctx *ctx);
void ak_enc_counters_reset(ak_enc_ctx *ctx);
void ak_dec_counters(const ak_dec_ctx *ctx, struct AkCounters *out);
void ak_dec_counters_reset(ak_dec_ctx *ctx);
size_t ak_enc_site_moves(const ak_enc_ctx *ctx, uint32_t *out, size_t cap);
/* noop */
/* A crossing and nothing else. */
uint64_t ak_noop(uint64_t x);
/* An identical twin of ak_noop. */
uint64_t ak_noop2(uint64_t x);
/* ak_noop with the init guard. */
uint64_t ak_noop_guarded(uint64_t x);
/* One forward and one reverse crossing. */
uint64_t ak_noop_reverse(uint64_t (*f)(uint64_t), uint64_t x);
/* pull */
int32_t ak_bdr_reserve(ak_dec_ctx *ctx, size_t bytes);
size_t ak_bdr_footprint(const ak_dec_ctx *ctx);
intptr_t ak_bdr_drain(ak_dec_ctx *ctx, uint8_t *dst, size_t cap, size_t *cursor);
int32_t ak_bdr_ptr(ak_dec_ctx *ctx, const uint8_t * *ptr, size_t *len);
void ak_bdr_reset(ak_dec_ctx *ctx);
/* Counting build: the host reports the forward crossings of a drain loop. */
void ak_bdr_count_forward(ak_dec_ctx *ctx, uint32_t n);
/* layout */
/* ABI v1 section 10: the core's own view of every group layout. */
size_t ak_layout_facts(uint32_t *out, size_t cap);

/* ---- section 9: the RPC half (plan.rpc, R-G5) -----------------------------------
 * Declared only here. A host never hand-declares one of these: R-D2 was a 3-field
 * copy of a 6-field struct, R-G5 a `u64` timeout declared `i32` on one side. */
typedef struct ak_runtime ak_runtime;
typedef struct ak_client ak_client;
typedef struct ak_call ak_call;
typedef struct ak_queue ak_queue;
/* A byte range the core owns until the host releases it with `ak_bytes_free`. */
struct ak_bytes {
  const uint8_t *ptr;
  size_t len;
  void *owner;  /* The core's handle on the allocation. The host passes it back and does not read it. */
};
typedef struct ak_bytes ak_bytes;
#define AK_BYTES_FIELDS 3
/* What a completion carries. Released with `ak_bytes_free`, as the blocking delivery's bytes are, so a host has one release path whichever delivery it takes. */
struct ak_completion {
  uint64_t tag;
  int32_t status;
  struct ak_bytes bytes;
};
typedef struct ak_completion ak_completion;
#define AK_COMPLETION_FIELDS 3
/* The transport settings ArmoniK pins. The stream and the connection window are separate settings on tonic/hyper, so both are here. Zero means "the stack's". */
struct ak_client_opts {
  uint32_t stream_window;  /* SETTINGS_INITIAL_WINDOW_SIZE per stream; 0 = default. ArmoniK: 4 MiB. */
  uint32_t connection_window;  /* The connection-level window, a SEPARATE setting; 0 = default. */
  int32_t adaptive_window;  /* 1 on, 0 off, -1 default (off). Overrides both windows when on. */
  uint32_t max_recv_message;  /* Largest message accepted, bytes; 0 = default. */
  uint32_t max_send_message;  /* Largest message sent, bytes; 0 = default. */
  int32_t tcp_nagle;  /* ArmoniK's tcp_nagle_algorithm: 1 Nagle on, 0 off, -1 default. ArmoniK ships it OFF. */
};
typedef struct ak_client_opts ak_client_opts;
#define AK_CLIENT_OPTS_FIELDS 6
/* Called ONCE per call, on a thread the core owns. */
typedef void (*ak_completion_cb)(void *user_data, struct ak_completion *comp);
#define AK_QUEUE_OK 0  /* `ak_queue_next` returned a completion. */
#define AK_QUEUE_TIMEOUT 1  /* The timeout expired with no completion. Not an error. */
#define AK_QUEUE_SHUTDOWN 2  /* The queue is shutting down and is drained. */
ak_runtime *ak_runtime_new(uint32_t worker_threads);
void ak_runtime_destroy(ak_runtime *r);
ak_client *ak_client_new(ak_runtime *r, const uint8_t *uri, size_t uri_len);
/* A client with the transport pinned. NULL options = `ak_client_new`. */
ak_client *ak_client_new_opts(ak_runtime *r, const uint8_t *uri, size_t uri_len, const struct ak_client_opts *opts);
void ak_client_destroy(ak_client *c);
/* Blocking delivery: one crossing in, `ak_bytes_free` the only other. */
int32_t ak_call_unary(ak_client *c, const uint8_t *path, size_t path_len, const uint8_t *req, size_t req_len, struct ak_bytes *out);
void ak_bytes_free(struct ak_bytes *b);
/* Callback delivery: 2 forward crossings and 1 reverse. */
ak_call *ak_call_unary_cb(ak_client *c, const uint8_t *path, size_t path_len, const uint8_t *req, size_t req_len, ak_completion_cb cb, void *user_data, uint64_t tag);
/* Completion-queue delivery: no upcall. 3 forward crossings and 0 reverse. */
ak_call *ak_call_unary_q(ak_client *c, const uint8_t *path, size_t path_len, const uint8_t *req, size_t req_len, ak_queue *q, uint64_t tag);
ak_queue *ak_queue_new(void);
/* Wait up to `timeout_ms` for one completion. R-G5: `u64`, as the core defines it. */
int32_t ak_queue_next(ak_queue *q, struct ak_completion *out, uint64_t timeout_ms);
void ak_queue_shutdown(ak_queue *q);
void ak_queue_destroy(ak_queue *q);
void ak_call_cancel(ak_call *h);
void ak_call_destroy(ak_call *h);
/* RPC boundary-call counts (counting build). Exported by a core built with `rpc`. */
struct ak_rpc_counters {
  uint64_t forward;
  uint64_t reverse;
};
/* 1 if this core counts RPC crossings. */
int32_t ak_rpc_counting(void);
void ak_rpc_counters(struct ak_rpc_counters *out);
void ak_rpc_counters_reset(void);

/* ABI v1 section 10 and obligation 12.3: layouts asserted, not assumed. */
#ifdef __cplusplus
#define AK_SASSERT(c, m) static_assert(c, m)
#else
#define AK_SASSERT_CAT2(a, b) a##b
#define AK_SASSERT_CAT(a, b) AK_SASSERT_CAT2(a, b)
#define AK_SASSERT(c, m) typedef char AK_SASSERT_CAT(ak_sa_, __LINE__)[(c) ? 1 : -1]
#endif

/* The fixed structs' sizes on a 64-bit host (plan.FIXED.sizes). */
#if UINTPTR_MAX == 0xFFFFFFFFFFFFFFFFu
AK_SASSERT(sizeof(struct ak_str) == 24, "sizeof ak_str");
AK_SASSERT(sizeof(struct ak_span) == 12, "sizeof ak_span");
AK_SASSERT(sizeof(struct ak_blob) == 16, "sizeof ak_blob");
AK_SASSERT(sizeof(struct ak_uspan) == 16, "sizeof ak_uspan");
AK_SASSERT(sizeof(struct ak_err) == 8, "sizeof ak_err");
AK_SASSERT(sizeof(struct ak_init_opts) == 24, "sizeof ak_init_opts");
AK_SASSERT(sizeof(struct AkCounters) == 48, "sizeof AkCounters");
AK_SASSERT(sizeof(struct ak_bdr_rec) == 24, "sizeof ak_bdr_rec");
AK_SASSERT(offsetof(struct ak_bdr_rec, token) == 8, "ak_bdr_rec.token");
#endif
AK_SASSERT(sizeof(struct ak_client_opts) == 24, "sizeof ak_client_opts");
AK_SASSERT(offsetof(struct ak_client_opts, stream_window) == 0, "ak_client_opts.stream_window");
AK_SASSERT(offsetof(struct ak_client_opts, connection_window) == 4, "ak_client_opts.connection_window");
AK_SASSERT(offsetof(struct ak_client_opts, adaptive_window) == 8, "ak_client_opts.adaptive_window");
AK_SASSERT(offsetof(struct ak_client_opts, max_recv_message) == 12, "ak_client_opts.max_recv_message");
AK_SASSERT(offsetof(struct ak_client_opts, max_send_message) == 16, "ak_client_opts.max_send_message");
AK_SASSERT(offsetof(struct ak_client_opts, tcp_nagle) == 20, "ak_client_opts.tcp_nagle");

/* Number of (struct, member) layout facts this header pins. */
#define AK_LAYOUT_FACTS 542

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* AK_ABI_H */
