// @generated by ffi/poc/csharp/gen/generate.py from ffi/schema/shapes.json.
// Do not edit. `gen/generate.py --check` fails if this file is not what the
// generator writes today.
//
// The facade types every arm of this slice operates on.

using System;
using System.Collections.Generic;
using Armonik.Ffi.Facade;

namespace Armonik.Ffi.Corpus;

/// Open enum: a wire value this build was not generated against is representable as
/// `(ResultStatus)v` and round-trips losslessly, which is what design/SHAPES.md's open-
/// enum row asks for. A C# enum is open by construction, so unlike the Rust facade this
/// needs no Unknown case.
public enum ResultStatus
{
    Unspecified = 0,
    Created = 1,
    Completed = 2,
    Aborted = 3,
    Deleted = 4,
    Notfound = 127,
}

/// Open enum: a wire value this build was not generated against is representable as
/// `(TaskStatus)v` and round-trips losslessly, which is what design/SHAPES.md's open-
/// enum row asks for. A C# enum is open by construction, so unlike the Rust facade this
/// needs no Unknown case.
public enum TaskStatus
{
    Unspecified = 0,
    Creating = 1,
    Submitted = 2,
    Dispatched = 3,
    Completed = 4,
    Error = 5,
    Timeout = 6,
    Cancelling = 7,
    Cancelled = 8,
    Processing = 9,
    Processed = 10,
    Retried = 11,
    Pending = 12,
    Paused = 13,
}

/// Open enum: a wire value this build was not generated against is representable as
/// `(ProbeKind)v` and round-trips losslessly, which is what design/SHAPES.md's open-
/// enum row asks for. A C# enum is open by construction, so unlike the Rust facade this
/// needs no Unknown case.
public enum ProbeKind
{
    Unspecified = 0,
    Alpha = 1,
    Beta = 2,
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class Timestamp
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public long Seconds;
    public int Nanos;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class Duration
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public long Seconds;
    public int Nanos;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class ResultRaw
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string SessionId = "";
    public string Name = "";
    public string OwnerTaskId = "";
    public ResultStatus Status;
    public Timestamp CreatedAt;
    public Timestamp CompletedAt;
    public string ResultId = "";
    public long Size;
    public string CreatedBy = "";
    public byte[] OpaqueId = EmptyBytes;
    public bool ManualDeletion;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class TaskOptions
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public OrderedMap<string, string> Options = new OrderedMap<string, string>();
    public Duration MaxDuration;
    public int MaxRetries;
    public int Priority;
    public string PartitionId = "";
    public string ApplicationName = "";
    public string ApplicationVersion = "";
    public string ApplicationNamespace = "";
    public string ApplicationService = "";
    public string EngineType = "";
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class TaskOutput
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public bool Success;
    public string Error = "";
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class TaskDetailed
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public string SessionId = "";
    public string OwnerPodId = "";
    public List<string> ParentTaskIds = new List<string>();
    public List<string> DataDependencies = new List<string>();
    public List<string> ExpectedOutputIds = new List<string>();
    public List<string> RetryOfIds = new List<string>();
    public TaskStatus Status;
    public string StatusMessage = "";
    public TaskOptions Options;
    public Timestamp CreatedAt;
    public Timestamp SubmittedAt;
    public Timestamp StartedAt;
    public Timestamp EndedAt;
    public Timestamp PodTtl;
    public TaskOutput Output;
    public string PodHostname = "";
    public Timestamp ReceivedAt;
    public Timestamp AcquiredAt;
    public Duration CreationToEndDuration;
    public Duration ProcessingToEndDuration;
    public string InitialTaskId = "";
    public Duration ReceivedToEndDuration;
    public Timestamp ProcessedAt;
    public Timestamp FetchedAt;
    public string PayloadId = "";
    public string CreatedBy = "";
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class TaskSummary
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public string SessionId = "";
    public TaskOptions Options;
    public TaskStatus Status;
    public Timestamp CreatedAt;
    public string Error = "";
    public string StatusMessage = "";
    public long CountDataDependencies;
}

/// Which member of `Probe.body` is set. `None` is not a member: it is the state
/// design/SHAPES.md says a by-value group cannot reach.
public enum ProbeBodyCase
{
    None = 0,
    AsInt = 10,
    AsText = 11,
    AsBlob = 12,
    AsStamp = 13,
    AsNothing = 14,
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class Probe
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public int? OptCount;
    public string OptLabel;
    public bool? OptFlag;

    public ProbeBodyCase BodyCase;
    public long AsInt;
    public string AsText;
    public byte[] AsBlob;
    public Timestamp AsStamp;
    public Empty AsNothing;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class Empty
{
    internal static readonly byte[] EmptyBytes = new byte[0];
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class UploadResultData
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string SessionId = "";
    public string ResultId = "";
    public byte[] DataChunk = EmptyBytes;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class MetricsBatch
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public List<long> Ticks = new List<long>();
    public List<double> Values = new List<double>();
    public List<int> Codes = new List<int>();
    public List<bool> Flags = new List<bool>();
    public List<TaskStatus> Statuses = new List<TaskStatus>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class Pair
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Key = "";
    public int Value;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ListResultsResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<ResultRaw> Results = new List<ResultRaw>();
    public int Page;
    public int Total;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ListTasksDetailedResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<TaskDetailed> Tasks = new List<TaskDetailed>();
    public int Page;
    public int Total;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ListTaskSummaryResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<TaskSummary> Tasks = new List<TaskSummary>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ListProbeResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<Probe> Probes = new List<Probe>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ListMetricsResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<MetricsBatch> Batches = new List<MetricsBatch>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class UploadResultDataMessage
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public UploadResultData Upload;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class DualResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<Pair> Left = new List<Pair>();
    public List<Pair> Right = new List<Pair>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class ChunkLeaf
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string K = "";
    public int V;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ChunkInner
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<long> Marks = new List<long>();
    public List<ChunkLeaf> Leaves = new List<ChunkLeaf>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ChunkElement
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<string> Labels = new List<string>();
    public OrderedMap<string, string> Attrs = new OrderedMap<string, string>();
    public string Id = "";
    public ChunkInner Inner;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ChunkedResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<ChunkElement> Items = new List<ChunkElement>();
    public int Page;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class ChunkedResponseWide
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<ChunkElement> Items = new List<ChunkElement>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class LeafElement
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Id = "";
    public long N;
    public Timestamp Stamp;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class LeafResponse
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public List<LeafElement> Items = new List<LeafElement>();
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class Surrogate
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Text = "";
    public SurrogateInner Nested;
    public OrderedMap<string, string> Attrs = new OrderedMap<string, string>();
    public List<string> Texts = new List<string>();
    public byte[] Raw = EmptyBytes;
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class SurrogateInner
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public string Text = "";
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is NOT a leaf, so it cannot be
/// batched.
public sealed class Nest
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public Nest Child;
    public string Leaf = "";
}

/// corpus.proto
/// Batching predicate (ABI v1 6/7.2): this message is a LEAF, so a run of them can
/// share one group buffer.
public sealed class WireZoo
{
    internal static readonly byte[] EmptyBytes = new byte[0];
    public int VInt32;
    public long VInt64;
    public bool VBool;
    public double VDouble;
    public uint VFixed32;
    public string VString = "";
    public byte[] VBytes = EmptyBytes;
    public ResultStatus VEnum;
    public Timestamp VMsg;
    public int VBigTag;
}
