// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/schema/shapes.json). Do not edit.

package ak.borrow;

/** Protos/V1/results_common.proto, tags preserved including the gap at 7 */
public final class ResultRaw {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public ak.Utf8View session_id = ak.Utf8View.EMPTY;
  public ak.Utf8View name = ak.Utf8View.EMPTY;
  public ak.Utf8View owner_task_id = ak.Utf8View.EMPTY;
  public int status = 0;
  public Timestamp created_at = null;
  public Timestamp completed_at = null;
  public ak.Utf8View result_id = ak.Utf8View.EMPTY;
  public long size = 0L;
  public ak.Utf8View created_by = ak.Utf8View.EMPTY;
  public byte[] opaque_id = EMPTY_BYTES;
  public boolean manual_deletion = false;
}
