/* @generated by ffi/poc/cpp/gen/generate.py from ffi/schema/shapes.json. Do not edit. */

/* The C ABI of ffi/design/ABI-v1.md, version 1.
 *
 * Fixed part (sections 4, 5, 10) and per-message part (section 6's groups and vtables,
 * section 7's fixes). C99/C++11 clean: nothing here depends on the standard level, which
 * is the hard stop README section 5.1 puts on this slice.
 */
#ifndef AK_ABI_H
#define AK_ABI_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ---- section 5: errors ---------------------------------------------------------- */
#define AK_OK                   0
#define AK_ALREADY_INITIALIZED  1
#define AK_ERR_HOST            (-1)
#define AK_ERR_MALFORMED       (-2)
#define AK_ERR_TRUNCATED       (-3)
#define AK_ERR_DEPTH           (-4)
#define AK_ERR_LIMIT           (-5)
#define AK_ERR_TRANSCODE       (-6)
#define AK_ERR_CAPACITY        (-7)
#define AK_ERR_INVALID_STATE   (-8)
#define AK_ERR_PANIC           (-9)
#define AK_ERR_UNINITIALIZED  (-10)
#define AK_ERR_ABI            (-11)

#define AK_ABI_VERSION 1u

/* ---- section 4: common vocabulary ------------------------------------------------ */

typedef int32_t (*ak_grow_fn)(void *sink, int32_t want, uint8_t **dst, int32_t *cap);
typedef int32_t (*ak_transcode_fn)(const void *src, size_t len,
                                   uint8_t *dst, int32_t cap,
                                   ak_grow_fn grow, void *sink);

/* Encode: a string or bytes field as DATA inside the group, never a call. `len` counts
 * SOURCE code units; for a C++ host holding std::string that is bytes. `tc == NULL` means
 * the field is ABSENT, which is how a group tells absent from present-and-empty. */
struct ak_str { const void *data; size_t len; ak_transcode_fn tc; };

/* ABI v1 section 8: a reserved `data` value meaning "this field is a direct argument of
 * the call". C++ never needs it (there is nothing to pin) and pays nothing for it. */
#define AK_STR_DIRECT ((const void *)(uintptr_t)1)

/* Decode: an OFFSET into the buffer the host handed in, plus a byte length. */
struct ak_span { uint32_t off, len, coder; };

/* Decision 11's unknown-field bag: two words, not three. */
struct ak_blob { const void *data; size_t len; };

struct ak_uspan { int64_t token; uint32_t off, len; };

#define AK_TOKEN_ROOT ((int64_t)-1)

typedef struct ak_enc_ctx ak_enc_ctx;
typedef struct ak_dec_ctx ak_dec_ctx;

typedef int32_t (*ak_loop_f)(ak_enc_ctx *ctx, const void *obj, int64_t token);
typedef void (*ak_unk_f)(ak_dec_ctx *ctx, void *obj, const struct ak_uspan *spans, int32_t n);

/* Encode group for `TaskOptionsOptionsEntry`. */
struct ak_efix_TaskOptionsOptionsEntry {
  struct ak_str key;
  struct ak_str value;
  uint32_t presence;
};

/* Decode group for `TaskOptionsOptionsEntry`. */
struct ak_dfix_TaskOptionsOptionsEntry {
  struct ak_span key;
  struct ak_span value;
  uint32_t presence;
};

/* Encode group for `TaskOptionsOptionsEntry`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskOptionsOptionsEntry {
  struct ak_str key;
  struct ak_str value;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Timestamp`. */
struct ak_efix_Timestamp {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Decode group for `Timestamp`. */
struct ak_dfix_Timestamp {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Encode group for `Timestamp`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Timestamp {
  int64_t seconds;
  int32_t nanos;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Duration`. */
struct ak_efix_Duration {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Decode group for `Duration`. */
struct ak_dfix_Duration {
  int64_t seconds;
  int32_t nanos;
  uint32_t presence;
};

/* Encode group for `Duration`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Duration {
  int64_t seconds;
  int32_t nanos;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ResultRaw`. */
struct ak_efix_ResultRaw {
  struct ak_str session_id;
  struct ak_str name;
  struct ak_str owner_task_id;
  int32_t status;
  struct ak_efix_Timestamp created_at;
  struct ak_efix_Timestamp completed_at;
  struct ak_str result_id;
  int64_t size;
  struct ak_str created_by;
  struct ak_str opaque_id;
  uint8_t manual_deletion;
  uint32_t presence;
};
#define AK_EFIX_RESULTRAW_PRESENT_CREATED_AT (1u << 0)
#define AK_EFIX_RESULTRAW_PRESENT_COMPLETED_AT (1u << 1)

/* Decode group for `ResultRaw`. */
struct ak_dfix_ResultRaw {
  struct ak_span session_id;
  struct ak_span name;
  struct ak_span owner_task_id;
  int32_t status;
  struct ak_dfix_Timestamp created_at;
  struct ak_dfix_Timestamp completed_at;
  struct ak_span result_id;
  int64_t size;
  struct ak_span created_by;
  struct ak_span opaque_id;
  uint8_t manual_deletion;
  uint32_t presence;
};
#define AK_DFIX_RESULTRAW_PRESENT_CREATED_AT (1u << 0)
#define AK_DFIX_RESULTRAW_PRESENT_COMPLETED_AT (1u << 1)

/* Encode group for `ResultRaw`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ResultRaw {
  struct ak_str session_id;
  struct ak_str name;
  struct ak_str owner_task_id;
  int32_t status;
  struct ak_ufix_Timestamp created_at;
  struct ak_ufix_Timestamp completed_at;
  struct ak_str result_id;
  int64_t size;
  struct ak_str created_by;
  struct ak_str opaque_id;
  uint8_t manual_deletion;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_RESULTRAW_PRESENT_CREATED_AT (1u << 0)
#define AK_UFIX_RESULTRAW_PRESENT_COMPLETED_AT (1u << 1)

/* Encode group for `TaskOptions`. */
struct ak_efix_TaskOptions {
  struct ak_efix_Duration max_duration;
  int32_t max_retries;
  int32_t priority;
  struct ak_str partition_id;
  struct ak_str application_name;
  struct ak_str application_version;
  struct ak_str application_namespace;
  struct ak_str application_service;
  struct ak_str engine_type;
  uint32_t presence;
};
#define AK_EFIX_TASKOPTIONS_PRESENT_MAX_DURATION (1u << 0)

/* Decode group for `TaskOptions`. */
struct ak_dfix_TaskOptions {
  struct ak_dfix_Duration max_duration;
  int32_t max_retries;
  int32_t priority;
  struct ak_span partition_id;
  struct ak_span application_name;
  struct ak_span application_version;
  struct ak_span application_namespace;
  struct ak_span application_service;
  struct ak_span engine_type;
  uint32_t presence;
};
#define AK_DFIX_TASKOPTIONS_PRESENT_MAX_DURATION (1u << 0)

/* Encode group for `TaskOptions`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskOptions {
  struct ak_ufix_Duration max_duration;
  int32_t max_retries;
  int32_t priority;
  struct ak_str partition_id;
  struct ak_str application_name;
  struct ak_str application_version;
  struct ak_str application_namespace;
  struct ak_str application_service;
  struct ak_str engine_type;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_TASKOPTIONS_PRESENT_MAX_DURATION (1u << 0)

/* Encode group for `TaskOutput`. */
struct ak_efix_TaskOutput {
  uint8_t success;
  struct ak_str error;
  uint32_t presence;
};

/* Decode group for `TaskOutput`. */
struct ak_dfix_TaskOutput {
  uint8_t success;
  struct ak_span error;
  uint32_t presence;
};

/* Encode group for `TaskOutput`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskOutput {
  uint8_t success;
  struct ak_str error;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `TaskDetailed`. */
struct ak_efix_TaskDetailed {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_str owner_pod_id;
  int32_t status;
  struct ak_str status_message;
  struct ak_efix_TaskOptions options;
  struct ak_efix_Timestamp created_at;
  struct ak_efix_Timestamp submitted_at;
  struct ak_efix_Timestamp started_at;
  struct ak_efix_Timestamp ended_at;
  struct ak_efix_Timestamp pod_ttl;
  struct ak_efix_TaskOutput output;
  struct ak_str pod_hostname;
  struct ak_efix_Timestamp received_at;
  struct ak_efix_Timestamp acquired_at;
  struct ak_efix_Duration creation_to_end_duration;
  struct ak_efix_Duration processing_to_end_duration;
  struct ak_str initial_task_id;
  struct ak_efix_Duration received_to_end_duration;
  struct ak_efix_Timestamp processed_at;
  struct ak_efix_Timestamp fetched_at;
  struct ak_str payload_id;
  struct ak_str created_by;
  uint32_t presence;
};
#define AK_EFIX_TASKDETAILED_PRESENT_OPTIONS (1u << 0)
#define AK_EFIX_TASKDETAILED_PRESENT_CREATED_AT (1u << 1)
#define AK_EFIX_TASKDETAILED_PRESENT_SUBMITTED_AT (1u << 2)
#define AK_EFIX_TASKDETAILED_PRESENT_STARTED_AT (1u << 3)
#define AK_EFIX_TASKDETAILED_PRESENT_ENDED_AT (1u << 4)
#define AK_EFIX_TASKDETAILED_PRESENT_POD_TTL (1u << 5)
#define AK_EFIX_TASKDETAILED_PRESENT_OUTPUT (1u << 6)
#define AK_EFIX_TASKDETAILED_PRESENT_RECEIVED_AT (1u << 7)
#define AK_EFIX_TASKDETAILED_PRESENT_ACQUIRED_AT (1u << 8)
#define AK_EFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION (1u << 9)
#define AK_EFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION (1u << 10)
#define AK_EFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION (1u << 11)
#define AK_EFIX_TASKDETAILED_PRESENT_PROCESSED_AT (1u << 12)
#define AK_EFIX_TASKDETAILED_PRESENT_FETCHED_AT (1u << 13)

/* Decode group for `TaskDetailed`. */
struct ak_dfix_TaskDetailed {
  struct ak_span id;
  struct ak_span session_id;
  struct ak_span owner_pod_id;
  int32_t status;
  struct ak_span status_message;
  struct ak_dfix_TaskOptions options;
  struct ak_dfix_Timestamp created_at;
  struct ak_dfix_Timestamp submitted_at;
  struct ak_dfix_Timestamp started_at;
  struct ak_dfix_Timestamp ended_at;
  struct ak_dfix_Timestamp pod_ttl;
  struct ak_dfix_TaskOutput output;
  struct ak_span pod_hostname;
  struct ak_dfix_Timestamp received_at;
  struct ak_dfix_Timestamp acquired_at;
  struct ak_dfix_Duration creation_to_end_duration;
  struct ak_dfix_Duration processing_to_end_duration;
  struct ak_span initial_task_id;
  struct ak_dfix_Duration received_to_end_duration;
  struct ak_dfix_Timestamp processed_at;
  struct ak_dfix_Timestamp fetched_at;
  struct ak_span payload_id;
  struct ak_span created_by;
  uint32_t presence;
};
#define AK_DFIX_TASKDETAILED_PRESENT_OPTIONS (1u << 0)
#define AK_DFIX_TASKDETAILED_PRESENT_CREATED_AT (1u << 1)
#define AK_DFIX_TASKDETAILED_PRESENT_SUBMITTED_AT (1u << 2)
#define AK_DFIX_TASKDETAILED_PRESENT_STARTED_AT (1u << 3)
#define AK_DFIX_TASKDETAILED_PRESENT_ENDED_AT (1u << 4)
#define AK_DFIX_TASKDETAILED_PRESENT_POD_TTL (1u << 5)
#define AK_DFIX_TASKDETAILED_PRESENT_OUTPUT (1u << 6)
#define AK_DFIX_TASKDETAILED_PRESENT_RECEIVED_AT (1u << 7)
#define AK_DFIX_TASKDETAILED_PRESENT_ACQUIRED_AT (1u << 8)
#define AK_DFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION (1u << 9)
#define AK_DFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION (1u << 10)
#define AK_DFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION (1u << 11)
#define AK_DFIX_TASKDETAILED_PRESENT_PROCESSED_AT (1u << 12)
#define AK_DFIX_TASKDETAILED_PRESENT_FETCHED_AT (1u << 13)

/* Encode group for `TaskDetailed`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskDetailed {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_str owner_pod_id;
  int32_t status;
  struct ak_str status_message;
  struct ak_ufix_TaskOptions options;
  struct ak_ufix_Timestamp created_at;
  struct ak_ufix_Timestamp submitted_at;
  struct ak_ufix_Timestamp started_at;
  struct ak_ufix_Timestamp ended_at;
  struct ak_ufix_Timestamp pod_ttl;
  struct ak_ufix_TaskOutput output;
  struct ak_str pod_hostname;
  struct ak_ufix_Timestamp received_at;
  struct ak_ufix_Timestamp acquired_at;
  struct ak_ufix_Duration creation_to_end_duration;
  struct ak_ufix_Duration processing_to_end_duration;
  struct ak_str initial_task_id;
  struct ak_ufix_Duration received_to_end_duration;
  struct ak_ufix_Timestamp processed_at;
  struct ak_ufix_Timestamp fetched_at;
  struct ak_str payload_id;
  struct ak_str created_by;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_TASKDETAILED_PRESENT_OPTIONS (1u << 0)
#define AK_UFIX_TASKDETAILED_PRESENT_CREATED_AT (1u << 1)
#define AK_UFIX_TASKDETAILED_PRESENT_SUBMITTED_AT (1u << 2)
#define AK_UFIX_TASKDETAILED_PRESENT_STARTED_AT (1u << 3)
#define AK_UFIX_TASKDETAILED_PRESENT_ENDED_AT (1u << 4)
#define AK_UFIX_TASKDETAILED_PRESENT_POD_TTL (1u << 5)
#define AK_UFIX_TASKDETAILED_PRESENT_OUTPUT (1u << 6)
#define AK_UFIX_TASKDETAILED_PRESENT_RECEIVED_AT (1u << 7)
#define AK_UFIX_TASKDETAILED_PRESENT_ACQUIRED_AT (1u << 8)
#define AK_UFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION (1u << 9)
#define AK_UFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION (1u << 10)
#define AK_UFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION (1u << 11)
#define AK_UFIX_TASKDETAILED_PRESENT_PROCESSED_AT (1u << 12)
#define AK_UFIX_TASKDETAILED_PRESENT_FETCHED_AT (1u << 13)

/* Encode group for `TaskSummary`. */
struct ak_efix_TaskSummary {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_efix_TaskOptions options;
  int32_t status;
  struct ak_efix_Timestamp created_at;
  struct ak_str error;
  struct ak_str status_message;
  int64_t count_data_dependencies;
  uint32_t presence;
};
#define AK_EFIX_TASKSUMMARY_PRESENT_OPTIONS (1u << 0)
#define AK_EFIX_TASKSUMMARY_PRESENT_CREATED_AT (1u << 1)

/* Decode group for `TaskSummary`. */
struct ak_dfix_TaskSummary {
  struct ak_span id;
  struct ak_span session_id;
  struct ak_dfix_TaskOptions options;
  int32_t status;
  struct ak_dfix_Timestamp created_at;
  struct ak_span error;
  struct ak_span status_message;
  int64_t count_data_dependencies;
  uint32_t presence;
};
#define AK_DFIX_TASKSUMMARY_PRESENT_OPTIONS (1u << 0)
#define AK_DFIX_TASKSUMMARY_PRESENT_CREATED_AT (1u << 1)

/* Encode group for `TaskSummary`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_TaskSummary {
  struct ak_str id;
  struct ak_str session_id;
  struct ak_ufix_TaskOptions options;
  int32_t status;
  struct ak_ufix_Timestamp created_at;
  struct ak_str error;
  struct ak_str status_message;
  int64_t count_data_dependencies;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_TASKSUMMARY_PRESENT_OPTIONS (1u << 0)
#define AK_UFIX_TASKSUMMARY_PRESENT_CREATED_AT (1u << 1)

/* Encode group for `Empty`. */
struct ak_efix_Empty {
  uint32_t presence;
};

/* Decode group for `Empty`. */
struct ak_dfix_Empty {
  uint32_t presence;
};

/* Encode group for `Empty`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Empty {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Probe`. */
struct ak_efix_Probe {
  struct ak_str id;
  int32_t opt_count;
  struct ak_str opt_label;
  uint8_t opt_flag;
  uint32_t body_case;
  int64_t body_as_int;
  struct ak_str body_as_text;
  struct ak_str body_as_blob;
  struct ak_efix_Timestamp body_as_stamp;
  struct ak_efix_Empty body_as_nothing;
  uint32_t presence;
};
#define AK_EFIX_PROBE_PRESENT_OPT_COUNT (1u << 0)
#define AK_EFIX_PROBE_PRESENT_OPT_LABEL (1u << 1)
#define AK_EFIX_PROBE_PRESENT_OPT_FLAG (1u << 2)

/* Decode group for `Probe`. */
struct ak_dfix_Probe {
  struct ak_span id;
  int32_t opt_count;
  struct ak_span opt_label;
  uint8_t opt_flag;
  uint32_t body_case;
  int64_t body_as_int;
  struct ak_span body_as_text;
  struct ak_span body_as_blob;
  struct ak_dfix_Timestamp body_as_stamp;
  struct ak_dfix_Empty body_as_nothing;
  uint32_t presence;
};
#define AK_DFIX_PROBE_PRESENT_OPT_COUNT (1u << 0)
#define AK_DFIX_PROBE_PRESENT_OPT_LABEL (1u << 1)
#define AK_DFIX_PROBE_PRESENT_OPT_FLAG (1u << 2)

/* Encode group for `Probe`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Probe {
  struct ak_str id;
  int32_t opt_count;
  struct ak_str opt_label;
  uint8_t opt_flag;
  uint32_t body_case;
  int64_t body_as_int;
  struct ak_str body_as_text;
  struct ak_str body_as_blob;
  struct ak_ufix_Timestamp body_as_stamp;
  struct ak_ufix_Empty body_as_nothing;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_PROBE_PRESENT_OPT_COUNT (1u << 0)
#define AK_UFIX_PROBE_PRESENT_OPT_LABEL (1u << 1)
#define AK_UFIX_PROBE_PRESENT_OPT_FLAG (1u << 2)

/* Encode group for `UploadResultData`. */
struct ak_efix_UploadResultData {
  struct ak_str session_id;
  struct ak_str result_id;
  struct ak_str data_chunk;
  uint32_t presence;
};

/* Decode group for `UploadResultData`. */
struct ak_dfix_UploadResultData {
  struct ak_span session_id;
  struct ak_span result_id;
  struct ak_span data_chunk;
  uint32_t presence;
};

/* Encode group for `UploadResultData`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_UploadResultData {
  struct ak_str session_id;
  struct ak_str result_id;
  struct ak_str data_chunk;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `MetricsBatch`. */
struct ak_efix_MetricsBatch {
  struct ak_str id;
  uint32_t presence;
};

/* Decode group for `MetricsBatch`. */
struct ak_dfix_MetricsBatch {
  struct ak_span id;
  uint32_t presence;
};

/* Encode group for `MetricsBatch`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_MetricsBatch {
  struct ak_str id;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `Pair`. */
struct ak_efix_Pair {
  struct ak_str key;
  int32_t value;
  uint32_t presence;
};

/* Decode group for `Pair`. */
struct ak_dfix_Pair {
  struct ak_span key;
  int32_t value;
  uint32_t presence;
};

/* Encode group for `Pair`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_Pair {
  struct ak_str key;
  int32_t value;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListResultsResponse`. */
struct ak_efix_ListResultsResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Decode group for `ListResultsResponse`. */
struct ak_dfix_ListResultsResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Encode group for `ListResultsResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListResultsResponse {
  int32_t page;
  int32_t total;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListTasksDetailedResponse`. */
struct ak_efix_ListTasksDetailedResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Decode group for `ListTasksDetailedResponse`. */
struct ak_dfix_ListTasksDetailedResponse {
  int32_t page;
  int32_t total;
  uint32_t presence;
};

/* Encode group for `ListTasksDetailedResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListTasksDetailedResponse {
  int32_t page;
  int32_t total;
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListTaskSummaryResponse`. */
struct ak_efix_ListTaskSummaryResponse {
  uint32_t presence;
};

/* Decode group for `ListTaskSummaryResponse`. */
struct ak_dfix_ListTaskSummaryResponse {
  uint32_t presence;
};

/* Encode group for `ListTaskSummaryResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListTaskSummaryResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListProbeResponse`. */
struct ak_efix_ListProbeResponse {
  uint32_t presence;
};

/* Decode group for `ListProbeResponse`. */
struct ak_dfix_ListProbeResponse {
  uint32_t presence;
};

/* Encode group for `ListProbeResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListProbeResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `ListMetricsResponse`. */
struct ak_efix_ListMetricsResponse {
  uint32_t presence;
};

/* Decode group for `ListMetricsResponse`. */
struct ak_dfix_ListMetricsResponse {
  uint32_t presence;
};

/* Encode group for `ListMetricsResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_ListMetricsResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode group for `UploadResultDataMessage`. */
struct ak_efix_UploadResultDataMessage {
  struct ak_efix_UploadResultData upload;
  uint32_t presence;
};
#define AK_EFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD (1u << 0)

/* Decode group for `UploadResultDataMessage`. */
struct ak_dfix_UploadResultDataMessage {
  struct ak_dfix_UploadResultData upload;
  uint32_t presence;
};
#define AK_DFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD (1u << 0)

/* Encode group for `UploadResultDataMessage`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_UploadResultDataMessage {
  struct ak_ufix_UploadResultData upload;
  struct ak_blob unknown;
  uint32_t presence;
};
#define AK_UFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD (1u << 0)

/* Encode group for `DualResponse`. */
struct ak_efix_DualResponse {
  uint32_t presence;
};

/* Decode group for `DualResponse`. */
struct ak_dfix_DualResponse {
  uint32_t presence;
};

/* Encode group for `DualResponse`.  With the unknown-field bag (decision 11 candidate). */
struct ak_ufix_DualResponse {
  struct ak_blob unknown;
  uint32_t presence;
};

/* Encode vtable for `ListResultsResponse`. One slot per field that could not ride in the group. */
struct ak_evt_ListResultsResponse {
  ak_loop_f loop_results;
};

/* Decode vtable for `ListResultsResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListResultsResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListResultsResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_results;
  void (*add_results)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_ResultRaw *, int32_t);
};

/* Encode vtable for `ListTasksDetailedResponse`. One slot per field that could not ride in the group. */
struct ak_evt_ListTasksDetailedResponse {
  ak_loop_f loop_tasks;
  const struct ak_evt_TaskDetailed *elem_tasks;
};

/* Decode vtable for `ListTasksDetailedResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListTasksDetailedResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListTasksDetailedResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_tasks;
  int64_t (*new_tasks)(ak_dec_ctx *, void *);
  void (*apply_tasks)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskDetailed *);
  void (*add_tasks_parent_task_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_data_dependencies)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_expected_output_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_retry_of_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_tasks_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `ListProbeResponse`. One slot per field that could not ride in the group. */
struct ak_evt_ListProbeResponse {
  ak_loop_f loop_probes;
};

/* Decode vtable for `ListProbeResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListProbeResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListProbeResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_probes;
  void (*add_probes)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_Probe *, int32_t);
};

/* Encode vtable for `ListTaskSummaryResponse`. One slot per field that could not ride in the group. */
struct ak_evt_ListTaskSummaryResponse {
  ak_loop_f loop_tasks;
  const struct ak_evt_TaskSummary *elem_tasks;
};

/* Decode vtable for `ListTaskSummaryResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListTaskSummaryResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListTaskSummaryResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_tasks;
  int64_t (*new_tasks)(ak_dec_ctx *, void *);
  void (*apply_tasks)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskSummary *);
  void (*add_tasks_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `UploadResultDataMessage`. Empty: nothing in this message needs a call. */
struct ak_evt_UploadResultDataMessage {
  /* Reserved: an empty struct has no defined size in C. */
  const void *_reserved;
};

/* Decode vtable for `UploadResultDataMessage` (the push family, ABI v1 section 7.1). */
struct ak_dvt_UploadResultDataMessage {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_UploadResultDataMessage *);
  ak_unk_f unknown;
};

/* Encode vtable for `ListMetricsResponse`. One slot per field that could not ride in the group. */
struct ak_evt_ListMetricsResponse {
  ak_loop_f loop_batches;
  const struct ak_evt_MetricsBatch *elem_batches;
};

/* Decode vtable for `ListMetricsResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ListMetricsResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ListMetricsResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_batches;
  int64_t (*new_batches)(ak_dec_ctx *, void *);
  void (*apply_batches)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_MetricsBatch *);
  void (*add_batches_ticks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  void (*add_batches_values)(ak_dec_ctx *, void *, int64_t, const double *, int32_t);
  void (*add_batches_codes)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
  void (*add_batches_flags)(ak_dec_ctx *, void *, int64_t, const uint8_t *, int32_t);
  void (*add_batches_statuses)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
};

/* Encode vtable for `DualResponse`. One slot per field that could not ride in the group. */
struct ak_evt_DualResponse {
  ak_loop_f loop_left;
  ak_loop_f loop_right;
};

/* Decode vtable for `DualResponse` (the push family, ABI v1 section 7.1). */
struct ak_dvt_DualResponse {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_DualResponse *);
  ak_unk_f unknown;
  ak_unk_f unk_left;
  void (*add_left)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_Pair *, int32_t);
  ak_unk_f unk_right;
  void (*add_right)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_Pair *, int32_t);
};

/* Encode vtable for `TaskOptionsOptionsEntry`. Empty: nothing in this message needs a call. */
struct ak_evt_TaskOptionsOptionsEntry {
  /* Reserved: an empty struct has no defined size in C. */
  const void *_reserved;
};

/* Decode vtable for `TaskOptionsOptionsEntry` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskOptionsOptionsEntry {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskOptionsOptionsEntry *);
  ak_unk_f unknown;
};

/* Encode vtable for `ResultRaw`. Empty: nothing in this message needs a call. */
struct ak_evt_ResultRaw {
  /* Reserved: an empty struct has no defined size in C. */
  const void *_reserved;
};

/* Decode vtable for `ResultRaw` (the push family, ABI v1 section 7.1). */
struct ak_dvt_ResultRaw {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_ResultRaw *);
  ak_unk_f unknown;
};

/* Encode vtable for `TaskDetailed`. One slot per field that could not ride in the group. */
struct ak_evt_TaskDetailed {
  ak_loop_f loop_parent_task_ids;
  ak_loop_f loop_data_dependencies;
  ak_loop_f loop_expected_output_ids;
  ak_loop_f loop_retry_of_ids;
  ak_loop_f loop_options_options;
};

/* Decode vtable for `TaskDetailed` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskDetailed {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskDetailed *);
  ak_unk_f unknown;
  void (*add_parent_task_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_data_dependencies)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_expected_output_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  void (*add_retry_of_ids)(ak_dec_ctx *, void *, int64_t, const struct ak_span *, int32_t);
  ak_unk_f unk_options_options;
  void (*add_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `TaskSummary`. One slot per field that could not ride in the group. */
struct ak_evt_TaskSummary {
  ak_loop_f loop_options_options;
};

/* Decode vtable for `TaskSummary` (the push family, ABI v1 section 7.1). */
struct ak_dvt_TaskSummary {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_TaskSummary *);
  ak_unk_f unknown;
  ak_unk_f unk_options_options;
  void (*add_options_options)(ak_dec_ctx *, void *, int64_t, const struct ak_dfix_TaskOptionsOptionsEntry *, int32_t);
};

/* Encode vtable for `Probe`. Empty: nothing in this message needs a call. */
struct ak_evt_Probe {
  /* Reserved: an empty struct has no defined size in C. */
  const void *_reserved;
};

/* Decode vtable for `Probe` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Probe {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Probe *);
  ak_unk_f unknown;
};

/* Encode vtable for `MetricsBatch`. One slot per field that could not ride in the group. */
struct ak_evt_MetricsBatch {
  ak_loop_f loop_ticks;
  ak_loop_f loop_values;
  ak_loop_f loop_codes;
  ak_loop_f loop_flags;
  ak_loop_f loop_statuses;
};

/* Decode vtable for `MetricsBatch` (the push family, ABI v1 section 7.1). */
struct ak_dvt_MetricsBatch {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_MetricsBatch *);
  ak_unk_f unknown;
  void (*add_ticks)(ak_dec_ctx *, void *, int64_t, const int64_t *, int32_t);
  void (*add_values)(ak_dec_ctx *, void *, int64_t, const double *, int32_t);
  void (*add_codes)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
  void (*add_flags)(ak_dec_ctx *, void *, int64_t, const uint8_t *, int32_t);
  void (*add_statuses)(ak_dec_ctx *, void *, int64_t, const int32_t *, int32_t);
};

/* Encode vtable for `Pair`. Empty: nothing in this message needs a call. */
struct ak_evt_Pair {
  /* Reserved: an empty struct has no defined size in C. */
  const void *_reserved;
};

/* Decode vtable for `Pair` (the push family, ABI v1 section 7.1). */
struct ak_dvt_Pair {
  void (*apply)(ak_dec_ctx *, void *, const struct ak_dfix_Pair *);
  ak_unk_f unknown;
};

/* ABI v1 section 6: what the host calls are PLAIN EXPORTS, not a table. */
intptr_t ak_encode_ListResultsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListResultsResponse *vt, const struct ak_efix_ListResultsResponse *fix);
intptr_t ak_uencode_ListResultsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListResultsResponse *vt, const struct ak_ufix_ListResultsResponse *fix);
int32_t ak_decode_ListResultsResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListResultsResponse *vt);
intptr_t ak_encode_ListTasksDetailedResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTasksDetailedResponse *vt, const struct ak_efix_ListTasksDetailedResponse *fix);
intptr_t ak_uencode_ListTasksDetailedResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTasksDetailedResponse *vt, const struct ak_ufix_ListTasksDetailedResponse *fix);
int32_t ak_decode_ListTasksDetailedResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListTasksDetailedResponse *vt);
intptr_t ak_encode_ListProbeResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListProbeResponse *vt, const struct ak_efix_ListProbeResponse *fix);
intptr_t ak_uencode_ListProbeResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListProbeResponse *vt, const struct ak_ufix_ListProbeResponse *fix);
int32_t ak_decode_ListProbeResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListProbeResponse *vt);
intptr_t ak_encode_ListTaskSummaryResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTaskSummaryResponse *vt, const struct ak_efix_ListTaskSummaryResponse *fix);
intptr_t ak_uencode_ListTaskSummaryResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListTaskSummaryResponse *vt, const struct ak_ufix_ListTaskSummaryResponse *fix);
int32_t ak_decode_ListTaskSummaryResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListTaskSummaryResponse *vt);
intptr_t ak_encode_UploadResultDataMessage(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_UploadResultDataMessage *vt, const struct ak_efix_UploadResultDataMessage *fix, const uint8_t *direct, size_t direct_len);
intptr_t ak_uencode_UploadResultDataMessage(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_UploadResultDataMessage *vt, const struct ak_ufix_UploadResultDataMessage *fix, const uint8_t *direct, size_t direct_len);
int32_t ak_decode_UploadResultDataMessage(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_UploadResultDataMessage *vt);
intptr_t ak_encode_ListMetricsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListMetricsResponse *vt, const struct ak_efix_ListMetricsResponse *fix);
intptr_t ak_uencode_ListMetricsResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_ListMetricsResponse *vt, const struct ak_ufix_ListMetricsResponse *fix);
int32_t ak_decode_ListMetricsResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_ListMetricsResponse *vt);
intptr_t ak_encode_DualResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_DualResponse *vt, const struct ak_efix_DualResponse *fix);
intptr_t ak_uencode_DualResponse(const void *obj, ak_enc_ctx *ctx, const struct ak_evt_DualResponse *vt, const struct ak_ufix_DualResponse *fix);
int32_t ak_decode_DualResponse(ak_dec_ctx *ctx, void *obj, const uint8_t *buf, size_t len, const struct ak_dvt_DualResponse *vt);
int32_t ak_elemu_MetricsBatch(ak_enc_ctx *ctx, const struct ak_efix_MetricsBatch *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_MetricsBatch(ak_enc_ctx *ctx, const struct ak_ufix_MetricsBatch *elems, int32_t n, int64_t tok0);
int32_t ak_elem_Pair(ak_enc_ctx *ctx, const struct ak_efix_Pair *elems, int32_t n);
int32_t ak_uelem_Pair(ak_enc_ctx *ctx, const struct ak_ufix_Pair *elems, int32_t n);
int32_t ak_elem_Probe(ak_enc_ctx *ctx, const struct ak_efix_Probe *elems, int32_t n);
int32_t ak_uelem_Probe(ak_enc_ctx *ctx, const struct ak_ufix_Probe *elems, int32_t n);
int32_t ak_elem_ResultRaw(ak_enc_ctx *ctx, const struct ak_efix_ResultRaw *elems, int32_t n);
int32_t ak_uelem_ResultRaw(ak_enc_ctx *ctx, const struct ak_ufix_ResultRaw *elems, int32_t n);
int32_t ak_elemu_TaskDetailed(ak_enc_ctx *ctx, const struct ak_efix_TaskDetailed *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_TaskDetailed(ak_enc_ctx *ctx, const struct ak_ufix_TaskDetailed *elems, int32_t n, int64_t tok0);
int32_t ak_elem_TaskOptionsOptionsEntry(ak_enc_ctx *ctx, const struct ak_efix_TaskOptionsOptionsEntry *elems, int32_t n);
int32_t ak_uelem_TaskOptionsOptionsEntry(ak_enc_ctx *ctx, const struct ak_ufix_TaskOptionsOptionsEntry *elems, int32_t n);
int32_t ak_elemu_TaskSummary(ak_enc_ctx *ctx, const struct ak_efix_TaskSummary *elems, int32_t n, int64_t tok0);
int32_t ak_uelemu_TaskSummary(ak_enc_ctx *ctx, const struct ak_ufix_TaskSummary *elems, int32_t n, int64_t tok0);
int32_t ak_blob_run(ak_enc_ctx *ctx, const struct ak_str *elems, int32_t n);
int32_t ak_run_i32(ak_enc_ctx *ctx, const int32_t *p, size_t n);
int32_t ak_run_i64(ak_enc_ctx *ctx, const int64_t *p, size_t n);
int32_t ak_run_f64(ak_enc_ctx *ctx, const double *p, size_t n);
int32_t ak_run_u8(ak_enc_ctx *ctx, const uint8_t *p, size_t n);

/* ---- the fixed exports (sections 3, 4, 5) ---------------------------------------- */
uint32_t ak_abi_version(void);
ak_enc_ctx *ak_enc_ctx_new(void);
void ak_enc_ctx_free(ak_enc_ctx *);
void ak_enc_reset(ak_enc_ctx *);
int32_t ak_enc_take(ak_enc_ctx *, const uint8_t **ptr, size_t *len);
int32_t ak_enc_err(const ak_enc_ctx *);
ak_dec_ctx *ak_dec_ctx_new(void);
void ak_dec_ctx_free(ak_dec_ctx *);
void ak_fail(void *ctx, int32_t code, const uint8_t *msg, uint32_t msg_len);
int32_t ak_dec_err(const ak_dec_ctx *);
void ak_dec_err_reset(ak_dec_ctx *);
ak_transcode_fn ak_tc_utf8(void);
ak_transcode_fn ak_tc_utf8_trusted(void);
ak_transcode_fn ak_tc_utf8_simd(void);
ak_transcode_fn ak_tc_bytes(void);

/* README R5: counted in the CORE, so a call the optimiser removed is not counted. */
struct AkCounters {
  uint64_t forward, reverse, transcode, prefix_moves, prefix_bytes, grows;
};
void ak_enc_counters(const ak_enc_ctx *, struct AkCounters *out);
/* Counting build only: the HOST reports a reverse crossing the core cannot see, because
 * `ak_str.tc` may point into either image and the counter lives in the core. */
void ak_enc_count_reverse(ak_enc_ctx *);
void ak_enc_counters_reset(ak_enc_ctx *);
void ak_dec_counters(const ak_dec_ctx *, struct AkCounters *out);
void ak_dec_counters_reset(ak_dec_ctx *);
size_t ak_enc_site_moves(const ak_enc_ctx *, uint32_t *out, size_t cap);

/* The boundary priced on its own, in the same process and build as the arms. */
uint64_t ak_noop(uint64_t x);
uint64_t ak_noop_reverse(uint64_t (*f)(uint64_t), uint64_t x);

/* ABI v1 section 10 and obligation 12.3: group layouts asserted, not assumed.
 * A disagreement between #[repr(C)] and this header otherwise surfaces as a
 * wrong VALUE in a field. Asserted at compile time on the host side here, and
 * re-asserted from the Rust side at run time by ak_layout_check(). */
#ifdef __cplusplus
#define AK_SASSERT(c, m) static_assert(c, m)
#else
#define AK_SASSERT(c, m) typedef char ak_sa_##__LINE__[(c) ? 1 : -1]
#endif

/* ---- section 9: the RPC half's client options -------------------------------
 * Rendered from `ak_client_opts` in poc/codec/crates/ak-abi/src/lib.rs, which the
 * core asserts field by field against the struct it reads (ak-core/src/rpc.rs).
 * Never hand-declare it in a host: R-D2 was a 3-field copy of a 6-field struct. */
struct ak_client_opts {
  uint32_t stream_window;
  uint32_t connection_window;
  int32_t adaptive_window;
  uint32_t max_recv_message;
  uint32_t max_send_message;
  int32_t tcp_nagle;
};
#define AK_CLIENT_OPTS_FIELDS 6
AK_SASSERT(sizeof(struct ak_client_opts) == 24, "sizeof ak_client_opts");
AK_SASSERT(offsetof(struct ak_client_opts, stream_window) == 0, "ak_client_opts.stream_window");
AK_SASSERT(offsetof(struct ak_client_opts, connection_window) == 4, "ak_client_opts.connection_window");
AK_SASSERT(offsetof(struct ak_client_opts, adaptive_window) == 8, "ak_client_opts.adaptive_window");
AK_SASSERT(offsetof(struct ak_client_opts, max_recv_message) == 12, "ak_client_opts.max_recv_message");
AK_SASSERT(offsetof(struct ak_client_opts, max_send_message) == 16, "ak_client_opts.max_send_message");
AK_SASSERT(offsetof(struct ak_client_opts, tcp_nagle) == 20, "ak_client_opts.tcp_nagle");

/* Number of (struct, member) layout facts this header pins. */
#define AK_LAYOUT_FACTS 380

/* The core writes its own view of the same facts here; the host compares. */
size_t ak_layout_facts(uint32_t *out, size_t cap);

#ifdef __cplusplus
} /* extern "C" */
#endif
#endif /* AK_ABI_H */
