// @generated by ffi/poc/codec/gen/java_rcodec.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

import ak.Dec;
import ak.Enc;

/** Arm `R` (unknown fields DROP): the generated pure-Java codec, rendered from the
 *  plans of poc/codec/gen/plan.py -- README R3's no-boundary control and section 13
 *  outcome 2's fallback architecture. An error is a {@link Dec.Malformed} or an
 *  {@link Enc.Refused}, and nothing is returned after it (plan rule, R-G6). */
public final class Codec {
  private Codec() {}

  /** One learned length-prefix width per site (ABI v1 section 6). */
  public static final int SITES = 47;
  /** The plan's recursion limit (Options.recursion_limit). */
  public static final int LIMIT = 100;
  /** The plan's MAX_FIELD_NUMBER and GROUP_DEPTH_LIMIT, handed to `Dec.skip`, whose
   *  group skip applies them to every key inside a group (D38). */
  public static final long MAX_FIELD_NUMBER = 536870911L;
  public static final int GROUP_DEPTH_LIMIT = 100;
  /** The plan's unknown-field mode and UTF-8 policy, for a log to name. */
  public static final String UNKNOWN_FIELDS = "drop";
  public static final String UTF8_POLICY = "reject";

  // A batched `add` may be called more than once per field (ABI v1 7.4), so the binding
  // APPENDS and never sizes to the count it was handed; this arm does the same, so the two
  // differ in where the bytes are parsed and in nothing else.
  static int[] append(int[] a, int[] b, int n) {
    int[] out = java.util.Arrays.copyOf(a, a.length + n);
    System.arraycopy(b, 0, out, a.length, n);
    return out;
  }

  static long[] append(long[] a, long[] b, int n) {
    long[] out = java.util.Arrays.copyOf(a, a.length + n);
    System.arraycopy(b, 0, out, a.length, n);
    return out;
  }

  static double[] append(double[] a, double[] b, int n) {
    double[] out = java.util.Arrays.copyOf(a, a.length + n);
    System.arraycopy(b, 0, out, a.length, n);
    return out;
  }

  static boolean[] append(boolean[] a, boolean[] b, int n) {
    boolean[] out = java.util.Arrays.copyOf(a, a.length + n);
    System.arraycopy(b, 0, out, a.length, n);
    return out;
  }

  static final byte[] EMPTY = new byte[0];


  /** plan ENCODE RULES (WP5 step 6): map entries in ascending order of the key's UTF-8
   *  bytes, i.e. code-point order. A {@code TreeMap<String, ...>} iterates in UTF-16 code
   *  unit order, which differs for a key with a supplementary character, so the entries
   *  are handed over re-sorted. (A {@code Utf8View} key already compares by bytes.) */
  public static <V> java.util.List<java.util.Map.Entry<String, V>> utf8Sorted(java.util.Map<String, V> m) {
    java.util.ArrayList<java.util.Map.Entry<String, V>> l = new java.util.ArrayList<java.util.Map.Entry<String, V>>(m.entrySet());
    if (l.size() > 1) {
      java.util.Collections.sort(l, new java.util.Comparator<java.util.Map.Entry<String, V>>() {
        public int compare(java.util.Map.Entry<String, V> a, java.util.Map.Entry<String, V> b) {
          return cmpUtf8(a.getKey(), b.getKey());
        }
      });
    }
    return l;
  }

  public static int cmpUtf8(String a, String b) {
    int i = 0, j = 0;
    while (i < a.length() && j < b.length()) {
      int x = a.codePointAt(i), y = b.codePointAt(j);
      if (x != y) return x < y ? -1 : 1;
      i += Character.charCount(x);
      j += Character.charCount(y);
    }
    return (i < a.length() ? 1 : 0) - (j < b.length() ? 1 : 0);
  }


  static void encTimestamp(Enc e, Timestamp o) {
    if (o.seconds != 0) e.varintField(1, o.seconds);
    if (o.nanos != 0) e.varintField(2, (long) (o.nanos));
  }

  static void encDuration(Enc e, Duration o) {
    if (o.seconds != 0) e.varintField(1, o.seconds);
    if (o.nanos != 0) e.varintField(2, (long) (o.nanos));
  }

  static void encResultRaw(Enc e, ResultRaw o) {
    if (!o.session_id.isEmpty()) e.stringField(1, o.session_id);
    if (!o.name.isEmpty()) e.stringField(2, o.name);
    if (!o.owner_task_id.isEmpty()) e.stringField(3, o.owner_task_id);
    if (o.status != 0) e.varintField(4, (long) (o.status));
    if (o.created_at != null) { long mk = e.begin(5, 0); encTimestamp(e, o.created_at); e.end(mk); }
    if (o.completed_at != null) { long mk = e.begin(6, 1); encTimestamp(e, o.completed_at); e.end(mk); }
    if (!o.result_id.isEmpty()) e.stringField(8, o.result_id);
    if (o.size != 0) e.varintField(9, o.size);
    if (!o.created_by.isEmpty()) e.stringField(10, o.created_by);
    if (o.opaque_id.length > 0) e.blobField(11, o.opaque_id);
    if (o.manual_deletion) e.varintField(12, (o.manual_deletion) ? 1 : 0);
  }

  static void encTaskOptions(Enc e, TaskOptions o) {
    for (java.util.Map.Entry<String, String> en : utf8Sorted(o.options)) {
      long mk = e.begin(1, 2);
      if (!en.getKey().isEmpty()) e.stringField(1, en.getKey());
      if (!en.getValue().isEmpty()) e.stringField(2, en.getValue());
      e.end(mk);
    }
    if (o.max_duration != null) { long mk = e.begin(2, 3); encDuration(e, o.max_duration); e.end(mk); }
    if (o.max_retries != 0) e.varintField(3, (long) (o.max_retries));
    if (o.priority != 0) e.varintField(4, (long) (o.priority));
    if (!o.partition_id.isEmpty()) e.stringField(5, o.partition_id);
    if (!o.application_name.isEmpty()) e.stringField(6, o.application_name);
    if (!o.application_version.isEmpty()) e.stringField(7, o.application_version);
    if (!o.application_namespace.isEmpty()) e.stringField(8, o.application_namespace);
    if (!o.application_service.isEmpty()) e.stringField(9, o.application_service);
    if (!o.engine_type.isEmpty()) e.stringField(10, o.engine_type);
  }

  static void encTaskOutput(Enc e, TaskOutput o) {
    if (o.success) e.varintField(1, (o.success) ? 1 : 0);
    if (!o.error.isEmpty()) e.stringField(2, o.error);
  }

  static void encTaskDetailed(Enc e, TaskDetailed o) {
    if (!o.id.isEmpty()) e.stringField(1, o.id);
    if (!o.session_id.isEmpty()) e.stringField(2, o.session_id);
    if (!o.owner_pod_id.isEmpty()) e.stringField(3, o.owner_pod_id);
    for (String x : o.parent_task_ids) e.stringField(4, x);
    for (String x : o.data_dependencies) e.stringField(5, x);
    for (String x : o.expected_output_ids) e.stringField(6, x);
    for (String x : o.retry_of_ids) e.stringField(7, x);
    if (o.status != 0) e.varintField(8, (long) (o.status));
    if (!o.status_message.isEmpty()) e.stringField(9, o.status_message);
    if (o.options != null) { long mk = e.begin(10, 4); encTaskOptions(e, o.options); e.end(mk); }
    if (o.created_at != null) { long mk = e.begin(11, 5); encTimestamp(e, o.created_at); e.end(mk); }
    if (o.submitted_at != null) { long mk = e.begin(12, 6); encTimestamp(e, o.submitted_at); e.end(mk); }
    if (o.started_at != null) { long mk = e.begin(13, 7); encTimestamp(e, o.started_at); e.end(mk); }
    if (o.ended_at != null) { long mk = e.begin(14, 8); encTimestamp(e, o.ended_at); e.end(mk); }
    if (o.pod_ttl != null) { long mk = e.begin(15, 9); encTimestamp(e, o.pod_ttl); e.end(mk); }
    if (o.output != null) { long mk = e.begin(16, 10); encTaskOutput(e, o.output); e.end(mk); }
    if (!o.pod_hostname.isEmpty()) e.stringField(17, o.pod_hostname);
    if (o.received_at != null) { long mk = e.begin(18, 11); encTimestamp(e, o.received_at); e.end(mk); }
    if (o.acquired_at != null) { long mk = e.begin(19, 12); encTimestamp(e, o.acquired_at); e.end(mk); }
    if (o.creation_to_end_duration != null) { long mk = e.begin(20, 13); encDuration(e, o.creation_to_end_duration); e.end(mk); }
    if (o.processing_to_end_duration != null) { long mk = e.begin(21, 14); encDuration(e, o.processing_to_end_duration); e.end(mk); }
    if (!o.initial_task_id.isEmpty()) e.stringField(22, o.initial_task_id);
    if (o.received_to_end_duration != null) { long mk = e.begin(23, 15); encDuration(e, o.received_to_end_duration); e.end(mk); }
    if (o.processed_at != null) { long mk = e.begin(24, 16); encTimestamp(e, o.processed_at); e.end(mk); }
    if (o.fetched_at != null) { long mk = e.begin(25, 17); encTimestamp(e, o.fetched_at); e.end(mk); }
    if (!o.payload_id.isEmpty()) e.stringField(26, o.payload_id);
    if (!o.created_by.isEmpty()) e.stringField(27, o.created_by);
  }

  static void encTaskSummary(Enc e, TaskSummary o) {
    if (!o.id.isEmpty()) e.stringField(1, o.id);
    if (!o.session_id.isEmpty()) e.stringField(2, o.session_id);
    if (o.options != null) { long mk = e.begin(3, 18); encTaskOptions(e, o.options); e.end(mk); }
    if (o.status != 0) e.varintField(4, (long) (o.status));
    if (o.created_at != null) { long mk = e.begin(5, 19); encTimestamp(e, o.created_at); e.end(mk); }
    if (!o.error.isEmpty()) e.stringField(8, o.error);
    if (!o.status_message.isEmpty()) e.stringField(9, o.status_message);
    if (o.count_data_dependencies != 0) e.varintField(11, o.count_data_dependencies);
  }

  static void encProbe(Enc e, Probe o) {
    if (o.body_case != 0 && o.body_case != 10 && o.body_case != 11 && o.body_case != 12 && o.body_case != 13 && o.body_case != 14)
      throw new Enc.Refused(Enc.ERR_ABI, "Probe.body: undeclared oneof case " + o.body_case);
    if (!o.id.isEmpty()) e.stringField(1, o.id);
    if (o.has_opt_count) e.varintField(2, (long) (o.opt_count));
    if (o.opt_label != null) e.stringField(3, o.opt_label);
    if (o.has_opt_flag) e.varintField(4, (o.opt_flag) ? 1 : 0);
    if (o.body_case == Probe.BODY_CASE_AS_INT) e.varintField(10, o.body_as_int);
    if (o.body_case == Probe.BODY_CASE_AS_TEXT) e.stringField(11, (o.body_as_text == null ? "" : o.body_as_text));
    if (o.body_case == Probe.BODY_CASE_AS_BLOB) e.blobField(12, (o.body_as_blob == null ? EMPTY : o.body_as_blob));
    if (o.body_case == Probe.BODY_CASE_AS_STAMP) { long mk = e.begin(13, 20); if (o.body_as_stamp != null) encTimestamp(e, o.body_as_stamp); e.end(mk); }
    if (o.body_case == Probe.BODY_CASE_AS_NOTHING) { long mk = e.begin(14, 21); if (o.body_as_nothing != null) encEmpty(e, o.body_as_nothing); e.end(mk); }
  }

  static void encEmpty(Enc e, Empty o) {
  }

  static void encUploadResultData(Enc e, UploadResultData o) {
    if (!o.session_id.isEmpty()) e.stringField(1, o.session_id);
    if (!o.result_id.isEmpty()) e.stringField(2, o.result_id);
    if (o.data_chunk.length > 0) e.blobField(3, o.data_chunk);
  }

  static void encMetricsBatch(Enc e, MetricsBatch o) {
    if (!o.id.isEmpty()) e.stringField(1, o.id);
    if (o.ticks.length > 0) {
      long mk = e.begin(2, 22);
      for (int i = 0; i < o.ticks.length; i++) e.varint(o.ticks[i]);
      e.end(mk);
    }
    if (o.values.length > 0) {
      long mk = e.begin(3, 23);
      for (int i = 0; i < o.values.length; i++) e.f64(o.values[i]);
      e.end(mk);
    }
    if (o.codes.length > 0) {
      long mk = e.begin(4, 24);
      for (int i = 0; i < o.codes.length; i++) e.varint((long) (o.codes[i]));
      e.end(mk);
    }
    if (o.flags.length > 0) {
      long mk = e.begin(5, 25);
      for (int i = 0; i < o.flags.length; i++) e.varint((o.flags[i]) ? 1 : 0);
      e.end(mk);
    }
    if (o.statuses.length > 0) {
      long mk = e.begin(6, 26);
      for (int i = 0; i < o.statuses.length; i++) e.varint((long) (o.statuses[i]));
      e.end(mk);
    }
  }

  static void encPair(Enc e, Pair o) {
    if (!o.key.isEmpty()) e.stringField(1, o.key);
    if (o.value != 0) e.varintField(2, (long) (o.value));
  }

  static void encListResultsResponse(Enc e, ListResultsResponse o) {
    for (ResultRaw x : o.results) { long mk = e.begin(1, 27); encResultRaw(e, x); e.end(mk); }
    if (o.page != 0) e.varintField(2, (long) (o.page));
    if (o.total != 0) e.varintField(3, (long) (o.total));
  }

  static void encListTasksDetailedResponse(Enc e, ListTasksDetailedResponse o) {
    for (TaskDetailed x : o.tasks) { long mk = e.begin(1, 28); encTaskDetailed(e, x); e.end(mk); }
    if (o.page != 0) e.varintField(2, (long) (o.page));
    if (o.total != 0) e.varintField(3, (long) (o.total));
  }

  static void encListTaskSummaryResponse(Enc e, ListTaskSummaryResponse o) {
    for (TaskSummary x : o.tasks) { long mk = e.begin(1, 29); encTaskSummary(e, x); e.end(mk); }
  }

  static void encListProbeResponse(Enc e, ListProbeResponse o) {
    for (Probe x : o.probes) { long mk = e.begin(1, 30); encProbe(e, x); e.end(mk); }
  }

  static void encListMetricsResponse(Enc e, ListMetricsResponse o) {
    for (MetricsBatch x : o.batches) { long mk = e.begin(1, 31); encMetricsBatch(e, x); e.end(mk); }
  }

  static void encUploadResultDataMessage(Enc e, UploadResultDataMessage o) {
    if (o.upload != null) { long mk = e.begin(1, 32); encUploadResultData(e, o.upload); e.end(mk); }
  }

  static void encDualResponse(Enc e, DualResponse o) {
    for (Pair x : o.left) { long mk = e.begin(1, 33); encPair(e, x); e.end(mk); }
    for (Pair x : o.right) { long mk = e.begin(2, 34); encPair(e, x); e.end(mk); }
  }

  static void encChunkLeaf(Enc e, ChunkLeaf o) {
    if (!o.k.isEmpty()) e.stringField(1, o.k);
    if (o.v != 0) e.varintField(2, (long) (o.v));
  }

  static void encChunkInner(Enc e, ChunkInner o) {
    if (o.marks.length > 0) {
      long mk = e.begin(1, 35);
      for (int i = 0; i < o.marks.length; i++) e.varint(o.marks[i]);
      e.end(mk);
    }
    for (ChunkLeaf x : o.leaves) { long mk = e.begin(2, 36); encChunkLeaf(e, x); e.end(mk); }
  }

  static void encChunkElement(Enc e, ChunkElement o) {
    for (String x : o.labels) e.stringField(1, x);
    for (java.util.Map.Entry<String, String> en : utf8Sorted(o.attrs)) {
      long mk = e.begin(2, 37);
      if (!en.getKey().isEmpty()) e.stringField(1, en.getKey());
      if (!en.getValue().isEmpty()) e.stringField(2, en.getValue());
      e.end(mk);
    }
    if (!o.id.isEmpty()) e.stringField(3, o.id);
    if (o.inner != null) { long mk = e.begin(4, 38); encChunkInner(e, o.inner); e.end(mk); }
  }

  static void encChunkedResponse(Enc e, ChunkedResponse o) {
    for (ChunkElement x : o.items) { long mk = e.begin(7, 39); encChunkElement(e, x); e.end(mk); }
    if (o.page != 0) e.varintField(8, (long) (o.page));
  }

  static void encChunkedResponseWide(Enc e, ChunkedResponseWide o) {
    for (ChunkElement x : o.items) { long mk = e.begin(70000, 40); encChunkElement(e, x); e.end(mk); }
  }

  static void encLeafElement(Enc e, LeafElement o) {
    if (!o.id.isEmpty()) e.stringField(1, o.id);
    if (o.n != 0) e.varintField(2, o.n);
    if (o.stamp != null) { long mk = e.begin(3, 41); encTimestamp(e, o.stamp); e.end(mk); }
  }

  static void encLeafResponse(Enc e, LeafResponse o) {
    for (LeafElement x : o.items) { long mk = e.begin(9, 42); encLeafElement(e, x); e.end(mk); }
  }

  static void encSurrogate(Enc e, Surrogate o) {
    if (!o.text.isEmpty()) e.stringField(1, o.text);
    if (o.nested != null) { long mk = e.begin(2, 43); encSurrogateInner(e, o.nested); e.end(mk); }
    for (java.util.Map.Entry<String, String> en : utf8Sorted(o.attrs)) {
      long mk = e.begin(3, 44);
      if (!en.getKey().isEmpty()) e.stringField(1, en.getKey());
      if (!en.getValue().isEmpty()) e.stringField(2, en.getValue());
      e.end(mk);
    }
    for (String x : o.texts) e.stringField(4, x);
    if (o.raw.length > 0) e.blobField(5, o.raw);
  }

  static void encSurrogateInner(Enc e, SurrogateInner o) {
    if (!o.text.isEmpty()) e.stringField(1, o.text);
  }

  static void encNest(Enc e, Nest o) {
    if (o.child != null) { long mk = e.begin(1, 45); encNest(e, o.child); e.end(mk); }
    if (!o.leaf.isEmpty()) e.stringField(2, o.leaf);
  }

  static void encWireZoo(Enc e, WireZoo o) {
    if (o.v_int32 != 0) e.varintField(1, (long) (o.v_int32));
    if (o.v_int64 != 0) e.varintField(2, o.v_int64);
    if (o.v_bool) e.varintField(3, (o.v_bool) ? 1 : 0);
    if (Double.doubleToRawLongBits(o.v_double) != 0L) e.f64Field(4, o.v_double);
    if (o.v_fixed32 != 0) e.fixed32Field(5, o.v_fixed32);
    if (!o.v_string.isEmpty()) e.stringField(6, o.v_string);
    if (o.v_bytes.length > 0) e.blobField(7, o.v_bytes);
    if (o.v_enum != 0) e.varintField(8, (long) (o.v_enum));
    if (o.v_msg != null) { long mk = e.begin(9, 46); encTimestamp(e, o.v_msg); e.end(mk); }
    if (o.v_big_tag != 0) e.varintField(536870911, (long) (o.v_big_tag));
  }

  static Timestamp decTimestamp(Dec d) {
    Timestamp r = new Timestamp();
    decTimestamp(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decTimestamp(Dec d, Timestamp r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 0) {   // set_scalar seconds
              r.seconds = d.readVarint();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar nanos
              r.nanos = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static Duration decDuration(Dec d) {
    Duration r = new Duration();
    decDuration(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decDuration(Dec d, Duration r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 0) {   // set_scalar seconds
              r.seconds = d.readVarint();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar nanos
              r.nanos = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ResultRaw decResultRaw(Dec d) {
    ResultRaw r = new ResultRaw();
    decResultRaw(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decResultRaw(Dec d, ResultRaw r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob session_id
              r.session_id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // set_blob name
              r.name = d.readString();
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // set_blob owner_task_id
              r.owner_task_id = d.readString();
            } else break;
            break known;
          case 4:
            if (wire == 0) {   // set_scalar status
              r.status = (int) d.readVarint();
            } else break;
            break known;
          case 5:
            if (wire == 2) {   // merge_child created_at
              if (r.created_at == null) r.created_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.created_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 6:
            if (wire == 2) {   // merge_child completed_at
              if (r.completed_at == null) r.completed_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.completed_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 8:
            if (wire == 2) {   // set_blob result_id
              r.result_id = d.readString();
            } else break;
            break known;
          case 9:
            if (wire == 0) {   // set_scalar size
              r.size = d.readVarint();
            } else break;
            break known;
          case 10:
            if (wire == 2) {   // set_blob created_by
              r.created_by = d.readString();
            } else break;
            break known;
          case 11:
            if (wire == 2) {   // set_blob opaque_id
              r.opaque_id = d.readBytes();
            } else break;
            break known;
          case 12:
            if (wire == 0) {   // set_scalar manual_deletion
              r.manual_deletion = d.readVarint() != 0;
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static TaskOptions decTaskOptions(Dec d) {
    TaskOptions r = new TaskOptions();
    decTaskOptions(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decTaskOptions(Dec d, TaskOptions r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // map_entry options
              {
                if (depth + 1 > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
                int outer = d.push();
                String ek = "", ev = "";
                while (!d.done()) {
                  long kk = d.readVarint();
                  int et = (int) (kk >>> 3), ew = (int) (kk & 7);
                  if (et == 0 || Long.compareUnsigned(kk >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
                  if (et == 1 && ew == 2) ek = d.readString();
                  else if (et == 2 && ew == 2) ev = d.readString();
                  // A facade map entry has no bag: an unknown field inside an
                  // entry is skipped in both modes (`U-map-entry`, disputed).
                  else d.skip(et, ew, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
                }
                d.pop(outer);
                // Plan rule: a duplicate key replaces the earlier value.
                r.options.put(ek, ev);
              }
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // merge_child max_duration
              if (r.max_duration == null) r.max_duration = new Duration();
              { int outer = d.push(); decDuration(d, r.max_duration, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 3:
            if (wire == 0) {   // set_scalar max_retries
              r.max_retries = (int) d.readVarint();
            } else break;
            break known;
          case 4:
            if (wire == 0) {   // set_scalar priority
              r.priority = (int) d.readVarint();
            } else break;
            break known;
          case 5:
            if (wire == 2) {   // set_blob partition_id
              r.partition_id = d.readString();
            } else break;
            break known;
          case 6:
            if (wire == 2) {   // set_blob application_name
              r.application_name = d.readString();
            } else break;
            break known;
          case 7:
            if (wire == 2) {   // set_blob application_version
              r.application_version = d.readString();
            } else break;
            break known;
          case 8:
            if (wire == 2) {   // set_blob application_namespace
              r.application_namespace = d.readString();
            } else break;
            break known;
          case 9:
            if (wire == 2) {   // set_blob application_service
              r.application_service = d.readString();
            } else break;
            break known;
          case 10:
            if (wire == 2) {   // set_blob engine_type
              r.engine_type = d.readString();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static TaskOutput decTaskOutput(Dec d) {
    TaskOutput r = new TaskOutput();
    decTaskOutput(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decTaskOutput(Dec d, TaskOutput r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 0) {   // set_scalar success
              r.success = d.readVarint() != 0;
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // set_blob error
              r.error = d.readString();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static TaskDetailed decTaskDetailed(Dec d) {
    TaskDetailed r = new TaskDetailed();
    decTaskDetailed(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decTaskDetailed(Dec d, TaskDetailed r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob id
              r.id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // set_blob session_id
              r.session_id = d.readString();
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // set_blob owner_pod_id
              r.owner_pod_id = d.readString();
            } else break;
            break known;
          case 4:
            if (wire == 2) {   // append_blob parent_task_ids
              r.parent_task_ids.add(d.readString());
            } else break;
            break known;
          case 5:
            if (wire == 2) {   // append_blob data_dependencies
              r.data_dependencies.add(d.readString());
            } else break;
            break known;
          case 6:
            if (wire == 2) {   // append_blob expected_output_ids
              r.expected_output_ids.add(d.readString());
            } else break;
            break known;
          case 7:
            if (wire == 2) {   // append_blob retry_of_ids
              r.retry_of_ids.add(d.readString());
            } else break;
            break known;
          case 8:
            if (wire == 0) {   // set_scalar status
              r.status = (int) d.readVarint();
            } else break;
            break known;
          case 9:
            if (wire == 2) {   // set_blob status_message
              r.status_message = d.readString();
            } else break;
            break known;
          case 10:
            if (wire == 2) {   // merge_child options
              if (r.options == null) r.options = new TaskOptions();
              { int outer = d.push(); decTaskOptions(d, r.options, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 11:
            if (wire == 2) {   // merge_child created_at
              if (r.created_at == null) r.created_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.created_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 12:
            if (wire == 2) {   // merge_child submitted_at
              if (r.submitted_at == null) r.submitted_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.submitted_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 13:
            if (wire == 2) {   // merge_child started_at
              if (r.started_at == null) r.started_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.started_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 14:
            if (wire == 2) {   // merge_child ended_at
              if (r.ended_at == null) r.ended_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.ended_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 15:
            if (wire == 2) {   // merge_child pod_ttl
              if (r.pod_ttl == null) r.pod_ttl = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.pod_ttl, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 16:
            if (wire == 2) {   // merge_child output
              if (r.output == null) r.output = new TaskOutput();
              { int outer = d.push(); decTaskOutput(d, r.output, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 17:
            if (wire == 2) {   // set_blob pod_hostname
              r.pod_hostname = d.readString();
            } else break;
            break known;
          case 18:
            if (wire == 2) {   // merge_child received_at
              if (r.received_at == null) r.received_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.received_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 19:
            if (wire == 2) {   // merge_child acquired_at
              if (r.acquired_at == null) r.acquired_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.acquired_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 20:
            if (wire == 2) {   // merge_child creation_to_end_duration
              if (r.creation_to_end_duration == null) r.creation_to_end_duration = new Duration();
              { int outer = d.push(); decDuration(d, r.creation_to_end_duration, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 21:
            if (wire == 2) {   // merge_child processing_to_end_duration
              if (r.processing_to_end_duration == null) r.processing_to_end_duration = new Duration();
              { int outer = d.push(); decDuration(d, r.processing_to_end_duration, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 22:
            if (wire == 2) {   // set_blob initial_task_id
              r.initial_task_id = d.readString();
            } else break;
            break known;
          case 23:
            if (wire == 2) {   // merge_child received_to_end_duration
              if (r.received_to_end_duration == null) r.received_to_end_duration = new Duration();
              { int outer = d.push(); decDuration(d, r.received_to_end_duration, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 24:
            if (wire == 2) {   // merge_child processed_at
              if (r.processed_at == null) r.processed_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.processed_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 25:
            if (wire == 2) {   // merge_child fetched_at
              if (r.fetched_at == null) r.fetched_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.fetched_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 26:
            if (wire == 2) {   // set_blob payload_id
              r.payload_id = d.readString();
            } else break;
            break known;
          case 27:
            if (wire == 2) {   // set_blob created_by
              r.created_by = d.readString();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static TaskSummary decTaskSummary(Dec d) {
    TaskSummary r = new TaskSummary();
    decTaskSummary(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decTaskSummary(Dec d, TaskSummary r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob id
              r.id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // set_blob session_id
              r.session_id = d.readString();
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // merge_child options
              if (r.options == null) r.options = new TaskOptions();
              { int outer = d.push(); decTaskOptions(d, r.options, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 4:
            if (wire == 0) {   // set_scalar status
              r.status = (int) d.readVarint();
            } else break;
            break known;
          case 5:
            if (wire == 2) {   // merge_child created_at
              if (r.created_at == null) r.created_at = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.created_at, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 8:
            if (wire == 2) {   // set_blob error
              r.error = d.readString();
            } else break;
            break known;
          case 9:
            if (wire == 2) {   // set_blob status_message
              r.status_message = d.readString();
            } else break;
            break known;
          case 11:
            if (wire == 0) {   // set_scalar count_data_dependencies
              r.count_data_dependencies = d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static Probe decProbe(Dec d) {
    Probe r = new Probe();
    decProbe(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decProbe(Dec d, Probe r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob id
              r.id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar opt_count
              r.opt_count = (int) d.readVarint();
              r.has_opt_count = true;
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // set_blob opt_label
              r.opt_label = d.readString();
            } else break;
            break known;
          case 4:
            if (wire == 0) {   // set_scalar opt_flag
              r.opt_flag = d.readVarint() != 0;
              r.has_opt_flag = true;
            } else break;
            break known;
          case 10:
            if (wire == 0) {   // oneof_set as_int
              r.body_as_int = d.readVarint();
              r.body_case = Probe.BODY_CASE_AS_INT;
            } else break;
            break known;
          case 11:
            if (wire == 2) {   // oneof_set as_text
              r.body_as_text = d.readString();
              r.body_case = Probe.BODY_CASE_AS_TEXT;
            } else break;
            break known;
          case 12:
            if (wire == 2) {   // oneof_set as_blob
              r.body_as_blob = d.readBytes();
              r.body_case = Probe.BODY_CASE_AS_BLOB;
            } else break;
            break known;
          case 13:
            if (wire == 2) {   // oneof_set as_stamp
              if (r.body_case != Probe.BODY_CASE_AS_STAMP || r.body_as_stamp == null) r.body_as_stamp = new Timestamp();
              r.body_case = Probe.BODY_CASE_AS_STAMP;
              { int outer = d.push(); decTimestamp(d, r.body_as_stamp, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 14:
            if (wire == 2) {   // oneof_set as_nothing
              if (r.body_case != Probe.BODY_CASE_AS_NOTHING || r.body_as_nothing == null) r.body_as_nothing = new Empty();
              r.body_case = Probe.BODY_CASE_AS_NOTHING;
              { int outer = d.push(); decEmpty(d, r.body_as_nothing, depth + 1); d.pop(outer); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static Empty decEmpty(Dec d) {
    Empty r = new Empty();
    decEmpty(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decEmpty(Dec d, Empty r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static UploadResultData decUploadResultData(Dec d) {
    UploadResultData r = new UploadResultData();
    decUploadResultData(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decUploadResultData(Dec d, UploadResultData r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob session_id
              r.session_id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // set_blob result_id
              r.result_id = d.readString();
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // set_blob data_chunk
              r.data_chunk = d.readBytes();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static MetricsBatch decMetricsBatch(Dec d) {
    MetricsBatch r = new MetricsBatch();
    decMetricsBatch(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decMetricsBatch(Dec d, MetricsBatch r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob id
              r.id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // packed_one ticks
              { long[] one = {d.readVarint()}; r.ticks = append(r.ticks, one, 1); }
            } else if (wire == 2) {   // packed_run ticks
              { int outer = d.push();
                long[] acc = new long[8];
                int n = 0;
                while (!d.done()) {
                  if (n == acc.length) acc = java.util.Arrays.copyOf(acc, n * 2);
                  acc[n++] = d.readVarint();
                }
                d.pop(outer);
                r.ticks = append(r.ticks, acc, n); }
            } else break;
            break known;
          case 3:
            if (wire == 1) {   // packed_one values
              { double[] one = {d.readDouble()}; r.values = append(r.values, one, 1); }
            } else if (wire == 2) {   // packed_run values
              { int outer = d.push();
                double[] acc = new double[8];
                int n = 0;
                while (!d.done()) {
                  if (n == acc.length) acc = java.util.Arrays.copyOf(acc, n * 2);
                  acc[n++] = d.readDouble();
                }
                d.pop(outer);
                r.values = append(r.values, acc, n); }
            } else break;
            break known;
          case 4:
            if (wire == 0) {   // packed_one codes
              { int[] one = {(int) d.readVarint()}; r.codes = append(r.codes, one, 1); }
            } else if (wire == 2) {   // packed_run codes
              { int outer = d.push();
                int[] acc = new int[8];
                int n = 0;
                while (!d.done()) {
                  if (n == acc.length) acc = java.util.Arrays.copyOf(acc, n * 2);
                  acc[n++] = (int) d.readVarint();
                }
                d.pop(outer);
                r.codes = append(r.codes, acc, n); }
            } else break;
            break known;
          case 5:
            if (wire == 0) {   // packed_one flags
              { boolean[] one = {d.readVarint() != 0}; r.flags = append(r.flags, one, 1); }
            } else if (wire == 2) {   // packed_run flags
              { int outer = d.push();
                boolean[] acc = new boolean[8];
                int n = 0;
                while (!d.done()) {
                  if (n == acc.length) acc = java.util.Arrays.copyOf(acc, n * 2);
                  acc[n++] = d.readVarint() != 0;
                }
                d.pop(outer);
                r.flags = append(r.flags, acc, n); }
            } else break;
            break known;
          case 6:
            if (wire == 0) {   // packed_one statuses
              { int[] one = {(int) d.readVarint()}; r.statuses = append(r.statuses, one, 1); }
            } else if (wire == 2) {   // packed_run statuses
              { int outer = d.push();
                int[] acc = new int[8];
                int n = 0;
                while (!d.done()) {
                  if (n == acc.length) acc = java.util.Arrays.copyOf(acc, n * 2);
                  acc[n++] = (int) d.readVarint();
                }
                d.pop(outer);
                r.statuses = append(r.statuses, acc, n); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static Pair decPair(Dec d) {
    Pair r = new Pair();
    decPair(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decPair(Dec d, Pair r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob key
              r.key = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar value
              r.value = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ListResultsResponse decListResultsResponse(Dec d) {
    ListResultsResponse r = new ListResultsResponse();
    decListResultsResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decListResultsResponse(Dec d, ListResultsResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_message results
              { ResultRaw x = new ResultRaw();
                { int outer = d.push(); decResultRaw(d, x, depth + 1); d.pop(outer); }
                r.results.add(x); }
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar page
              r.page = (int) d.readVarint();
            } else break;
            break known;
          case 3:
            if (wire == 0) {   // set_scalar total
              r.total = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ListTasksDetailedResponse decListTasksDetailedResponse(Dec d) {
    ListTasksDetailedResponse r = new ListTasksDetailedResponse();
    decListTasksDetailedResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decListTasksDetailedResponse(Dec d, ListTasksDetailedResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_message tasks
              { TaskDetailed x = new TaskDetailed();
                { int outer = d.push(); decTaskDetailed(d, x, depth + 1); d.pop(outer); }
                r.tasks.add(x); }
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar page
              r.page = (int) d.readVarint();
            } else break;
            break known;
          case 3:
            if (wire == 0) {   // set_scalar total
              r.total = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ListTaskSummaryResponse decListTaskSummaryResponse(Dec d) {
    ListTaskSummaryResponse r = new ListTaskSummaryResponse();
    decListTaskSummaryResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decListTaskSummaryResponse(Dec d, ListTaskSummaryResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_message tasks
              { TaskSummary x = new TaskSummary();
                { int outer = d.push(); decTaskSummary(d, x, depth + 1); d.pop(outer); }
                r.tasks.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ListProbeResponse decListProbeResponse(Dec d) {
    ListProbeResponse r = new ListProbeResponse();
    decListProbeResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decListProbeResponse(Dec d, ListProbeResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_message probes
              { Probe x = new Probe();
                { int outer = d.push(); decProbe(d, x, depth + 1); d.pop(outer); }
                r.probes.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ListMetricsResponse decListMetricsResponse(Dec d) {
    ListMetricsResponse r = new ListMetricsResponse();
    decListMetricsResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decListMetricsResponse(Dec d, ListMetricsResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_message batches
              { MetricsBatch x = new MetricsBatch();
                { int outer = d.push(); decMetricsBatch(d, x, depth + 1); d.pop(outer); }
                r.batches.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static UploadResultDataMessage decUploadResultDataMessage(Dec d) {
    UploadResultDataMessage r = new UploadResultDataMessage();
    decUploadResultDataMessage(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decUploadResultDataMessage(Dec d, UploadResultDataMessage r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // merge_child upload
              if (r.upload == null) r.upload = new UploadResultData();
              { int outer = d.push(); decUploadResultData(d, r.upload, depth + 1); d.pop(outer); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static DualResponse decDualResponse(Dec d) {
    DualResponse r = new DualResponse();
    decDualResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decDualResponse(Dec d, DualResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_message left
              { Pair x = new Pair();
                { int outer = d.push(); decPair(d, x, depth + 1); d.pop(outer); }
                r.left.add(x); }
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // append_message right
              { Pair x = new Pair();
                { int outer = d.push(); decPair(d, x, depth + 1); d.pop(outer); }
                r.right.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ChunkLeaf decChunkLeaf(Dec d) {
    ChunkLeaf r = new ChunkLeaf();
    decChunkLeaf(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decChunkLeaf(Dec d, ChunkLeaf r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob k
              r.k = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar v
              r.v = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ChunkInner decChunkInner(Dec d) {
    ChunkInner r = new ChunkInner();
    decChunkInner(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decChunkInner(Dec d, ChunkInner r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 0) {   // packed_one marks
              { long[] one = {d.readVarint()}; r.marks = append(r.marks, one, 1); }
            } else if (wire == 2) {   // packed_run marks
              { int outer = d.push();
                long[] acc = new long[8];
                int n = 0;
                while (!d.done()) {
                  if (n == acc.length) acc = java.util.Arrays.copyOf(acc, n * 2);
                  acc[n++] = d.readVarint();
                }
                d.pop(outer);
                r.marks = append(r.marks, acc, n); }
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // append_message leaves
              { ChunkLeaf x = new ChunkLeaf();
                { int outer = d.push(); decChunkLeaf(d, x, depth + 1); d.pop(outer); }
                r.leaves.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ChunkElement decChunkElement(Dec d) {
    ChunkElement r = new ChunkElement();
    decChunkElement(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decChunkElement(Dec d, ChunkElement r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // append_blob labels
              r.labels.add(d.readString());
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // map_entry attrs
              {
                if (depth + 1 > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
                int outer = d.push();
                String ek = "", ev = "";
                while (!d.done()) {
                  long kk = d.readVarint();
                  int et = (int) (kk >>> 3), ew = (int) (kk & 7);
                  if (et == 0 || Long.compareUnsigned(kk >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
                  if (et == 1 && ew == 2) ek = d.readString();
                  else if (et == 2 && ew == 2) ev = d.readString();
                  // A facade map entry has no bag: an unknown field inside an
                  // entry is skipped in both modes (`U-map-entry`, disputed).
                  else d.skip(et, ew, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
                }
                d.pop(outer);
                // Plan rule: a duplicate key replaces the earlier value.
                r.attrs.put(ek, ev);
              }
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // set_blob id
              r.id = d.readString();
            } else break;
            break known;
          case 4:
            if (wire == 2) {   // merge_child inner
              if (r.inner == null) r.inner = new ChunkInner();
              { int outer = d.push(); decChunkInner(d, r.inner, depth + 1); d.pop(outer); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ChunkedResponse decChunkedResponse(Dec d) {
    ChunkedResponse r = new ChunkedResponse();
    decChunkedResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decChunkedResponse(Dec d, ChunkedResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 7:
            if (wire == 2) {   // append_message items
              { ChunkElement x = new ChunkElement();
                { int outer = d.push(); decChunkElement(d, x, depth + 1); d.pop(outer); }
                r.items.add(x); }
            } else break;
            break known;
          case 8:
            if (wire == 0) {   // set_scalar page
              r.page = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static ChunkedResponseWide decChunkedResponseWide(Dec d) {
    ChunkedResponseWide r = new ChunkedResponseWide();
    decChunkedResponseWide(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decChunkedResponseWide(Dec d, ChunkedResponseWide r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 70000:
            if (wire == 2) {   // append_message items
              { ChunkElement x = new ChunkElement();
                { int outer = d.push(); decChunkElement(d, x, depth + 1); d.pop(outer); }
                r.items.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static LeafElement decLeafElement(Dec d) {
    LeafElement r = new LeafElement();
    decLeafElement(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decLeafElement(Dec d, LeafElement r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob id
              r.id = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar n
              r.n = d.readVarint();
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // merge_child stamp
              if (r.stamp == null) r.stamp = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.stamp, depth + 1); d.pop(outer); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static LeafResponse decLeafResponse(Dec d) {
    LeafResponse r = new LeafResponse();
    decLeafResponse(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decLeafResponse(Dec d, LeafResponse r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 9:
            if (wire == 2) {   // append_message items
              { LeafElement x = new LeafElement();
                { int outer = d.push(); decLeafElement(d, x, depth + 1); d.pop(outer); }
                r.items.add(x); }
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static Surrogate decSurrogate(Dec d) {
    Surrogate r = new Surrogate();
    decSurrogate(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decSurrogate(Dec d, Surrogate r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob text
              r.text = d.readString();
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // merge_child nested
              if (r.nested == null) r.nested = new SurrogateInner();
              { int outer = d.push(); decSurrogateInner(d, r.nested, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 3:
            if (wire == 2) {   // map_entry attrs
              {
                if (depth + 1 > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
                int outer = d.push();
                String ek = "", ev = "";
                while (!d.done()) {
                  long kk = d.readVarint();
                  int et = (int) (kk >>> 3), ew = (int) (kk & 7);
                  if (et == 0 || Long.compareUnsigned(kk >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
                  if (et == 1 && ew == 2) ek = d.readString();
                  else if (et == 2 && ew == 2) ev = d.readString();
                  // A facade map entry has no bag: an unknown field inside an
                  // entry is skipped in both modes (`U-map-entry`, disputed).
                  else d.skip(et, ew, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
                }
                d.pop(outer);
                // Plan rule: a duplicate key replaces the earlier value.
                r.attrs.put(ek, ev);
              }
            } else break;
            break known;
          case 4:
            if (wire == 2) {   // append_blob texts
              r.texts.add(d.readString());
            } else break;
            break known;
          case 5:
            if (wire == 2) {   // set_blob raw
              r.raw = d.readBytes();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static SurrogateInner decSurrogateInner(Dec d) {
    SurrogateInner r = new SurrogateInner();
    decSurrogateInner(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decSurrogateInner(Dec d, SurrogateInner r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // set_blob text
              r.text = d.readString();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static Nest decNest(Dec d) {
    Nest r = new Nest();
    decNest(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decNest(Dec d, Nest r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 2) {   // merge_child child
              if (r.child == null) r.child = new Nest();
              { int outer = d.push(); decNest(d, r.child, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 2:
            if (wire == 2) {   // set_blob leaf
              r.leaf = d.readString();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  static WireZoo decWireZoo(Dec d) {
    WireZoo r = new WireZoo();
    decWireZoo(d, r, 0);
    return r;
  }

  /** Decode INTO `r`, which is what makes a repeated occurrence merge. */
  static void decWireZoo(Dec d, WireZoo r, int depth) {
    // Plan rule: a message more than LIMIT levels below the root is refused.
    if (depth > LIMIT) throw Dec.err(Dec.ERR_DEPTH, "nesting past " + LIMIT);
    while (!d.done()) {
      int s0 = d.pos;
      long k = d.readVarint();
      int tag = (int) (k >>> 3), wire = (int) (k & 7);
      // Plan rule: field number 0 is malformed on every message (R-E4).
      if (tag == 0 || Long.compareUnsigned(k >>> 3, 536870911L) > 0) throw Dec.err(Dec.ERR_MALFORMED, "field number 0 or above 2^29-1");
      known: {
        switch (tag) {
          case 1:
            if (wire == 0) {   // set_scalar v_int32
              r.v_int32 = (int) d.readVarint();
            } else break;
            break known;
          case 2:
            if (wire == 0) {   // set_scalar v_int64
              r.v_int64 = d.readVarint();
            } else break;
            break known;
          case 3:
            if (wire == 0) {   // set_scalar v_bool
              r.v_bool = d.readVarint() != 0;
            } else break;
            break known;
          case 4:
            if (wire == 1) {   // set_scalar v_double
              r.v_double = d.readDouble();
            } else break;
            break known;
          case 5:
            if (wire == 5) {   // set_scalar v_fixed32
              r.v_fixed32 = d.readFixed32();
            } else break;
            break known;
          case 6:
            if (wire == 2) {   // set_blob v_string
              r.v_string = d.readString();
            } else break;
            break known;
          case 7:
            if (wire == 2) {   // set_blob v_bytes
              r.v_bytes = d.readBytes();
            } else break;
            break known;
          case 8:
            if (wire == 0) {   // set_scalar v_enum
              r.v_enum = (int) d.readVarint();
            } else break;
            break known;
          case 9:
            if (wire == 2) {   // merge_child v_msg
              if (r.v_msg == null) r.v_msg = new Timestamp();
              { int outer = d.push(); decTimestamp(d, r.v_msg, depth + 1); d.pop(outer); }
            } else break;
            break known;
          case 536870911:
            if (wire == 0) {   // set_scalar v_big_tag
              r.v_big_tag = (int) d.readVarint();
            } else break;
            break known;
          default: break;
        }
        // Plan rule (drop): not in the table -- including a known number at a
        // wire type the table has no entry for (R-E2) -- is skipped.
        d.skip(tag, wire, MAX_FIELD_NUMBER, GROUP_DEPTH_LIMIT);
      }
    }
  }

  // ---- the roots ------------------------------------------------------

  public static byte[] encodeTimestamp(Enc e, Timestamp o) {
    e.reset();
    encTimestamp(e, o);
    return e.toBytes();
  }

  public static void encodeIntoTimestamp(Enc e, Timestamp o) {
    e.reset();
    encTimestamp(e, o);
  }

  public static Timestamp decodeTimestamp(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decTimestamp(d);
  }

  public static byte[] encodeDuration(Enc e, Duration o) {
    e.reset();
    encDuration(e, o);
    return e.toBytes();
  }

  public static void encodeIntoDuration(Enc e, Duration o) {
    e.reset();
    encDuration(e, o);
  }

  public static Duration decodeDuration(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decDuration(d);
  }

  public static byte[] encodeResultRaw(Enc e, ResultRaw o) {
    e.reset();
    encResultRaw(e, o);
    return e.toBytes();
  }

  public static void encodeIntoResultRaw(Enc e, ResultRaw o) {
    e.reset();
    encResultRaw(e, o);
  }

  public static ResultRaw decodeResultRaw(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decResultRaw(d);
  }

  public static byte[] encodeTaskOptions(Enc e, TaskOptions o) {
    e.reset();
    encTaskOptions(e, o);
    return e.toBytes();
  }

  public static void encodeIntoTaskOptions(Enc e, TaskOptions o) {
    e.reset();
    encTaskOptions(e, o);
  }

  public static TaskOptions decodeTaskOptions(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decTaskOptions(d);
  }

  public static byte[] encodeTaskOutput(Enc e, TaskOutput o) {
    e.reset();
    encTaskOutput(e, o);
    return e.toBytes();
  }

  public static void encodeIntoTaskOutput(Enc e, TaskOutput o) {
    e.reset();
    encTaskOutput(e, o);
  }

  public static TaskOutput decodeTaskOutput(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decTaskOutput(d);
  }

  public static byte[] encodeTaskDetailed(Enc e, TaskDetailed o) {
    e.reset();
    encTaskDetailed(e, o);
    return e.toBytes();
  }

  public static void encodeIntoTaskDetailed(Enc e, TaskDetailed o) {
    e.reset();
    encTaskDetailed(e, o);
  }

  public static TaskDetailed decodeTaskDetailed(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decTaskDetailed(d);
  }

  public static byte[] encodeTaskSummary(Enc e, TaskSummary o) {
    e.reset();
    encTaskSummary(e, o);
    return e.toBytes();
  }

  public static void encodeIntoTaskSummary(Enc e, TaskSummary o) {
    e.reset();
    encTaskSummary(e, o);
  }

  public static TaskSummary decodeTaskSummary(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decTaskSummary(d);
  }

  public static byte[] encodeProbe(Enc e, Probe o) {
    e.reset();
    encProbe(e, o);
    return e.toBytes();
  }

  public static void encodeIntoProbe(Enc e, Probe o) {
    e.reset();
    encProbe(e, o);
  }

  public static Probe decodeProbe(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decProbe(d);
  }

  public static byte[] encodeEmpty(Enc e, Empty o) {
    e.reset();
    encEmpty(e, o);
    return e.toBytes();
  }

  public static void encodeIntoEmpty(Enc e, Empty o) {
    e.reset();
    encEmpty(e, o);
  }

  public static Empty decodeEmpty(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decEmpty(d);
  }

  public static byte[] encodeUploadResultData(Enc e, UploadResultData o) {
    e.reset();
    encUploadResultData(e, o);
    return e.toBytes();
  }

  public static void encodeIntoUploadResultData(Enc e, UploadResultData o) {
    e.reset();
    encUploadResultData(e, o);
  }

  public static UploadResultData decodeUploadResultData(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decUploadResultData(d);
  }

  public static byte[] encodeMetricsBatch(Enc e, MetricsBatch o) {
    e.reset();
    encMetricsBatch(e, o);
    return e.toBytes();
  }

  public static void encodeIntoMetricsBatch(Enc e, MetricsBatch o) {
    e.reset();
    encMetricsBatch(e, o);
  }

  public static MetricsBatch decodeMetricsBatch(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decMetricsBatch(d);
  }

  public static byte[] encodePair(Enc e, Pair o) {
    e.reset();
    encPair(e, o);
    return e.toBytes();
  }

  public static void encodeIntoPair(Enc e, Pair o) {
    e.reset();
    encPair(e, o);
  }

  public static Pair decodePair(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decPair(d);
  }

  public static byte[] encodeListResultsResponse(Enc e, ListResultsResponse o) {
    e.reset();
    encListResultsResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoListResultsResponse(Enc e, ListResultsResponse o) {
    e.reset();
    encListResultsResponse(e, o);
  }

  public static ListResultsResponse decodeListResultsResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decListResultsResponse(d);
  }

  public static byte[] encodeListTasksDetailedResponse(Enc e, ListTasksDetailedResponse o) {
    e.reset();
    encListTasksDetailedResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoListTasksDetailedResponse(Enc e, ListTasksDetailedResponse o) {
    e.reset();
    encListTasksDetailedResponse(e, o);
  }

  public static ListTasksDetailedResponse decodeListTasksDetailedResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decListTasksDetailedResponse(d);
  }

  public static byte[] encodeListTaskSummaryResponse(Enc e, ListTaskSummaryResponse o) {
    e.reset();
    encListTaskSummaryResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoListTaskSummaryResponse(Enc e, ListTaskSummaryResponse o) {
    e.reset();
    encListTaskSummaryResponse(e, o);
  }

  public static ListTaskSummaryResponse decodeListTaskSummaryResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decListTaskSummaryResponse(d);
  }

  public static byte[] encodeListProbeResponse(Enc e, ListProbeResponse o) {
    e.reset();
    encListProbeResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoListProbeResponse(Enc e, ListProbeResponse o) {
    e.reset();
    encListProbeResponse(e, o);
  }

  public static ListProbeResponse decodeListProbeResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decListProbeResponse(d);
  }

  public static byte[] encodeListMetricsResponse(Enc e, ListMetricsResponse o) {
    e.reset();
    encListMetricsResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoListMetricsResponse(Enc e, ListMetricsResponse o) {
    e.reset();
    encListMetricsResponse(e, o);
  }

  public static ListMetricsResponse decodeListMetricsResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decListMetricsResponse(d);
  }

  public static byte[] encodeUploadResultDataMessage(Enc e, UploadResultDataMessage o) {
    e.reset();
    encUploadResultDataMessage(e, o);
    return e.toBytes();
  }

  public static void encodeIntoUploadResultDataMessage(Enc e, UploadResultDataMessage o) {
    e.reset();
    encUploadResultDataMessage(e, o);
  }

  public static UploadResultDataMessage decodeUploadResultDataMessage(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decUploadResultDataMessage(d);
  }

  public static byte[] encodeDualResponse(Enc e, DualResponse o) {
    e.reset();
    encDualResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoDualResponse(Enc e, DualResponse o) {
    e.reset();
    encDualResponse(e, o);
  }

  public static DualResponse decodeDualResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decDualResponse(d);
  }

  public static byte[] encodeChunkLeaf(Enc e, ChunkLeaf o) {
    e.reset();
    encChunkLeaf(e, o);
    return e.toBytes();
  }

  public static void encodeIntoChunkLeaf(Enc e, ChunkLeaf o) {
    e.reset();
    encChunkLeaf(e, o);
  }

  public static ChunkLeaf decodeChunkLeaf(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decChunkLeaf(d);
  }

  public static byte[] encodeChunkInner(Enc e, ChunkInner o) {
    e.reset();
    encChunkInner(e, o);
    return e.toBytes();
  }

  public static void encodeIntoChunkInner(Enc e, ChunkInner o) {
    e.reset();
    encChunkInner(e, o);
  }

  public static ChunkInner decodeChunkInner(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decChunkInner(d);
  }

  public static byte[] encodeChunkElement(Enc e, ChunkElement o) {
    e.reset();
    encChunkElement(e, o);
    return e.toBytes();
  }

  public static void encodeIntoChunkElement(Enc e, ChunkElement o) {
    e.reset();
    encChunkElement(e, o);
  }

  public static ChunkElement decodeChunkElement(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decChunkElement(d);
  }

  public static byte[] encodeChunkedResponse(Enc e, ChunkedResponse o) {
    e.reset();
    encChunkedResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoChunkedResponse(Enc e, ChunkedResponse o) {
    e.reset();
    encChunkedResponse(e, o);
  }

  public static ChunkedResponse decodeChunkedResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decChunkedResponse(d);
  }

  public static byte[] encodeChunkedResponseWide(Enc e, ChunkedResponseWide o) {
    e.reset();
    encChunkedResponseWide(e, o);
    return e.toBytes();
  }

  public static void encodeIntoChunkedResponseWide(Enc e, ChunkedResponseWide o) {
    e.reset();
    encChunkedResponseWide(e, o);
  }

  public static ChunkedResponseWide decodeChunkedResponseWide(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decChunkedResponseWide(d);
  }

  public static byte[] encodeLeafElement(Enc e, LeafElement o) {
    e.reset();
    encLeafElement(e, o);
    return e.toBytes();
  }

  public static void encodeIntoLeafElement(Enc e, LeafElement o) {
    e.reset();
    encLeafElement(e, o);
  }

  public static LeafElement decodeLeafElement(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decLeafElement(d);
  }

  public static byte[] encodeLeafResponse(Enc e, LeafResponse o) {
    e.reset();
    encLeafResponse(e, o);
    return e.toBytes();
  }

  public static void encodeIntoLeafResponse(Enc e, LeafResponse o) {
    e.reset();
    encLeafResponse(e, o);
  }

  public static LeafResponse decodeLeafResponse(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decLeafResponse(d);
  }

  public static byte[] encodeSurrogate(Enc e, Surrogate o) {
    e.reset();
    encSurrogate(e, o);
    return e.toBytes();
  }

  public static void encodeIntoSurrogate(Enc e, Surrogate o) {
    e.reset();
    encSurrogate(e, o);
  }

  public static Surrogate decodeSurrogate(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decSurrogate(d);
  }

  public static byte[] encodeSurrogateInner(Enc e, SurrogateInner o) {
    e.reset();
    encSurrogateInner(e, o);
    return e.toBytes();
  }

  public static void encodeIntoSurrogateInner(Enc e, SurrogateInner o) {
    e.reset();
    encSurrogateInner(e, o);
  }

  public static SurrogateInner decodeSurrogateInner(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decSurrogateInner(d);
  }

  public static byte[] encodeNest(Enc e, Nest o) {
    e.reset();
    encNest(e, o);
    return e.toBytes();
  }

  public static void encodeIntoNest(Enc e, Nest o) {
    e.reset();
    encNest(e, o);
  }

  public static Nest decodeNest(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decNest(d);
  }

  public static byte[] encodeWireZoo(Enc e, WireZoo o) {
    e.reset();
    encWireZoo(e, o);
    return e.toBytes();
  }

  public static void encodeIntoWireZoo(Enc e, WireZoo o) {
    e.reset();
    encWireZoo(e, o);
  }

  public static WireZoo decodeWireZoo(Dec d, byte[] buf, int off, int len) {
    d.reset(buf, off, len);
    return decWireZoo(d);
  }
}
