// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

public final class ListTasksDetailedResponse {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public java.util.List<TaskDetailed> tasks = new java.util.ArrayList<TaskDetailed>();
  public int page = 0;
  public int total = 0;

  /** Unknown fields captured by a retain-mode codec, verbatim, key included;
   *  re-emitted after the known fields. `null` when none. */
  public byte[] unknownFields;
}
