// @generated by ffi/poc/java/gen/java_walk.py (campaign glue). Do not edit.

package ak.corpus;

/** Read every field of a decoded facade value (CAMPAIGN.md req 9). */
public final class Walk {
  private Walk() {}

  public static long walk(String root, Object o) {
    switch (root) {
      case "Timestamp": return wTimestamp((Timestamp) o);
      case "Duration": return wDuration((Duration) o);
      case "ResultRaw": return wResultRaw((ResultRaw) o);
      case "TaskOptions": return wTaskOptions((TaskOptions) o);
      case "TaskOutput": return wTaskOutput((TaskOutput) o);
      case "TaskDetailed": return wTaskDetailed((TaskDetailed) o);
      case "TaskSummary": return wTaskSummary((TaskSummary) o);
      case "Probe": return wProbe((Probe) o);
      case "Empty": return wEmpty((Empty) o);
      case "UploadResultData": return wUploadResultData((UploadResultData) o);
      case "MetricsBatch": return wMetricsBatch((MetricsBatch) o);
      case "Pair": return wPair((Pair) o);
      case "ListResultsResponse": return wListResultsResponse((ListResultsResponse) o);
      case "ListTasksDetailedResponse": return wListTasksDetailedResponse((ListTasksDetailedResponse) o);
      case "ListTaskSummaryResponse": return wListTaskSummaryResponse((ListTaskSummaryResponse) o);
      case "ListProbeResponse": return wListProbeResponse((ListProbeResponse) o);
      case "ListMetricsResponse": return wListMetricsResponse((ListMetricsResponse) o);
      case "UploadResultDataMessage": return wUploadResultDataMessage((UploadResultDataMessage) o);
      case "DualResponse": return wDualResponse((DualResponse) o);
      case "ChunkLeaf": return wChunkLeaf((ChunkLeaf) o);
      case "ChunkInner": return wChunkInner((ChunkInner) o);
      case "ChunkElement": return wChunkElement((ChunkElement) o);
      case "ChunkedResponse": return wChunkedResponse((ChunkedResponse) o);
      case "ChunkedResponseWide": return wChunkedResponseWide((ChunkedResponseWide) o);
      case "LeafElement": return wLeafElement((LeafElement) o);
      case "LeafResponse": return wLeafResponse((LeafResponse) o);
      case "Surrogate": return wSurrogate((Surrogate) o);
      case "SurrogateInner": return wSurrogateInner((SurrogateInner) o);
      case "Nest": return wNest((Nest) o);
      case "WireZoo": return wWireZoo((WireZoo) o);
      default: throw new IllegalArgumentException(root);
    }
  }

  static long wTimestamp(Timestamp o) {
    long h = 0;
    h += o.seconds;
    h += o.nanos;
    return h;
  }

  static long wDuration(Duration o) {
    long h = 0;
    h += o.seconds;
    h += o.nanos;
    return h;
  }

  static long wResultRaw(ResultRaw o) {
    long h = 0;
    h += o.session_id.length();
    h += o.name.length();
    h += o.owner_task_id.length();
    h += o.status;
    if (o.created_at != null) { h += wTimestamp(o.created_at); }
    if (o.completed_at != null) { h += wTimestamp(o.completed_at); }
    h += o.result_id.length();
    h += o.size;
    h += o.created_by.length();
    h += o.opaque_id.length;
    h += o.manual_deletion ? 1 : 0;
    return h;
  }

  static long wTaskOptions(TaskOptions o) {
    long h = 0;
    for (java.util.Map.Entry<String, String> e : o.options.entrySet()) h += e.getKey().length() + e.getValue().length();
    if (o.max_duration != null) { h += wDuration(o.max_duration); }
    h += o.max_retries;
    h += o.priority;
    h += o.partition_id.length();
    h += o.application_name.length();
    h += o.application_version.length();
    h += o.application_namespace.length();
    h += o.application_service.length();
    h += o.engine_type.length();
    return h;
  }

  static long wTaskOutput(TaskOutput o) {
    long h = 0;
    h += o.success ? 1 : 0;
    h += o.error.length();
    return h;
  }

  static long wTaskDetailed(TaskDetailed o) {
    long h = 0;
    h += o.id.length();
    h += o.session_id.length();
    h += o.owner_pod_id.length();
    for (String x : o.parent_task_ids) { h += x.length(); }
    for (String x : o.data_dependencies) { h += x.length(); }
    for (String x : o.expected_output_ids) { h += x.length(); }
    for (String x : o.retry_of_ids) { h += x.length(); }
    h += o.status;
    h += o.status_message.length();
    if (o.options != null) { h += wTaskOptions(o.options); }
    if (o.created_at != null) { h += wTimestamp(o.created_at); }
    if (o.submitted_at != null) { h += wTimestamp(o.submitted_at); }
    if (o.started_at != null) { h += wTimestamp(o.started_at); }
    if (o.ended_at != null) { h += wTimestamp(o.ended_at); }
    if (o.pod_ttl != null) { h += wTimestamp(o.pod_ttl); }
    if (o.output != null) { h += wTaskOutput(o.output); }
    h += o.pod_hostname.length();
    if (o.received_at != null) { h += wTimestamp(o.received_at); }
    if (o.acquired_at != null) { h += wTimestamp(o.acquired_at); }
    if (o.creation_to_end_duration != null) { h += wDuration(o.creation_to_end_duration); }
    if (o.processing_to_end_duration != null) { h += wDuration(o.processing_to_end_duration); }
    h += o.initial_task_id.length();
    if (o.received_to_end_duration != null) { h += wDuration(o.received_to_end_duration); }
    if (o.processed_at != null) { h += wTimestamp(o.processed_at); }
    if (o.fetched_at != null) { h += wTimestamp(o.fetched_at); }
    h += o.payload_id.length();
    h += o.created_by.length();
    return h;
  }

  static long wTaskSummary(TaskSummary o) {
    long h = 0;
    h += o.id.length();
    h += o.session_id.length();
    if (o.options != null) { h += wTaskOptions(o.options); }
    h += o.status;
    if (o.created_at != null) { h += wTimestamp(o.created_at); }
    h += o.error.length();
    h += o.status_message.length();
    h += o.count_data_dependencies;
    return h;
  }

  static long wProbe(Probe o) {
    long h = 0;
    h += o.id.length();
    h += o.opt_count;
    if (o.opt_label != null) { h += o.opt_label.length(); }
    h += o.opt_flag ? 1 : 0;
    switch (o.body_case) {
      case 10: { h += o.body_as_int; } break;
      case 11: if (o.body_as_text != null) { h += o.body_as_text.length(); } break;
      case 12: if (o.body_as_blob != null) { h += o.body_as_blob.length; } break;
      case 13: if (o.body_as_stamp != null) { h += wTimestamp(o.body_as_stamp); } break;
      case 14: if (o.body_as_nothing != null) { h += wEmpty(o.body_as_nothing); } break;
      default: break;
    }
    return h;
  }

  static long wEmpty(Empty o) {
    long h = 0;
    return h;
  }

  static long wUploadResultData(UploadResultData o) {
    long h = 0;
    h += o.session_id.length();
    h += o.result_id.length();
    h += o.data_chunk.length;
    return h;
  }

  static long wMetricsBatch(MetricsBatch o) {
    long h = 0;
    h += o.id.length();
    for (int i = 0; i < o.ticks.length; i++) { h += o.ticks[i]; }
    for (int i = 0; i < o.values.length; i++) { h += Double.doubleToRawLongBits(o.values[i]); }
    for (int i = 0; i < o.codes.length; i++) { h += o.codes[i]; }
    for (int i = 0; i < o.flags.length; i++) { h += o.flags[i] ? 1 : 0; }
    for (int i = 0; i < o.statuses.length; i++) { h += o.statuses[i]; }
    return h;
  }

  static long wPair(Pair o) {
    long h = 0;
    h += o.key.length();
    h += o.value;
    return h;
  }

  static long wListResultsResponse(ListResultsResponse o) {
    long h = 0;
    for (ResultRaw x : o.results) { h += wResultRaw(x); }
    h += o.page;
    h += o.total;
    return h;
  }

  static long wListTasksDetailedResponse(ListTasksDetailedResponse o) {
    long h = 0;
    for (TaskDetailed x : o.tasks) { h += wTaskDetailed(x); }
    h += o.page;
    h += o.total;
    return h;
  }

  static long wListTaskSummaryResponse(ListTaskSummaryResponse o) {
    long h = 0;
    for (TaskSummary x : o.tasks) { h += wTaskSummary(x); }
    return h;
  }

  static long wListProbeResponse(ListProbeResponse o) {
    long h = 0;
    for (Probe x : o.probes) { h += wProbe(x); }
    return h;
  }

  static long wListMetricsResponse(ListMetricsResponse o) {
    long h = 0;
    for (MetricsBatch x : o.batches) { h += wMetricsBatch(x); }
    return h;
  }

  static long wUploadResultDataMessage(UploadResultDataMessage o) {
    long h = 0;
    if (o.upload != null) { h += wUploadResultData(o.upload); }
    return h;
  }

  static long wDualResponse(DualResponse o) {
    long h = 0;
    for (Pair x : o.left) { h += wPair(x); }
    for (Pair x : o.right) { h += wPair(x); }
    return h;
  }

  static long wChunkLeaf(ChunkLeaf o) {
    long h = 0;
    h += o.k.length();
    h += o.v;
    return h;
  }

  static long wChunkInner(ChunkInner o) {
    long h = 0;
    for (int i = 0; i < o.marks.length; i++) { h += o.marks[i]; }
    for (ChunkLeaf x : o.leaves) { h += wChunkLeaf(x); }
    return h;
  }

  static long wChunkElement(ChunkElement o) {
    long h = 0;
    for (String x : o.labels) { h += x.length(); }
    for (java.util.Map.Entry<String, String> e : o.attrs.entrySet()) h += e.getKey().length() + e.getValue().length();
    h += o.id.length();
    if (o.inner != null) { h += wChunkInner(o.inner); }
    return h;
  }

  static long wChunkedResponse(ChunkedResponse o) {
    long h = 0;
    for (ChunkElement x : o.items) { h += wChunkElement(x); }
    h += o.page;
    return h;
  }

  static long wChunkedResponseWide(ChunkedResponseWide o) {
    long h = 0;
    for (ChunkElement x : o.items) { h += wChunkElement(x); }
    return h;
  }

  static long wLeafElement(LeafElement o) {
    long h = 0;
    h += o.id.length();
    h += o.n;
    if (o.stamp != null) { h += wTimestamp(o.stamp); }
    return h;
  }

  static long wLeafResponse(LeafResponse o) {
    long h = 0;
    for (LeafElement x : o.items) { h += wLeafElement(x); }
    return h;
  }

  static long wSurrogate(Surrogate o) {
    long h = 0;
    h += o.text.length();
    if (o.nested != null) { h += wSurrogateInner(o.nested); }
    for (java.util.Map.Entry<String, String> e : o.attrs.entrySet()) h += e.getKey().length() + e.getValue().length();
    for (String x : o.texts) { h += x.length(); }
    h += o.raw.length;
    return h;
  }

  static long wSurrogateInner(SurrogateInner o) {
    long h = 0;
    h += o.text.length();
    return h;
  }

  static long wNest(Nest o) {
    long h = 0;
    if (o.child != null) { h += wNest(o.child); }
    h += o.leaf.length();
    return h;
  }

  static long wWireZoo(WireZoo o) {
    long h = 0;
    h += o.v_int32;
    h += o.v_int64;
    h += o.v_bool ? 1 : 0;
    h += Double.doubleToRawLongBits(o.v_double);
    h += o.v_fixed32;
    h += o.v_string.length();
    h += o.v_bytes.length;
    h += o.v_enum;
    if (o.v_msg != null) { h += wTimestamp(o.v_msg); }
    h += o.v_big_tag;
    return h;
  }
}
