// @generated by ffi/poc/codec/gen/java_jni.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

/** Per-message ABI entry points of this description, and the lifecycle call.
 *  Declared once, shared by every facade package over this description. */
public final class NativeEntry {
  private NativeEntry() {}

  public static native long encTrampoline(int i);
  public static native long decTrampoline(int i);

  /** `ak_init` with the plan's default flags (AK_INIT_NO_CRYPTO, AK_INIT_NO_PANIC_HOOK). */
  static native int init();

  private static boolean initDone;

  /** ABI v1 section 3, rendered from plan.lifecycle (R-G7): called by every
   *  generated Binding before its first codec call. AK_OK and AK_ALREADY_INITIALIZED are success;
   *  anything else throws, so a refused init is loud. `-Dak.skipInit=1` skips the
   *  call: a PLANTED CONTROL for the gate only -- against a core built with
   *  `init-guard` every codec call must then fail with AK_ERR_UNINITIALIZED. */
  public static synchronized void ensureInit() {
    if (initDone) return;
    if ("1".equals(System.getProperty("ak.skipInit"))) {
      System.err.println("ak.skipInit=1: ak_init NOT called (planted control)");
      initDone = true;
      return;
    }
    int rc = init();
    if (rc != 0 && rc != 1)   // AK_OK, AK_ALREADY_INITIALIZED
      throw new IllegalStateException("ak_init returned " + rc);
    initDone = true;
  }

  public static native long encodeTimestamp(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewTimestamp();
  public static native int decodeTimestamp(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseTimestamp(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeDuration(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewDuration();
  public static native int decodeDuration(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseDuration(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeResultRaw(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewResultRaw();
  public static native int decodeResultRaw(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseResultRaw(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeTaskOptions(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewTaskOptions();
  public static native int decodeTaskOptions(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseTaskOptions(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeTaskOutput(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewTaskOutput();
  public static native int decodeTaskOutput(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseTaskOutput(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeTaskDetailed(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewTaskDetailed();
  public static native int decodeTaskDetailed(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseTaskDetailed(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeTaskSummary(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewTaskSummary();
  public static native int decodeTaskSummary(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseTaskSummary(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeProbe(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewProbe();
  public static native int decodeProbe(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseProbe(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeEmpty(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewEmpty();
  public static native int decodeEmpty(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseEmpty(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeUploadResultData(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewUploadResultData();
  /** ABI v1 section 8: the direct field pinned for the call. */
  public static native long encodeDirectUploadResultData(Object self, long ctx, long vt, long fix, byte[] data, int dlen);
  public static native int decodeUploadResultData(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseUploadResultData(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeMetricsBatch(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewMetricsBatch();
  public static native int decodeMetricsBatch(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseMetricsBatch(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodePair(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewPair();
  public static native int decodePair(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parsePair(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeListResultsResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewListResultsResponse();
  public static native int decodeListResultsResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseListResultsResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeListTasksDetailedResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewListTasksDetailedResponse();
  public static native int decodeListTasksDetailedResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseListTasksDetailedResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeListTaskSummaryResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewListTaskSummaryResponse();
  public static native int decodeListTaskSummaryResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseListTaskSummaryResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeListProbeResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewListProbeResponse();
  public static native int decodeListProbeResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseListProbeResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeListMetricsResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewListMetricsResponse();
  public static native int decodeListMetricsResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseListMetricsResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeUploadResultDataMessage(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewUploadResultDataMessage();
  /** ABI v1 section 8: the direct field pinned for the call. */
  public static native long encodeDirectUploadResultDataMessage(Object self, long ctx, long vt, long fix, byte[] data, int dlen);
  public static native int decodeUploadResultDataMessage(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseUploadResultDataMessage(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeDualResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewDualResponse();
  public static native int decodeDualResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseDualResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeChunkLeaf(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewChunkLeaf();
  public static native int decodeChunkLeaf(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseChunkLeaf(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeChunkInner(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewChunkInner();
  public static native int decodeChunkInner(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseChunkInner(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeChunkElement(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewChunkElement();
  public static native int decodeChunkElement(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseChunkElement(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeChunkedResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewChunkedResponse();
  public static native int decodeChunkedResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseChunkedResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeChunkedResponseWide(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewChunkedResponseWide();
  public static native int decodeChunkedResponseWide(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseChunkedResponseWide(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeLeafElement(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewLeafElement();
  public static native int decodeLeafElement(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseLeafElement(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeLeafResponse(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewLeafResponse();
  public static native int decodeLeafResponse(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseLeafResponse(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeSurrogate(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewSurrogate();
  public static native int decodeSurrogate(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseSurrogate(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeSurrogateInner(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewSurrogateInner();
  public static native int decodeSurrogateInner(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseSurrogateInner(Object self, long ctx, byte[] wire, int off, int len);

  public static native long encodeWireZoo(Object self, long ctx, long vt, long fix);
  /** Rule 6 in the no-unknown variant: a context bound to this root (no options). */
  public static native long decCtxNewWireZoo();
  public static native int decodeWireZoo(Object self, long ctx, long buf, long len, long vt);
  /** ABI v1 7.1's pull family, over the host's OWN array (no upcall). */
  public static native int parseWireZoo(Object self, long ctx, byte[] wire, int off, int len);

  public static native int elemuChunkElement(long ctx, long elems, int n, long tok0);
  public static native int elemChunkElementAttrsEntry(long ctx, long elems, int n);
  public static native int elemChunkLeaf(long ctx, long elems, int n);
  public static native int elemLeafElement(long ctx, long elems, int n);
  public static native int elemuMetricsBatch(long ctx, long elems, int n, long tok0);
  public static native int elemPair(long ctx, long elems, int n);
  public static native int elemProbe(long ctx, long elems, int n);
  public static native int elemResultRaw(long ctx, long elems, int n);
  public static native int elemSurrogateAttrsEntry(long ctx, long elems, int n);
  public static native int elemuTaskDetailed(long ctx, long elems, int n, long tok0);
  public static native int elemTaskOptionsOptionsEntry(long ctx, long elems, int n);
  public static native int elemuTaskSummary(long ctx, long elems, int n, long tok0);
}
