// Requirement 24: read back the JIT tier of the code a case runs, not only the settings.
//
// An in-process EventListener on the runtime's own event source (JIT keyword, verbose)
// receives MethodLoadVerbose for every method compiled, with the optimization tier in bits
// 7-9 of MethodFlags (the runtime's JitOptimizationTier; names as TraceEvent's
// OptimizationTier). Events arrive late on the runtime's dispatch thread, so they are
// attributed to a case by their own timestamp against the times the diagnoser records at
// BDN's BeforeAnythingElse / BeforeActualRun / AfterActualRun signals, after the run.
//
// Per case the exporter writes: compilations before the actual stage (jitting, pilot,
// warm-up) and inside it by tier, and the methods compiled in the case whose LAST
// version at the end of the span is still a tier-0 form, and among them the ones the runtime
// promotes later ("hot_tier0": hot code this case measured at tier 0). A case with no
// compilation in its span and hot_tier0 = 0 measured final-tier code.

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics.Tracing;
using System.Linq;

namespace Armonik.Ffi.Bdn;

public sealed class JitTiers : EventListener
{
    public static readonly string[] TierName =
        { "Unknown", "MinOptJitted", "Optimized", "QuickJitted", "OptimizedTier1", "OptimizedTier1OSR", "QuickJittedInstrumented", "OptimizedTier1Instrumented" };

    public readonly struct Jit
    {
        public readonly DateTime T; public readonly ulong Id; public readonly int Tier; public readonly string Name;
        public Jit(DateTime t, ulong id, int tier, string name) { T = t; Id = id; Tier = tier; Name = name; }
    }

    public static readonly ConcurrentQueue<Jit> Events = new ConcurrentQueue<Jit>();
    private static JitTiers _one;
    public static long Received;

    public static void Start() { _one ??= new JitTiers(); }

    protected override void OnEventSourceCreated(EventSource es)
    {
        if (es.Name == "Microsoft-Windows-DotNETRuntime") EnableEvents(es, EventLevel.Verbose, (EventKeywords)0x10);
    }

    protected override void OnEventWritten(EventWrittenEventArgs e)
    {
        if (e.EventName == null || !e.EventName.StartsWith("MethodLoadVerbose", StringComparison.Ordinal)) return;
        var n = e.PayloadNames;
        object P(string k) { int i = n.IndexOf(k); return i >= 0 ? e.Payload[i] : null; }
        uint flags = Convert.ToUInt32(P("MethodFlags"));
        var ns = P("MethodNamespace") as string ?? "";
        if (Excluded(ns)) return;
        var t = e.TimeStamp.Kind == DateTimeKind.Local ? e.TimeStamp.ToUniversalTime() : e.TimeStamp;
        Events.Enqueue(new Jit(t, Convert.ToUInt64(P("MethodID")), (int)((flags >> 7) & 0x7), ns + "::" + (P("MethodName") as string)));
        System.Threading.Interlocked.Increment(ref Received);
    }

    /// Not the measured code: the BDN engine (its statistics, logging, reflection) and this
    /// harness's own instrumentation. BDN's emitted workload loop
    /// (BenchmarkDotNet.Autogenerated) IS measured, and so is the runtime library code the
    /// arms call (UTF-8 transcoding, span helpers, memmove). Heuristic by name; every method
    /// counted is named in the rows, so the list can be audited.
    private static readonly string[] EnginePrefixes =
    {
        "BenchmarkDotNet.", "Perfolizer", "Pragmastat", "System.Collections.Immutable", "System.Reflection", "System.Linq",
        "System.Number", "System.Globalization", "System.IO", "System.Text.StringBuilder", "System.Enum", "System.TimeSpan",
        "System.Diagnostics", "System.Console", "System.Threading", "Armonik.Ffi.Bdn.",
    };
    private static bool Excluded(string ns)
    {
        if (ns.StartsWith("BenchmarkDotNet.Autogenerated", StringComparison.Ordinal) || ns.StartsWith("Armonik.Ffi.Bdn.CodecSuite", StringComparison.Ordinal)) return false;
        foreach (var p in EnginePrefixes) if (ns.StartsWith(p, StringComparison.Ordinal)) return true;
        return ns.Contains("[System.Double]", StringComparison.Ordinal) || ns.Contains("[BenchmarkDotNet.", StringComparison.Ordinal)
            || ns.Contains("[Perfolizer", StringComparison.Ordinal) || ns.Contains("[Pragmastat", StringComparison.Ordinal)
            || ns.Contains("[Armonik.Ffi.Bdn.", StringComparison.Ordinal) || ns.Contains("[System.Collections.Immutable", StringComparison.Ordinal);
    }

    private static bool Tier0(int t) => t == 1 || t == 3 || t == 6;

    /// The JSON fragment for one case, given its signal times.
    private static Jit[] _all;
    private static Dictionary<ulong, DateTime> _first;

    /// Called once all events have arrived (the exporter waits for the stream to go quiet).
    public static void Freeze()
    {
        _all = Events.ToArray();
        _first = _all.GroupBy(j => j.Id).ToDictionary(g => g.Key, g => g.Min(j => j.T));
    }

    /// ts = the end of this case's GlobalSetup: a method first compiled between t0 and ts is
    /// setup code (payload builders), not measured, and is left out.
    public static string Summarise(DateTime t0, DateTime ts, DateTime t1, DateTime t2, out int spanCount, out int hotTier0)
    {
        if (_all == null) Freeze();
        var all = _all;
        bool Setup(Jit j) { var f = _first[j.Id]; return f >= t0 && f < ts; }
        var pre = all.Where(j => j.T >= t0 && j.T < t1 && !Setup(j)).ToList();
        var span = all.Where(j => j.T >= t1 && j.T <= t2 && !Setup(j)).ToList();
        var mine = new HashSet<ulong>(all.Where(j => _first[j.Id] >= ts && _first[j.Id] <= t2).Select(j => j.Id));
        var last = all.Where(j => j.T <= t2 && mine.Contains(j.Id)).GroupBy(j => j.Id).Select(g => g.OrderBy(j => j.T).Last()).ToList();
        var left = last.Where(j => Tier0(j.Tier)).ToList();
        // A tier-0 method that the runtime promotes LATER was hot while this case measured
        // it at tier 0: the decisive signal. (One that is never promoted was called fewer
        // times than the call-count threshold, or the process ended first.)
        var later = all.Where(j => j.T > t2 && !Tier0(j.Tier)).Select(j => j.Id).ToHashSet();
        var hot = left.Where(j => later.Contains(j.Id)).ToList();
        spanCount = span.Count; hotTier0 = hot.Count;
        string ByTier(List<Jit> l) => "{" + string.Join(",", l.GroupBy(j => j.Tier).OrderBy(g => g.Key).Select(g => "\"" + TierName[g.Key] + "\":" + g.Count())) + "}";
        string Names(IEnumerable<Jit> l) => "[" + string.Join(",", l.Take(8).Select(j => "\"" + J(j.Name) + "@" + TierName[j.Tier] + "\"")) + "]";
        return "\"jit_pre\":" + ByTier(pre) + ",\"jit_span\":" + ByTier(span) + ",\"jit_span_methods\":" + Names(span)
             + ",\"tier0_left\":" + left.Count + ",\"tier0_left_methods\":" + Names(left)
             + ",\"hot_tier0\":" + hot.Count + ",\"hot_tier0_methods\":" + Names(hot);
    }

    private static string J(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
