// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

/** google.protobuf.Duration, copied rather than imported */
public final class Duration {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public long seconds = 0L;
  public int nanos = 0;
}
