// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

/** Protos/V1/results_common.proto, tags preserved including the gap at 7 */
public final class ResultRaw {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public String session_id = "";
  public String name = "";
  public String owner_task_id = "";
  public int status = 0;
  public Timestamp created_at = null;
  public Timestamp completed_at = null;
  public String result_id = "";
  public long size = 0L;
  public String created_by = "";
  public byte[] opaque_id = EMPTY_BYTES;
  public boolean manual_deletion = false;
}
