// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus;

/** Protos/V1/objects.proto */
public final class TaskOptions {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public java.util.TreeMap<String, String> options = new java.util.TreeMap<String, String>();
  public Duration max_duration = null;
  public int max_retries = 0;
  public int priority = 0;
  public String partition_id = "";
  public String application_name = "";
  public String application_version = "";
  public String application_namespace = "";
  public String application_service = "";
  public String engine_type = "";
}
