// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus.borrow;

/** invented; both shapes are real, the schema has 19 oneofs in 413 fields */
public final class Probe {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public ak.Utf8View id = ak.Utf8View.EMPTY;
  public int opt_count = 0;
  public boolean has_opt_count;
  public ak.Utf8View opt_label = null;
  public boolean opt_flag = false;
  public boolean has_opt_flag;

  /** oneof `body`: a case tag plus one slot per member. The case value
   *  is the member's TAG, as in the ABI group; `BODY_CASE_NONE` is none.
   *  A case that is neither 0 nor a member tag is REFUSED by every
   *  encoder (plan: oneof_checks). */
  public static final int BODY_CASE_NONE = 0;
  public static final int BODY_CASE_AS_INT = 10;
  public static final int BODY_CASE_AS_TEXT = 11;
  public static final int BODY_CASE_AS_BLOB = 12;
  public static final int BODY_CASE_AS_STAMP = 13;
  public static final int BODY_CASE_AS_NOTHING = 14;
  public int body_case;
  public long body_as_int = 0L;
  public ak.Utf8View body_as_text = null;
  public byte[] body_as_blob = EMPTY_BYTES;
  public Timestamp body_as_stamp = null;
  public Empty body_as_nothing = null;

  /** Unknown fields captured by a retain-mode codec, verbatim, key included;
   *  re-emitted after the known fields. `null` when none. */
  public byte[] unknownFields;
}
