// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus.borrow;

/** invented for the corpus */
public final class WireZoo {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public int v_int32 = 0;
  public long v_int64 = 0L;
  public boolean v_bool = false;
  public double v_double = 0.0;
  public int v_fixed32 = 0;
  public ak.Utf8View v_string = ak.Utf8View.EMPTY;
  public byte[] v_bytes = EMPTY_BYTES;
  public int v_enum = 0;
  public Timestamp v_msg = null;
  public int v_big_tag = 0;

  /** Unknown fields captured by a retain-mode codec, verbatim, key included;
   *  re-emitted after the known fields. `null` when none. */
  public byte[] unknownFields;
}
