//! @generated by ffi/poc/csharp/gen/rs_probe.py. Do not edit.
//!
//! Print the size and field offsets of every ABI struct the C# binding declares,
//! and the value of every presence constant it reads.
//!
//! ABI v1 obligation 12.3. See Cargo.toml for why this slice needs it and the
//! earlier ones did not: C# re-declares these types by hand, so the managed
//! `[StructLayout]` is a second declaration and only agreement makes the
//! by-value group work.
//!
//! Output is JSON on stdout, consumed by `gen/cs_abi.py`. Nothing here is
//! measured; it is a build step.

use ak_abi::generated::abi::*;
use ak_abi::{ak_span, ak_str};
use std::mem::{align_of, size_of};

macro_rules! lay {
    ($out:expr, $t:ty, [$($f:ident),* $(,)?]) => {{
        let v = <$t>::ZERO;
        let base = &v as *const $t as usize;
        let mut fields: Vec<String> = Vec::new();
        $(
            let off = (&v.$f as *const _ as usize) - base;
            fields.push(format!("\"{}\": {}", stringify!($f), off));
        )*
        $out.push(format!(
            "    \"{}\": {{ \"size\": {}, \"align\": {}, \"fields\": {{ {} }} }}",
            stringify!($t), size_of::<$t>(), align_of::<$t>(), fields.join(", ")
        ));
    }};
}

/// A struct with no ZERO const, laid out by a default instance instead.
macro_rules! lay_raw {
    ($out:expr, $t:ty, $v:expr, [$($f:ident),* $(,)?]) => {{
        let v: $t = $v;
        let base = &v as *const $t as usize;
        let mut fields: Vec<String> = Vec::new();
        $(
            let off = (&v.$f as *const _ as usize) - base;
            fields.push(format!("\"{}\": {}", stringify!($f), off));
        )*
        $out.push(format!(
            "    \"{}\": {{ \"size\": {}, \"align\": {}, \"fields\": {{ {} }} }}",
            stringify!($t), size_of::<$t>(), align_of::<$t>(), fields.join(", ")
        ));
    }};
}

/// Every vtable's SLOT COUNT. Every slot is pointer sized, so a wrong count is a
/// wrong size and nothing subtler is needed to catch it -- which is the check
/// that would have caught a slot invented by analogy on `ak_dvt_TaskDetailed`.
macro_rules! vt {
    ($out:expr, $t:ty) => {{
        $out.push(format!(
            "    \"{}\": {{ \"size\": {}, \"slots\": {} }}",
            stringify!($t), size_of::<$t>(), size_of::<$t>() / size_of::<usize>()
        ));
    }};
}

fn main() {
    let mut out: Vec<String> = Vec::new();
    let mut pres: Vec<String> = Vec::new();
    let mut vts: Vec<String> = Vec::new();
    macro_rules! pc {
        ($c:ident) => { pres.push(format!("    \"{}\": {}", stringify!($c), $c)); };
    }

    lay_raw!(out, ak_str, ak_str::default(), [data, len, tc]);
    lay_raw!(out, ak_span, ak_span::default(), [off, len, coder]);

    // ENCODE: the by-value group.
    lay!(out, ak_efix_ListResultsResponse, [page, total, presence]);
    lay!(out, ak_efix_ResultRaw, [session_id, name, owner_task_id, status, created_at, completed_at, result_id, size, created_by, opaque_id, manual_deletion, presence]);
    lay!(out, ak_efix_Timestamp, [seconds, nanos, presence]);
    lay!(out, ak_efix_ListTasksDetailedResponse, [page, total, presence]);
    lay!(out, ak_efix_TaskDetailed, [id, session_id, owner_pod_id, status, status_message, options, created_at, submitted_at, started_at, ended_at, pod_ttl, output, pod_hostname, received_at, acquired_at, creation_to_end_duration, processing_to_end_duration, initial_task_id, received_to_end_duration, processed_at, fetched_at, payload_id, created_by, presence]);
    lay!(out, ak_efix_TaskOptions, [max_duration, max_retries, priority, partition_id, application_name, application_version, application_namespace, application_service, engine_type, presence]);
    lay!(out, ak_efix_Duration, [seconds, nanos, presence]);
    lay!(out, ak_efix_TaskOutput, [success, error, presence]);
    lay!(out, ak_efix_ListProbeResponse, [presence]);
    lay!(out, ak_efix_Probe, [id, opt_count, opt_label, opt_flag, body_case, body_as_int, body_as_text, body_as_blob, body_as_stamp, body_as_nothing, presence]);
    lay!(out, ak_efix_Empty, [presence]);
    lay!(out, ak_efix_ListTaskSummaryResponse, [presence]);
    lay!(out, ak_efix_TaskSummary, [id, session_id, options, status, created_at, error, status_message, count_data_dependencies, presence]);
    lay!(out, ak_efix_UploadResultDataMessage, [upload, presence]);
    lay!(out, ak_efix_UploadResultData, [session_id, result_id, data_chunk, presence]);
    lay!(out, ak_efix_ListMetricsResponse, [presence]);
    lay!(out, ak_efix_MetricsBatch, [id, presence]);
    lay!(out, ak_efix_DualResponse, [presence]);
    lay!(out, ak_efix_Pair, [key, value, presence]);
    lay!(out, ak_efix_TaskOptionsOptionsEntry, [key, value, presence]);

    // DECODE: the by-value group, whose blobs are ak_span OFFSETS.
    lay!(out, ak_dfix_ListResultsResponse, [page, total, presence]);
    lay!(out, ak_dfix_ResultRaw, [session_id, name, owner_task_id, status, created_at, completed_at, result_id, size, created_by, opaque_id, manual_deletion, presence]);
    lay!(out, ak_dfix_Timestamp, [seconds, nanos, presence]);
    lay!(out, ak_dfix_ListTasksDetailedResponse, [page, total, presence]);
    lay!(out, ak_dfix_TaskDetailed, [id, session_id, owner_pod_id, status, status_message, options, created_at, submitted_at, started_at, ended_at, pod_ttl, output, pod_hostname, received_at, acquired_at, creation_to_end_duration, processing_to_end_duration, initial_task_id, received_to_end_duration, processed_at, fetched_at, payload_id, created_by, presence]);
    lay!(out, ak_dfix_TaskOptions, [max_duration, max_retries, priority, partition_id, application_name, application_version, application_namespace, application_service, engine_type, presence]);
    lay!(out, ak_dfix_Duration, [seconds, nanos, presence]);
    lay!(out, ak_dfix_TaskOutput, [success, error, presence]);
    lay!(out, ak_dfix_ListProbeResponse, [presence]);
    lay!(out, ak_dfix_Probe, [id, opt_count, opt_label, opt_flag, body_case, body_as_int, body_as_text, body_as_blob, body_as_stamp, body_as_nothing, presence]);
    lay!(out, ak_dfix_Empty, [presence]);
    lay!(out, ak_dfix_ListTaskSummaryResponse, [presence]);
    lay!(out, ak_dfix_TaskSummary, [id, session_id, options, status, created_at, error, status_message, count_data_dependencies, presence]);
    lay!(out, ak_dfix_UploadResultDataMessage, [upload, presence]);
    lay!(out, ak_dfix_UploadResultData, [session_id, result_id, data_chunk, presence]);
    lay!(out, ak_dfix_ListMetricsResponse, [presence]);
    lay!(out, ak_dfix_MetricsBatch, [id, presence]);
    lay!(out, ak_dfix_DualResponse, [presence]);
    lay!(out, ak_dfix_Pair, [key, value, presence]);
    lay!(out, ak_dfix_TaskOptionsOptionsEntry, [key, value, presence]);

    // The presence bits, read from the Rust constants rather than
    // inferred from a field's position among the singular message children.
    // The obvious rule is right today and is still a guess.
    pc!(AK_EFIX_RESULTRAW_PRESENT_CREATED_AT);
    pc!(AK_EFIX_RESULTRAW_PRESENT_COMPLETED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_OPTIONS);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_CREATED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_SUBMITTED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_STARTED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_ENDED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_POD_TTL);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_OUTPUT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_RECEIVED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_ACQUIRED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_PROCESSED_AT);
    pc!(AK_EFIX_TASKDETAILED_PRESENT_FETCHED_AT);
    pc!(AK_EFIX_TASKOPTIONS_PRESENT_MAX_DURATION);
    pc!(AK_EFIX_PROBE_PRESENT_OPT_COUNT);
    pc!(AK_EFIX_PROBE_PRESENT_OPT_LABEL);
    pc!(AK_EFIX_PROBE_PRESENT_OPT_FLAG);
    pc!(AK_EFIX_TASKSUMMARY_PRESENT_OPTIONS);
    pc!(AK_EFIX_TASKSUMMARY_PRESENT_CREATED_AT);
    pc!(AK_EFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD);
    pc!(AK_DFIX_RESULTRAW_PRESENT_CREATED_AT);
    pc!(AK_DFIX_RESULTRAW_PRESENT_COMPLETED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_OPTIONS);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_CREATED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_SUBMITTED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_STARTED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_ENDED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_POD_TTL);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_OUTPUT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_RECEIVED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_ACQUIRED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_CREATION_TO_END_DURATION);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_PROCESSING_TO_END_DURATION);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_RECEIVED_TO_END_DURATION);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_PROCESSED_AT);
    pc!(AK_DFIX_TASKDETAILED_PRESENT_FETCHED_AT);
    pc!(AK_DFIX_TASKOPTIONS_PRESENT_MAX_DURATION);
    pc!(AK_DFIX_PROBE_PRESENT_OPT_COUNT);
    pc!(AK_DFIX_PROBE_PRESENT_OPT_LABEL);
    pc!(AK_DFIX_PROBE_PRESENT_OPT_FLAG);
    pc!(AK_DFIX_TASKSUMMARY_PRESENT_OPTIONS);
    pc!(AK_DFIX_TASKSUMMARY_PRESENT_CREATED_AT);
    pc!(AK_DFIX_UPLOADRESULTDATAMESSAGE_PRESENT_UPLOAD);

    // The vtables. A message that only ever appears as an INLINED
    // child has none: TaskOptions is reached through TaskDetailed's.
    vt!(vts, ak_evt_ListResultsResponse);
    vt!(vts, ak_dvt_ListResultsResponse);
    vt!(vts, ak_evt_ListTasksDetailedResponse);
    vt!(vts, ak_dvt_ListTasksDetailedResponse);
    vt!(vts, ak_evt_ListProbeResponse);
    vt!(vts, ak_dvt_ListProbeResponse);
    vt!(vts, ak_evt_ListTaskSummaryResponse);
    vt!(vts, ak_dvt_ListTaskSummaryResponse);
    vt!(vts, ak_evt_UploadResultDataMessage);
    vt!(vts, ak_dvt_UploadResultDataMessage);
    vt!(vts, ak_evt_ListMetricsResponse);
    vt!(vts, ak_dvt_ListMetricsResponse);
    vt!(vts, ak_evt_DualResponse);
    vt!(vts, ak_dvt_DualResponse);
    vt!(vts, ak_evt_ResultRaw);
    vt!(vts, ak_dvt_ResultRaw);
    vt!(vts, ak_evt_TaskDetailed);
    vt!(vts, ak_dvt_TaskDetailed);
    vt!(vts, ak_evt_TaskOptionsOptionsEntry);
    vt!(vts, ak_dvt_TaskOptionsOptionsEntry);
    vt!(vts, ak_evt_Probe);
    vt!(vts, ak_dvt_Probe);
    vt!(vts, ak_evt_TaskSummary);
    vt!(vts, ak_dvt_TaskSummary);
    vt!(vts, ak_evt_MetricsBatch);
    vt!(vts, ak_dvt_MetricsBatch);
    vt!(vts, ak_evt_Pair);
    vt!(vts, ak_dvt_Pair);

    println!("{{");
    println!("  \"pointer_width\": {},", size_of::<usize>() * 8);
    println!("  \"structs\": {{");
    println!("{}", out.join(",\n"));
    println!("  }},");
    println!("  \"presence\": {{");
    println!("{}", pres.join(",\n"));
    println!("  }},");
    println!("  \"vtables\": {{");
    println!("{}", vts.join(",\n"));
    println!("  }}");
    println!("}}");
}
