// @generated by ffi/poc/java/gen/java_corpus.py (corpus glue). Do not edit.

package ak.shapes;

import ak.Dec;
import ak.Enc;

/** Root name -> each arm's decode and encode, so the corpus harness carries no
 *  reflection. Arm R for every message; the binding for the C ABI's roots. */
public final class Dispatch {
  private Dispatch() {}

  public static final String[] ALL = {"Timestamp", "Duration", "ResultRaw", "TaskOptions", "TaskOutput", "TaskDetailed", "TaskSummary", "Probe", "Empty", "UploadResultData", "MetricsBatch", "Pair", "ListResultsResponse", "ListTasksDetailedResponse", "ListTaskSummaryResponse", "ListProbeResponse", "ListMetricsResponse", "UploadResultDataMessage", "DualResponse"};
  public static final String[] ABI = {"ListResultsResponse", "ListTasksDetailedResponse", "ListProbeResponse", "ListTaskSummaryResponse", "UploadResultDataMessage", "ListMetricsResponse", "DualResponse"};

  /** The no-unknown build (WP5 step 10) has no retain codec. */
  public static Object decRRetain(String root, byte[] b) {
    throw new UnsupportedOperationException("no-unknown build: no retain mode");
  }

  public static byte[] encRRetain(String root, Object o) {
    throw new UnsupportedOperationException("no-unknown build: no retain mode");
  }

  public static Object decR(String root, byte[] b) {
    Dec d = new Dec().reset(b, 0, b.length);
    switch (root) {
      case "Timestamp": return Codec.decTimestamp(d);
      case "Duration": return Codec.decDuration(d);
      case "ResultRaw": return Codec.decResultRaw(d);
      case "TaskOptions": return Codec.decTaskOptions(d);
      case "TaskOutput": return Codec.decTaskOutput(d);
      case "TaskDetailed": return Codec.decTaskDetailed(d);
      case "TaskSummary": return Codec.decTaskSummary(d);
      case "Probe": return Codec.decProbe(d);
      case "Empty": return Codec.decEmpty(d);
      case "UploadResultData": return Codec.decUploadResultData(d);
      case "MetricsBatch": return Codec.decMetricsBatch(d);
      case "Pair": return Codec.decPair(d);
      case "ListResultsResponse": return Codec.decListResultsResponse(d);
      case "ListTasksDetailedResponse": return Codec.decListTasksDetailedResponse(d);
      case "ListTaskSummaryResponse": return Codec.decListTaskSummaryResponse(d);
      case "ListProbeResponse": return Codec.decListProbeResponse(d);
      case "ListMetricsResponse": return Codec.decListMetricsResponse(d);
      case "UploadResultDataMessage": return Codec.decUploadResultDataMessage(d);
      case "DualResponse": return Codec.decDualResponse(d);
      default: throw new IllegalArgumentException(root);
    }
  }

  public static byte[] encR(String root, Object o) {
    Enc e = new Enc(Codec.SITES);
    e.reset();
    switch (root) {
      case "Timestamp": Codec.encTimestamp(e, (Timestamp) o); break;
      case "Duration": Codec.encDuration(e, (Duration) o); break;
      case "ResultRaw": Codec.encResultRaw(e, (ResultRaw) o); break;
      case "TaskOptions": Codec.encTaskOptions(e, (TaskOptions) o); break;
      case "TaskOutput": Codec.encTaskOutput(e, (TaskOutput) o); break;
      case "TaskDetailed": Codec.encTaskDetailed(e, (TaskDetailed) o); break;
      case "TaskSummary": Codec.encTaskSummary(e, (TaskSummary) o); break;
      case "Probe": Codec.encProbe(e, (Probe) o); break;
      case "Empty": Codec.encEmpty(e, (Empty) o); break;
      case "UploadResultData": Codec.encUploadResultData(e, (UploadResultData) o); break;
      case "MetricsBatch": Codec.encMetricsBatch(e, (MetricsBatch) o); break;
      case "Pair": Codec.encPair(e, (Pair) o); break;
      case "ListResultsResponse": Codec.encListResultsResponse(e, (ListResultsResponse) o); break;
      case "ListTasksDetailedResponse": Codec.encListTasksDetailedResponse(e, (ListTasksDetailedResponse) o); break;
      case "ListTaskSummaryResponse": Codec.encListTaskSummaryResponse(e, (ListTaskSummaryResponse) o); break;
      case "ListProbeResponse": Codec.encListProbeResponse(e, (ListProbeResponse) o); break;
      case "ListMetricsResponse": Codec.encListMetricsResponse(e, (ListMetricsResponse) o); break;
      case "UploadResultDataMessage": Codec.encUploadResultDataMessage(e, (UploadResultDataMessage) o); break;
      case "DualResponse": Codec.encDualResponse(e, (DualResponse) o); break;
      default: throw new IllegalArgumentException(root);
    }
    return e.toBytes();
  }

  public static Object decFfi(Binding b, String root, byte[] w) {
    switch (root) {
      case "ListResultsResponse": return b.decodeListResultsResponse(w, 0, w.length);
      case "ListTasksDetailedResponse": return b.decodeListTasksDetailedResponse(w, 0, w.length);
      case "ListProbeResponse": return b.decodeListProbeResponse(w, 0, w.length);
      case "ListTaskSummaryResponse": return b.decodeListTaskSummaryResponse(w, 0, w.length);
      case "UploadResultDataMessage": return b.decodeUploadResultDataMessage(w, 0, w.length);
      case "ListMetricsResponse": return b.decodeListMetricsResponse(w, 0, w.length);
      case "DualResponse": return b.decodeDualResponse(w, 0, w.length);
      default: throw new IllegalArgumentException(root);
    }
  }

  public static Object parseFfi(Binding b, String root, byte[] w) {
    switch (root) {
      case "ListResultsResponse": return b.parseListResultsResponse(w, 0, w.length);
      case "ListTasksDetailedResponse": return b.parseListTasksDetailedResponse(w, 0, w.length);
      case "ListProbeResponse": return b.parseListProbeResponse(w, 0, w.length);
      case "ListTaskSummaryResponse": return b.parseListTaskSummaryResponse(w, 0, w.length);
      case "UploadResultDataMessage": return b.parseUploadResultDataMessage(w, 0, w.length);
      case "ListMetricsResponse": return b.parseListMetricsResponse(w, 0, w.length);
      case "DualResponse": return b.parseDualResponse(w, 0, w.length);
      default: throw new IllegalArgumentException(root);
    }
  }

  public static byte[] encFfi(Binding b, String root, Object o) {
    switch (root) {
      case "ListResultsResponse": b.encodeListResultsResponse((ListResultsResponse) o); break;
      case "ListTasksDetailedResponse": b.encodeListTasksDetailedResponse((ListTasksDetailedResponse) o); break;
      case "ListProbeResponse": b.encodeListProbeResponse((ListProbeResponse) o); break;
      case "ListTaskSummaryResponse": b.encodeListTaskSummaryResponse((ListTaskSummaryResponse) o); break;
      case "UploadResultDataMessage": b.encodeUploadResultDataMessage((UploadResultDataMessage) o); break;
      case "ListMetricsResponse": b.encodeListMetricsResponse((ListMetricsResponse) o); break;
      case "DualResponse": b.encodeDualResponse((DualResponse) o); break;
      default: throw new IllegalArgumentException(root);
    }
    return b.take();
  }

  /** Decision 11's retain mode on this binding; the no-unknown build refuses it. */
  public static void setRetain(Binding b, boolean on) {
    if (on) throw new UnsupportedOperationException("no-unknown build: no retain mode");
  }

  /** {buffers reclaimed after failed decodes, left after successful ones}. */
  public static long[] unkCounters(Binding b) {
    return new long[] {0L, 0L};
  }
}
