// @generated by ffi/poc/java/gen/generate.py from ffi/schema/shapes.json. Do not edit.

package ak.shapes;

import ak.Values;

/** Build any payload of shapes.json as protobuf-java values: the incumbent's objects. */
public final class PbBuild {
  private PbBuild() {}

  static ak.pb.Timestamp mkTimestamp(int idx) {
    return ak.pb.Timestamp.newBuilder()
        .setSeconds(Values.stampSeconds(idx)).setNanos(Values.stampNanos(idx)).build();
  }

  static ak.pb.Duration mkDuration(int idx) {
    return ak.pb.Duration.newBuilder()
        .setSeconds(Values.durSeconds(idx)).setNanos(Values.durNanos(idx)).build();
  }


  public static ak.pb.ResultRaw buildResultRaw(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.ResultRaw.Builder b = ak.pb.ResultRaw.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setSessionId(Values.recode(Values.guid((path + ".session_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setName(Values.recode(Values.word((path + ".name"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setOwnerTaskId(Values.recode(Values.guid((path + ".owner_task_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setStatusValue(Values.enumValue(ak.shapes.ResultStatus.DECLARED, (int) idx));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCreatedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT || mode == Build.HALF_ABSENT)) {
      b.setCompletedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setResultId(Values.recode(Values.guid((path + ".result_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setSize(Values.scalarI64((path + ".size"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCreatedBy(Values.recode(Values.guid((path + ".created_by"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setOpaqueId(com.google.protobuf.ByteString.copyFrom(Values.blob((path + ".opaque_id"), (int) idx, 16)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setManualDeletion(Values.scalarBool((path + ".manual_deletion"), (int) (idx)));
    }
    return b.build();
  }

  public static ak.pb.TaskOptions buildTaskOptions(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.TaskOptions.Builder b = ak.pb.TaskOptions.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int k = 0; k < 4; k++) {
        String key = Build.pad2(k) + Values.recode(Values.word(path + ".options.key", idx * 31 + k), cs);
        String val = "";
        if (!(mode == Build.HALF_ABSENT && k % 2 == 0))
          val = Values.recode(Values.word(path + ".options.value", idx * 31 + k), cs);
        b.putOptions(key, val);
      }
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setMaxDuration(mkDuration((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setMaxRetries(Values.scalarI32((path + ".max_retries"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPriority(Values.scalarI32((path + ".priority"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPartitionId(Values.recode(Values.word((path + ".partition_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setApplicationName(Values.recode(Values.word((path + ".application_name"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setApplicationVersion(Values.recode(Values.word((path + ".application_version"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setApplicationNamespace(Values.recode(Values.word((path + ".application_namespace"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setApplicationService(Values.recode(Values.word((path + ".application_service"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setEngineType(Values.recode(Values.word((path + ".engine_type"), (int) (idx)), cs));
    }
    return b.build();
  }

  public static ak.pb.TaskOutput buildTaskOutput(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.TaskOutput.Builder b = ak.pb.TaskOutput.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setSuccess(Values.scalarBool((path + ".success"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setError(Values.recode(Values.sentence((path + ".error"), (int) (idx)), cs));
    }
    return b.build();
  }

  public static ak.pb.TaskDetailed buildTaskDetailed(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.TaskDetailed.Builder b = ak.pb.TaskDetailed.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setId(Values.recode(Values.guid((path + ".id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setSessionId(Values.recode(Values.guid((path + ".session_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setOwnerPodId(Values.recode(Values.guid((path + ".owner_pod_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addParentTaskIds(Values.recode(Values.guid((path + ".parent_task_ids"), (int) (idx * 211 + j)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addDataDependencies(Values.recode(Values.guid((path + ".data_dependencies"), (int) (idx * 211 + j)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addExpectedOutputIds(Values.recode(Values.guid((path + ".expected_output_ids"), (int) (idx * 211 + j)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addRetryOfIds(Values.recode(Values.guid((path + ".retry_of_ids"), (int) (idx * 211 + j)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setStatusValue(Values.enumValue(ak.shapes.TaskStatus.DECLARED, (int) idx));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setStatusMessage(Values.recode(Values.sentence((path + ".status_message"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setOptions(buildTaskOptions((path + ".options"), idx, mode, repeats, bulk, cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCreatedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT || mode == Build.HALF_ABSENT)) {
      b.setSubmittedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setStartedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT || mode == Build.HALF_ABSENT)) {
      b.setEndedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPodTtl(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT || mode == Build.HALF_ABSENT)) {
      switch (Build.adapterState(idx)) {
        case Build.ADAPTER_INVALID: break;
        case Build.ADAPTER_OK:
          b.setOutput(ak.pb.TaskOutput.newBuilder().setSuccess(true));
          break;
        default:
          b.setOutput(ak.pb.TaskOutput.newBuilder().setError(Values.recode(Values.sentence(path + ".output.error", (int) idx), cs)));
          break;
      }
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPodHostname(Values.recode(Values.word((path + ".pod_hostname"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT || mode == Build.HALF_ABSENT)) {
      b.setReceivedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setAcquiredAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCreationToEndDuration(mkDuration((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setProcessingToEndDuration(mkDuration((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setInitialTaskId(Values.recode(Values.guid((path + ".initial_task_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setReceivedToEndDuration(mkDuration((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT || mode == Build.HALF_ABSENT)) {
      b.setProcessedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setFetchedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPayloadId(Values.recode(Values.guid((path + ".payload_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCreatedBy(Values.recode(Values.guid((path + ".created_by"), (int) (idx)), cs));
    }
    return b.build();
  }

  public static ak.pb.TaskSummary buildTaskSummary(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.TaskSummary.Builder b = ak.pb.TaskSummary.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setId(Values.recode(Values.guid((path + ".id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setSessionId(Values.recode(Values.guid((path + ".session_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setOptions(buildTaskOptions((path + ".options"), idx, mode, repeats, bulk, cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setStatusValue(Values.enumValue(ak.shapes.TaskStatus.DECLARED, (int) idx));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCreatedAt(mkTimestamp((int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT) && Build.adapterState(idx) == Build.ADAPTER_ERROR)
      b.setError(Values.recode(Values.sentence((path + ".error"), (int) (idx)), cs));
    if (!(mode == Build.ALL_ABSENT)) {
      b.setStatusMessage(Values.recode(Values.sentence((path + ".status_message"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setCountDataDependencies(Values.scalarI64((path + ".count_data_dependencies"), (int) (idx)));
    }
    return b.build();
  }

  public static ak.pb.Probe buildProbe(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.Probe.Builder b = ak.pb.Probe.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setId(Values.recode(Values.guid((path + ".id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      if (Build.explicitPresent(2, idx))
        b.setOptCount(idx % 7 == 0 ? 0 : Values.scalarI32((path + ".opt_count"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      if (Build.explicitPresent(3, idx))
        b.setOptLabel(idx % 7 == 0 ? "" : Values.recode(Values.word((path + ".opt_label"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      if (Build.explicitPresent(4, idx))
        b.setOptFlag(idx % 7 == 0 ? false : Values.scalarBool((path + ".opt_flag"), (int) (idx)));
    }
    switch (idx % 5) {
      case 0:
        b.setAsInt(Values.scalarI64("Probe.as_int", (int) idx));
        break;
      case 1:
        b.setAsText(Values.recode(Values.word("Probe.as_text", (int) idx), cs));
        break;
      case 2:
        b.setAsBlob(com.google.protobuf.ByteString.copyFrom(Values.blob("Probe.as_blob", (int) idx, 16)));
        break;
      case 3:
        b.setAsStamp(mkTimestamp((int) idx));
        break;
      default:
        b.setAsNothing(ak.pb.Empty.newBuilder());
        break;
    }
    return b.build();
  }

  public static ak.pb.Empty buildEmpty(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.Empty.Builder b = ak.pb.Empty.newBuilder();
    return b.build();
  }

  public static ak.pb.UploadResultData buildUploadResultData(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.UploadResultData.Builder b = ak.pb.UploadResultData.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setSessionId(Values.recode(Values.guid((path + ".session_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setResultId(Values.recode(Values.guid((path + ".result_id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setDataChunk(com.google.protobuf.ByteString.copyFrom(Values.bulk(bulk)));
    }
    return b.build();
  }

  public static ak.pb.MetricsBatch buildMetricsBatch(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.MetricsBatch.Builder b = ak.pb.MetricsBatch.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setId(Values.recode(Values.guid((path + ".id"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < 30; j++)
        b.addTicks(Values.scalarI64((path + ".ticks"), (int) (idx * 97 + j)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < 30; j++)
        b.addValues(Values.scalarDouble((path + ".values"), (int) (idx * 97 + j)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < 30; j++)
        b.addCodes(Values.scalarI32((path + ".codes"), (int) (idx * 97 + j)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < 30; j++)
        b.addFlags(Values.scalarBool((path + ".flags"), (int) (idx * 97 + j)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < 30; j++)
        b.addStatusesValue(Values.enumValue(ak.shapes.TaskStatus.DECLARED, idx * 97 + j));
    }
    return b.build();
  }

  public static ak.pb.Pair buildPair(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.Pair.Builder b = ak.pb.Pair.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setKey(Values.recode(Values.word((path + ".key"), (int) (idx)), cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setValue(Values.scalarI32((path + ".value"), (int) (idx)));
    }
    return b.build();
  }

  public static ak.pb.ListResultsResponse buildListResultsResponse(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.ListResultsResponse.Builder b = ak.pb.ListResultsResponse.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addResults(buildResultRaw((path + ".results"), j, mode, repeats, bulk, cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPage(Values.scalarI32((path + ".page"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setTotal(Values.scalarI32((path + ".total"), (int) (idx)));
    }
    return b.build();
  }

  public static ak.pb.ListTasksDetailedResponse buildListTasksDetailedResponse(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.ListTasksDetailedResponse.Builder b = ak.pb.ListTasksDetailedResponse.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addTasks(buildTaskDetailed((path + ".tasks"), j, mode, repeats, bulk, cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setPage(Values.scalarI32((path + ".page"), (int) (idx)));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      b.setTotal(Values.scalarI32((path + ".total"), (int) (idx)));
    }
    return b.build();
  }

  public static ak.pb.ListTaskSummaryResponse buildListTaskSummaryResponse(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.ListTaskSummaryResponse.Builder b = ak.pb.ListTaskSummaryResponse.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addTasks(buildTaskSummary((path + ".tasks"), j, mode, repeats, bulk, cs));
    }
    return b.build();
  }

  public static ak.pb.ListProbeResponse buildListProbeResponse(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.ListProbeResponse.Builder b = ak.pb.ListProbeResponse.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addProbes(buildProbe((path + ".probes"), j, mode, repeats, bulk, cs));
    }
    return b.build();
  }

  public static ak.pb.ListMetricsResponse buildListMetricsResponse(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.ListMetricsResponse.Builder b = ak.pb.ListMetricsResponse.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addBatches(buildMetricsBatch((path + ".batches"), j, mode, repeats, bulk, cs));
    }
    return b.build();
  }

  public static ak.pb.UploadResultDataMessage buildUploadResultDataMessage(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.UploadResultDataMessage.Builder b = ak.pb.UploadResultDataMessage.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      b.setUpload(buildUploadResultData((path + ".upload"), idx, mode, repeats, bulk, cs));
    }
    return b.build();
  }

  public static ak.pb.DualResponse buildDualResponse(String path, int idx, int mode, int repeats, int bulk, int cs) {
    ak.pb.DualResponse.Builder b = ak.pb.DualResponse.newBuilder();
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addLeft(buildPair((path + ".left"), j, mode, repeats, bulk, cs));
    }
    if (!(mode == Build.ALL_ABSENT)) {
      for (int j = 0; j < repeats; j++)
        b.addRight(buildPair((path + ".right"), j, mode, repeats, bulk, cs));
    }
    return b.build();
  }

  // ---- the payload set ------------------------------------------------

  /** P1.1: ListResultsResponse, full. */
  public static ak.pb.ListResultsResponse payloadP1_1(int cs) {
    ak.pb.ListResultsResponse.Builder b = ak.pb.ListResultsResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 4; j++)
      b.addResults(buildResultRaw("ResultRaw", j, Build.FULL, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(4);
    return b.build();
  }

  /** P1.2: ListResultsResponse, full. */
  public static ak.pb.ListResultsResponse payloadP1_2(int cs) {
    ak.pb.ListResultsResponse.Builder b = ak.pb.ListResultsResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 1000; j++)
      b.addResults(buildResultRaw("ResultRaw", j, Build.FULL, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(1000);
    return b.build();
  }

  /** P1.3: ListResultsResponse, all_absent. */
  public static ak.pb.ListResultsResponse payloadP1_3(int cs) {
    ak.pb.ListResultsResponse.Builder b = ak.pb.ListResultsResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 300; j++)
      b.addResults(buildResultRaw("ResultRaw", j, Build.ALL_ABSENT, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(300);
    return b.build();
  }

  /** P2.1: ListTasksDetailedResponse, full. */
  public static ak.pb.ListTasksDetailedResponse payloadP2_1(int cs) {
    ak.pb.ListTasksDetailedResponse.Builder b = ak.pb.ListTasksDetailedResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 1; j++)
      b.addTasks(buildTaskDetailed("TaskDetailed", j, Build.FULL, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(1);
    return b.build();
  }

  /** P2.2: ListTasksDetailedResponse, full. */
  public static ak.pb.ListTasksDetailedResponse payloadP2_2(int cs) {
    ak.pb.ListTasksDetailedResponse.Builder b = ak.pb.ListTasksDetailedResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 500; j++)
      b.addTasks(buildTaskDetailed("TaskDetailed", j, Build.FULL, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(500);
    return b.build();
  }

  /** P2.3: ListTasksDetailedResponse, full. */
  public static ak.pb.ListTasksDetailedResponse payloadP2_3(int cs) {
    ak.pb.ListTasksDetailedResponse.Builder b = ak.pb.ListTasksDetailedResponse.newBuilder();
    final int[] kReps = {30};
    for (int j = 0; j < 125; j++)
      b.addTasks(buildTaskDetailed("TaskDetailed", j, Build.FULL, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(125);
    return b.build();
  }

  /** P2.4: ListTasksDetailedResponse, full. */
  public static ak.pb.ListTasksDetailedResponse payloadP2_4(int cs) {
    ak.pb.ListTasksDetailedResponse.Builder b = ak.pb.ListTasksDetailedResponse.newBuilder();
    final int[] kReps = {3, 150};
    for (int j = 0; j < 80; j++)
      b.addTasks(buildTaskDetailed("TaskDetailed", j, Build.FULL, kReps[j % 2], 0, cs));
    b.setPage(1);
    b.setTotal(80);
    return b.build();
  }

  /** P2.5: ListTasksDetailedResponse, half_absent. */
  public static ak.pb.ListTasksDetailedResponse payloadP2_5(int cs) {
    ak.pb.ListTasksDetailedResponse.Builder b = ak.pb.ListTasksDetailedResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 20; j++)
      b.addTasks(buildTaskDetailed("TaskDetailed", j, Build.HALF_ABSENT, kReps[j % 1], 0, cs));
    b.setPage(1);
    b.setTotal(20);
    return b.build();
  }

  /** P3.1: ListProbeResponse, full. */
  public static ak.pb.ListProbeResponse payloadP3_1(int cs) {
    ak.pb.ListProbeResponse.Builder b = ak.pb.ListProbeResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 200; j++)
      b.addProbes(buildProbe("Probe", j, Build.FULL, kReps[j % 1], 0, cs));
    return b.build();
  }

  /** P4.1: ListTaskSummaryResponse, full. */
  public static ak.pb.ListTaskSummaryResponse payloadP4_1(int cs) {
    ak.pb.ListTaskSummaryResponse.Builder b = ak.pb.ListTaskSummaryResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 200; j++)
      b.addTasks(buildTaskSummary("TaskSummary", j, Build.FULL, kReps[j % 1], 0, cs));
    return b.build();
  }

  /** P5.1: UploadResultDataMessage, full. */
  public static ak.pb.UploadResultDataMessage payloadP5_1(int cs) {
    ak.pb.UploadResultDataMessage.Builder b = ak.pb.UploadResultDataMessage.newBuilder();
    b.setUpload(buildUploadResultData("UploadResultData", 0, Build.FULL, 3, 36, cs));
    return b.build();
  }

  /** P5.2: UploadResultDataMessage, full. */
  public static ak.pb.UploadResultDataMessage payloadP5_2(int cs) {
    ak.pb.UploadResultDataMessage.Builder b = ak.pb.UploadResultDataMessage.newBuilder();
    b.setUpload(buildUploadResultData("UploadResultData", 0, Build.FULL, 3, 65536, cs));
    return b.build();
  }

  /** P5.3: UploadResultDataMessage, full. */
  public static ak.pb.UploadResultDataMessage payloadP5_3(int cs) {
    ak.pb.UploadResultDataMessage.Builder b = ak.pb.UploadResultDataMessage.newBuilder();
    b.setUpload(buildUploadResultData("UploadResultData", 0, Build.FULL, 3, 1048576, cs));
    return b.build();
  }

  /** P5.4: UploadResultDataMessage, full. */
  public static ak.pb.UploadResultDataMessage payloadP5_4(int cs) {
    ak.pb.UploadResultDataMessage.Builder b = ak.pb.UploadResultDataMessage.newBuilder();
    b.setUpload(buildUploadResultData("UploadResultData", 0, Build.FULL, 3, 4194304, cs));
    return b.build();
  }

  /** P6.1: ListMetricsResponse, full. */
  public static ak.pb.ListMetricsResponse payloadP6_1(int cs) {
    ak.pb.ListMetricsResponse.Builder b = ak.pb.ListMetricsResponse.newBuilder();
    final int[] kReps = {3};
    for (int j = 0; j < 200; j++)
      b.addBatches(buildMetricsBatch("MetricsBatch", j, Build.FULL, kReps[j % 1], 0, cs));
    return b.build();
  }

  // P7.1 has no builder: no canonical writer can produce it.
}
