// @generated by ffi/poc/codec/gen/java_facade.py (plan from ffi/corpus/corpus.json (reader view) over ffi/schema/shapes.json). Do not edit.

package ak.corpus.borrow;

/** Protos/V1/tasks_common.proto, tags preserved */
public final class TaskDetailed {
  static final byte[] EMPTY_BYTES = new byte[0];
  static final int[] EMPTY_I32 = new int[0];
  static final long[] EMPTY_I64 = new long[0];
  static final double[] EMPTY_F64 = new double[0];
  static final boolean[] EMPTY_BOOL = new boolean[0];

  public ak.Utf8View id = ak.Utf8View.EMPTY;
  public ak.Utf8View session_id = ak.Utf8View.EMPTY;
  public ak.Utf8View owner_pod_id = ak.Utf8View.EMPTY;
  public java.util.List<ak.Utf8View> parent_task_ids = new java.util.ArrayList<ak.Utf8View>();
  public java.util.List<ak.Utf8View> data_dependencies = new java.util.ArrayList<ak.Utf8View>();
  public java.util.List<ak.Utf8View> expected_output_ids = new java.util.ArrayList<ak.Utf8View>();
  public java.util.List<ak.Utf8View> retry_of_ids = new java.util.ArrayList<ak.Utf8View>();
  public int status = 0;
  public ak.Utf8View status_message = ak.Utf8View.EMPTY;
  public TaskOptions options = null;
  public Timestamp created_at = null;
  public Timestamp submitted_at = null;
  public Timestamp started_at = null;
  public Timestamp ended_at = null;
  public Timestamp pod_ttl = null;
  public TaskOutput output = null;
  public ak.Utf8View pod_hostname = ak.Utf8View.EMPTY;
  public Timestamp received_at = null;
  public Timestamp acquired_at = null;
  public Duration creation_to_end_duration = null;
  public Duration processing_to_end_duration = null;
  public ak.Utf8View initial_task_id = ak.Utf8View.EMPTY;
  public Duration received_to_end_duration = null;
  public Timestamp processed_at = null;
  public Timestamp fetched_at = null;
  public ak.Utf8View payload_id = ak.Utf8View.EMPTY;
  public ak.Utf8View created_by = ak.Utf8View.EMPTY;

  /** Unknown fields captured by a retain-mode codec, verbatim, key included;
   *  re-emitted after the known fields. `null` when none. */
  public byte[] unknownFields;
}
