if(NOT DEFINED SRC_FMT)
    set(SRC_FMT "https://github.com/fmtlib/fmt/archive/refs/tags/10.1.0.tar.gz")
endif()
if(NOT DEFINED SRC_SIMDJSON)
    set(SRC_SIMDJSON "https://github.com/simdjson/simdjson/archive/refs/tags/v3.2.2.tar.gz")
endif()
if(NOT DEFINED SRC_GTEST)
    set(SRC_GTEST "https://github.com/google/googletest/archive/03597a01ee50ed33e9dfd640b249b4be3799d395.zip")
endif()